zarr-developers/zarr-python

- zarr/tests/test_chunk.py
This PR upgrades c-blosc to v1.8.1, which includes a fix for using bitshuffle with single byte dtypes. Resolves #10.
> Upgrade blosc v1.8.1

- MANIFEST.in
- cpuinfo.py
- setup.py
- zarr/ext.pyx
This PR modifies setup.py to detect support for AVX2 via the [cpuinfo](https://github.com/workhorsy/py-cpuinfo) module.
Resolves #4.
cc @FrancescAlted this looks like it works, maybe useful for bcolz and python-blosc too.
> Detect AVX2

- zarr/__init__.py
- zarr/ext.pyx
- zarr/tests/test_array.py
- zarr/tests/test_chunk.py
- zarr/util.py
This PR resolves #15 by providing the option to use blosc in either contextual or non-contextual mode. The non-contextual mode (now the default) is best when using zarr in a single-threaded environment because it allows blosc to use multiple threads internally. The contextual mode is better when using zarr in a multi-threaded environment like dask.array because it avoids the blosc global lock and so multiple blosc operations can be running concurrently.
> Implement support for using global blosc functions

- zarr/attrs.py
- zarr/defaults.py
- zarr/ext.pxd
- zarr/ext.pyx
- zarr/tests/test_array.py
Resolves #11 by adding an "attr" property on all arrays with a dict-like interface for storing simple attributes with an array. Includes support for persistence and synchronization.
> Implement array attributes

- zarr/compressors.py
- zarr/util.py
This failed for me on Python 3.  There might be more cases where this is necessary
> ensure bytes for blosc name

- docs/release.rst
This PR upgrades c-blosc sub-module.
> Upgrade c-blosc to v1.10.2

- docs/release.rst
- notebooks/.ipynb_checkpoints/blosc_microbench-checkpoint.ipynb
- notebooks/blosc_microbench.ipynb
- zarr/blosc.c
- zarr/blosc.pyx
- zarr/tests/test_core.py
This PR modifies the blosc extension to return bytes instead of array.array.
> blosc returns bytes; resolves #55

- docs/api/storage.rst
- docs/release.rst
- docs/spec/v2.rst
- docs/tutorial.rst
- notebooks/.ipynb_checkpoints/zip_benchmark-checkpoint.ipynb
- notebooks/zip_benchmark.ipynb
- zarr/storage.py
- zarr/tests/test_hierarchy.py
- zarr/tests/test_storage.py
This PR changes the ZipStore implementation to avoid re-reading the zip file contents list multiple times, which was killing performance.
> fix ZipStore performance; resolves #66

- zarr/hierarchy.py
- zarr/tests/test_codecs.py
- zarr/tests/test_hierarchy.py
This fixes #88 by raising an AttributeError instead of a KeyError in __getattr__, which is the more correct thing to do (because hasattr only returns False when it gets an AttributeError, and propagates all other exceptions instead).
> raise AttributeError in __getattr__ if lookup fails

- docs/api/codecs.rst
- docs/api/core.rst
- zarr/codecs.py
- zarr/core.py
- zarr/tests/test_codecs.py
- zarr/tests/test_core.py
- zarr/tests/test_filters.py
Fixes https://github.com/alimanfoo/zarr/issues/94
Allows data to be stored with one data type. When read in with this filter, it is automatically converted to another type specified. Based largely off the `Delta` filter, but tweaked a bit. Added a few tests to make sure this is working correctly.
> AsType Filter

- docs/release.rst
Micro release to include fix for #88.
> Micro release 2.1.4

- .travis.yml
- README.rst
- tox.ini
Fixes https://github.com/alimanfoo/zarr/issues/117
Displays line numbers missed by the test coverage. Reports coverage to Coveralls. Needs to have Coveralls enabled on the repo to work.
> Use Coveralls

- zarr/codecs.py
- zarr/tests/test_codecs.py
Use string representations of `AsType`'s `dtype`s instead of allowing the `dtype`s to be converted automatically. This matches more closely with what `Delta` is doing in its representation.
> Fix representation of AsType's dtypes

- .travis.yml
- tox.ini
- zarr/codecs.py
- zarr/tests/test_codecs.py
Backport(?) of PR ( https://github.com/alimanfoo/numcodecs/pull/13 ).
Tries to use `backports.lzma` as a fallback if `lzma` is not found (e.g. Python 2). Adds testing for it on Travis CI.
> Support LZMA on Python 2 via backports.lzma

- docs/api/hierarchy.rst
- zarr/hierarchy.py
- zarr/tests/test_hierarchy.py
Fixes https://github.com/alimanfoo/zarr/issues/92
Provides `visit` and `visititem` that behave identically to their h5py counterparts. This should make it easier to traverse the full hierarchy of a Zarr group. Also should make it easier for users with h5py code to try out using Zarr with fewer changes.
> Add visitor pattern methods

- requirements_dev.txt
Fixes https://github.com/alimanfoo/zarr/issues/125
As all of these are now requirements of `setuptools` instead of being vendored as they were before, pinning them to anything other than the latest version has adverse consequences. So this drops all of these pins. More details about the problem and possible fixes in issue ( https://github.com/pypa/pip/issues/4264 ).
> Unpin setuptools requirements

- zarr/tests/test_core.py
- zarr/tests/test_util.py
- zarr/util.py
This PR focuses on support for arrays with one or more zero-length dimensions. Some changes from #154 have been manually merged. Also some further tests to verify slicing behaviour is consistent with numpy. Resolves #150.
> Zero length dimensions

- .travis.yml
- zarr/compat.py
- zarr/tests/test_core.py
- zarr/util.py
> Test and fix for #143 index with numpy integer item

- zarr/core.py
- zarr/creation.py
- zarr/storage.py
- zarr/tests/test_core.py
- zarr/tests/test_hierarchy.py
This PR provides tests and implementation of support for 0-dimensional arrays. This builds off work done in #154, however I needed to add special case implementations of ``__getitem__`` and ``__setitem__`` to the ``Array`` class to get indexing working with both empty tuple and ellipsis.
> 0-dimensional arrays

- .coveragerc
- tox.ini
- zarr/compat.py
- zarr/errors.py
- zarr/meta.py
- zarr/meta_v1.py
- zarr/storage.py
- zarr/tests/test_core.py
- zarr/tests/test_filters.py
- zarr/tests/test_hierarchy.py
- zarr/tests/test_meta.py
- zarr/tests/test_storage.py
- zarr/util.py
This PR re-instates coverage for all Python versions (#169). Also a mechanism is added for excluding lines from coverage analysis based on which Python major version.
> Coverage and Python versions

- zarr/core.py
- zarr/storage.py
- zarr/tests/test_core.py
This PR has modifications to fix incorrect counting of number of chunks initialized, resolves #97.
> Count nchunks_initialized properly

- docs/tutorial.rst
- zarr/creation.py
- zarr/meta.py
- zarr/tests/test_meta.py
This PR adds base64 encoding of bytes fill values, which is required to store array metadata as JSON. Resolves #165.
> Test and fix for bytes fill value bug

- docs/api/storage.rst
- tox.ini
- zarr/__init__.py
- zarr/storage.py
- zarr/tests/test_core.py
- zarr/tests/test_hierarchy.py
- zarr/tests/test_storage.py
This PR adds a new store class which stores chunk files in a nested directory structure rather than all chunk files for a given array in the same directory. Resolves #155.
> Add nested directory store

- notebooks/repr_tree.ipynb
- zarr/hierarchy.py
- zarr/tests/test_hierarchy.py
- zarr/util.py
This PR modifies the tree HTML representation to use jstree. Also adds a "level" parameter to tree() to allow limiting depth to which tree is printed.
> Use jstree

- .gitignore
- data/donotdelete
- docs/api/convenience.rst
- docs/api/storage.rst
- docs/conf.py
- docs/index.rst
- docs/release.rst
- docs/spec/v2.rst
- docs/tutorial.rst
- requirements_dev.txt
- requirements_rtfd.txt
- zarr/convenience.py
- zarr/core.py
- zarr/creation.py
- zarr/hierarchy.py
- zarr/storage.py
- zarr/tests/test_convenience.py
- zarr/tests/test_core.py
- zarr/tests/test_creation.py
- zarr/tests/test_hierarchy.py
- zarr/tests/test_meta.py
- zarr/tests/test_storage.py
- zarr/tests/test_util.py
- zarr/util.py
Main TODOs...
Also need to add release notes (resolves #159) for enhancements:
...and other work...
> WIP documentation for 2.2 release

- docs/api/storage.rst
- docs/release.rst
- docs/tutorial.rst
- notebooks/store_benchmark.ipynb
- tox.ini
- zarr/__init__.py
- zarr/core.py
- zarr/hierarchy.py
- zarr/meta.py
- zarr/storage.py
- zarr/tests/test_core.py
- zarr/tests/test_hierarchy.py
- zarr/tests/test_storage.py
- zarr/tests/test_util.py
- zarr/util.py
This PR adds a new ``LMDBStore`` class.
Also some other improvements to the storage module, including making ZipStore thread safe (resolves #194).
> LMDB store

- zarr/storage.py
- zarr/tests/test_storage.py
Lays the ground work for resolving issue ( https://github.com/alimanfoo/zarr/issues/191 ). Namely adds a `rename` function on some `Store`s like `Dict` and `DirectoryStore`. This can later be used by `move`. Since this requires a deletion step it won't work for things like `ZipStore`.
> Add Store rename method

- docs/release.rst
- docs/spec/v2.rst
- docs/tutorial.rst
- zarr/storage.py
- zarr/tests/test_hierarchy.py
- zarr/tests/test_storage.py
This PR changes the initialisation behaviour for arrays and groups such that the .zattrs key is not written with an empty dict. Now the .zattrs key will be absent until the first time an attribute is written. Includes a clarification to the spec that .zattrs is optional. Resolves #121.
> Lazily create .zattrs

- docs/tutorial.rst
From #199, cProfile/profile only showed me fast context switching, not the cause of it (blosc). Think it would be good to a note warning about the possibility.
> Add note about manual parallelism with blosc

- docs/api/core.rst
- docs/release.rst
- zarr/attrs.py
- zarr/core.py
- zarr/meta.py
- zarr/tests/test_core.py
- zarr/tests/test_sync.py
Fixes https://github.com/alimanfoo/zarr/issues/98
Provides a method for Zarr Array's to compute their checksum. Uses the `sha1` checksum by default thanks to its speed and low probability of collisions. Though the user can change the checksum to any supported by their version of `openssl` (per `hashlib` docs) should they desire to. The hashing is done on the data in the chunk store (so encoded) and the metadata (shape, dtype, order, filtering, and attributes).
> Method to find Zarr Array checksum

- zarr/tests/test_core.py
Fixes https://github.com/alimanfoo/zarr/issues/178
Make sure that we are able to store 0-length structured arrays in Zarr.
> Test 0-length structured array

- appveyor.yml
- docs/release.rst
- docs/tutorial.rst
- notebooks/object_arrays.ipynb
- pytest.ini
- requirements.txt
- requirements_dev.txt
- setup.py
- tox.ini
- zarr/core.py
- zarr/creation.py
- zarr/meta.py
- zarr/storage.py
- zarr/tests/test_core.py
- zarr/tests/test_creation.py
- zarr/tests/test_hierarchy.py
- zarr/tests/test_sync.py
This PR is a minimal attempt to improve safety and usability for object arrays, to resolve #208.
Object arrays without a filter that encodes object data are inherently unsafe and can lead to nasty errors or segfaults. Therefore, we want to make it very hard (if not impossible) for the user to create an object array without the necessary encoding.
This PR attempts to achieve this while maintaining backwards compatibility with previously-created data. I.e., any data previously created with an object dtype and with an appropriate filter such as ``numcodecs.MsgPack`` will continue to work with the new code, and no changes to the storage specification are required.
This is achieved by introducing a new ``object_codec`` argument to all array creation functions. If the array dtype is ``object``, …
> Object encoding

- docs/api/core.rst
- zarr/core.py
Follow-up to PR ( https://github.com/alimanfoo/zarr/pull/203 ).
This implements an equivalent method to `hashlib`'s `digest` method for Zarr Arrays. Makes sure to document it as well.
> Add a `digest` method for Zarr Arrays

- docs/release.rst
- docs/spec/v2.rst
- docs/tutorial.rst
- requirements_dev.txt
- setup.py
- zarr/core.py
- zarr/meta.py
- zarr/storage.py
- zarr/tests/test_core.py
- zarr/tests/test_filters.py
- zarr/util.py
Numcodecs 0.5.0 adds some new codecs for variable length text (unicode) strings ([VLenUTF8](http://numcodecs.readthedocs.io/en/stable/vlen.html#numcodecs.vlen.VLenUTF8)), variable length byte strings ([VLenBytes](http://numcodecs.readthedocs.io/en/stable/vlen.html#numcodecs.vlen.VLenBytes)) and variable length arrays of primitive numpy types ([VLenArray](http://numcodecs.readthedocs.io/en/stable/vlen.html#numcodecs.vlen.VLenArray)). These codecs all use the [Parquet format byte array encoding](https://github.com/apache/parquet-format/blob/master/Encodings.md#plain-plain--0). The codecs have [good performance and encoded data size](https://github.com/alimanfoo/numcodecs/blob/master/notebooks/benchmark_vlen.ipynb) and provide a platform-independent encoding for these common cases.
This PR …
> Object dtype convenience API; datetime64/timedelta64 support

- docs/api/convenience.rst
- docs/release.rst
- docs/tutorial.rst
- requirements_dev.txt
- zarr/__init__.py
- zarr/convenience.py
- zarr/errors.py
- zarr/tests/test_convenience.py
This PR adds some convenience functions for copying data between zarr groups or stores, or for copying data between h5py and zarr. The following new functions are proposed:
* ``zarr.copy(source, dest, ...)`` - copy the ``source`` h5py or zarr group or array into the ``dest`` h5py or zarr group.
* ``zarr.copy_all(source, dest, ...)`` - copy all children of the ``source`` h5py or zarr group into the ``dest`` h5py or zarr group.
* ``zarr.copy_store(source, dest, ...)`` - copy all (key, value) pairs from the ``source`` store to the ``dest`` store.
Further details and examples are given in the function docstrings.
Resolves #87, resolves #113, resolves #137.
TODO:
POSTPONED:
* consider Group.copy() method?
* consider ``delete=True/False`` option analogous to rsync?
> Copy functions

- docs/api/storage.rst
- docs/release.rst
- docs/tutorial.rst
- zarr/__init__.py
- zarr/compat.py
- zarr/storage.py
- zarr/tests/test_core.py
- zarr/tests/test_hierarchy.py
- zarr/tests/test_storage.py
- zarr/tests/util.py
- zarr/util.py
This PR adds a new ``zarr.storage.LRUStoreCache`` class which can be used as a cache layer for slow stores (e.g., stores accessed via network).
Also in developing this PR some inconsistencies in the way that ``zarr.storage.getsize()`` was implemented for different store types came to light and have been fixed.
TODO:
> LRU store cache

- docs/api.rst
- docs/api/attrs.rst
- docs/release.rst
- zarr/attrs.py
- zarr/core.py
- zarr/creation.py
- zarr/hierarchy.py
- zarr/tests/test_attrs.py
- zarr/tests/test_core.py
- zarr/tests/test_sync.py
- zarr/tests/util.py
This PR adds support for caching user attributes, enabled by default. Resolves #218.
TODO:
> Cache attributes

- docs/release.rst
- release.txt
- requirements.txt
- requirements_dev.txt
- zarr/attrs.py
- zarr/convenience.py
- zarr/creation.py
- zarr/errors.py
- zarr/hierarchy.py
- zarr/indexing.py
- zarr/meta.py
- zarr/tests/test_attrs.py
- zarr/tests/test_convenience.py
- zarr/tests/test_core.py
- zarr/tests/test_creation.py
- zarr/tests/test_filters.py
- zarr/tests/test_hierarchy.py
- zarr/tests/test_indexing.py
- zarr/tests/test_info.py
- zarr/tests/test_meta.py
- zarr/tests/test_storage.py
- zarr/tests/test_sync.py
- zarr/tests/test_util.py
This PR completes the migration to pytest and removes all use of nose. Resolves #189.
(N.B., nose is still retained in requirements_dev.txt because it is needed by numcodecs.)
> Complete pytest migration

- .gitignore
- docs/index.rst
- docs/tutorial.rst
- requirements_dev.txt
- setup.py
- windows_conda_dev.txt
Bumps the `numcodecs` requirement to `0.5.3` as this version uses `pytest` only (without `nose`). As `zarr` uses some testing utilities from `numcodecs`, the version bump is needed to remove the indirect dependency on `nose`. With this requirement change, drop usage of `nose` throughout `zarr`. Also update the testing instructions to use `pytest` (instead of `nose`).
> Require numcodecs 0.5.3 and drop nose

- appveyor.yml
- docs/release.rst
- requirements_dev.txt
- tox.ini
- zarr/meta.py
- zarr/tests/test_core.py
- zarr/tests/test_meta.py
- zarr/tests/test_util.py
- zarr/util.py
This PR adds testing with numpy 1.14 and deals with some compatibility issues around fill values for structured arrays. Resolves #222, resolves #238.
TODO:
``pytest -v --doctest-modules zarr``)
``pytest -v zarr``)
> Work around numpy 1.14 structured array changes

- tox.ini
Same as PR ( https://github.com/zarr-developers/numcodecs/pull/124 ) for Zarr.
This allows users to run `flake8 zarr` and pick up the desired configuration by default.
TODO:
> Configure flake8's line length as 100

- zarr/convenience.py
- zarr/tests/test_convenience.py
Fixes #336 by adding **kwargs to `open_consolidated`
TODO:
> pass kwargs to consolidate

- zarr/storage.py
In the ideal case, this cleanup step never happens on CI as the file got moved into place and so no longer exists at the old location. Given this, we ignore coverage on this line.
TODO:
> Skip coverage of temp file cleanup

- docs/release.rst
- requirements.txt
- requirements_dev.txt
- setup.py
- zarr/storage.py
When the chunk file is first removed before the new version
is moved into place, racing reads may encounter a missing chunk.
Using rename() or replace() without remove() avoids the issue
on Posix-Systems as the methods are atomic. The fallback of
remove() -> rename() is included for Windows pre Python 3.3.
Fixes #263
TODO:
> avoid race condition during chunk write

- docs/release.rst
- zarr/storage.py
- zarr/tests/test_storage.py
Partially addresses issue ( https://github.com/zarr-developers/zarr/issues/348 ) and issue ( https://github.com/zarr-developers/zarr/issues/349 ).
As the spec notes stores values must be an "arbitrary sequence of bytes", this change ensures that values in `DictStore` meet that constraint. Of course nesting of `DictStore`s are still allowed per usual. However these really just map to a variety of keys, which is fine.
Since the `DictStore`'s values are just `bytes`, there shouldn't be any cases where the size of these values cannot be determined. So drop handling for unknown sizes in `buffer_size`. Also drop the associated test for `DictStore` as this cannot occur.
Add a test case for `getsize` with a non-conforming `dict`-based store where sizes are unknown to make sure that case is tested …
> Ensure `DictStore` contains only `bytes`

- docs/release.rst
- zarr/meta.py
- zarr/tests/test_core.py
- zarr/tests/test_creation.py
- zarr/tests/test_meta.py
Related to issue ( https://github.com/zarr-developers/zarr/issues/342 )
The `NaT` type is represented as `-0`. As a result, casting to an unsigned integral fails and throws an error. However casting to a signed integral type does not have this problem and proceeds without issues.
TODO:
> Cast datetime and timedelta to signed 64-bit int

- docs/release.rst
- zarr/core.py
Follow-up to PR ( https://github.com/zarr-developers/zarr/pull/352 )
Simplifies the process of constructing an `ndarray` to view the chunk data when writing the result to a destination. Also removes the last usage of `np.frombuffer` from library code (still used in examples, tests, and docs).
TODO:
> Use `ensure_ndarray` to view chunk as an array

- docs/release.rst
- zarr/core.py
Follow-up to PR ( https://github.com/zarr-developers/zarr/pull/352 ) and PR ( https://github.com/zarr-developers/zarr/pull/268 )
This workaround was added because `get_codec` was modifying its argument. However as of Numcodecs 0.6.0, `get_codec` does not modify its argument as it takes a copy and modifies the copy instead. ( https://github.com/zarr-developers/numcodecs/pull/79 ) Given as we now require Numcodecs 0.6.0, this workaround is no longer needed. Hence we drop it.
TODO:
> Drop temporary workaround for `get_codec`

- zarr/core.py
As using slicing syntax on `list`s makes a copy, use `reversed` instead to avoid the copy and just create a generator for iterating through the `list` backwards.
TODO:
> Use `reversed` to iterate through `list` backwards

- docs/release.rst
- zarr/core.py
- zarr/indexing.py
NumPy 1.15.0 deprecates the use of sequences in `ndarray` selection for sequences other than `tuple`s. We have a few cases where we are using `list`s instead as they are mutable. Thus are easier to build up and change. However passing `list`s into `ndarray` selection will cause this `FutureWarning` to be emitted (and will eventually result in an error).
To fix this simply, just convert these `list`s to `tuple`s after we are done changing their contents, but before we use them with `ndarray`s. This works just as well on older versions of NumPy. Avoids the `FutureWarning` in NumPy 1.15.0+. Not to mention this will continue to work on future versions of NumPy, which may change this warning into an error.
xref: https://github.com/numpy/numpy/pull/9686
TODO:
> Always use `tuple`s for multidimensional indexing

- zarr/tests/test_storage.py
Adds a test for the `popitem` method of `MutableMapping`'s as well. Typically this is not used, but it does get used in the default `clear` method. Given this method doesn't guarantee an order, use a store with a single-key value pair to simplify the test logic. Also test the case of an empty store to make sure it errors out properly. Override the `popitem` method appropriate for stores that do not handle removal properly.
TODO:
> Test the `popitem` method of `MutableMapping`s too

- zarr/tests/test_storage.py
Adds another case to `test_pop` for stores generally, which merely tests if `pop` can handle the default argument correctly when no key can be found.
TODO:
> Test `pop` with default argument

- docs/release.rst
- zarr/compat.py
- zarr/core.py
- zarr/storage.py
- zarr/tests/test_core.py
Closes #398.
Thanks to @alimanfoo for giving me the formula for unit tests! The only tricky thing is the zero-d case, which I've mirrored numpy's behaviour for.
TODO:
> Chunkwise iteration over arrays.

- zarr/storage.py
Previously there were some [test failures on Python 2]( https://travis-ci.org/zarr-developers/zarr/jobs/473753393#L2148 ) and referenced in [this comment (and later discussion)]( https://github.com/zarr-developers/zarr/pull/372#issuecomment-450667294 ). Turns out on Python 2 a `bson.Binary` instance is returned, which subclasses `bytes`, as [explained in the docs]( http://api.mongodb.com/python/current/python3.html#id3 ). So the coercion to `bytes` is only needed on Python 2 to convert `bson.Binary` to `bytes`. As Python 3 already returns a `bytes` instance, there is nothing we need to do there. Thus we restrict the `binary_type` call to Python 2. Should avoid a copy on Python 3.
xref: https://github.com/zarr-developers/zarr/pull/372
TODO:
> Use binary_type in MongoDBStore.__getitem__ for Python 2 only

- docs/release.rst
- zarr/core.py
- zarr/tests/test_core.py
This removes the special case copying of chunks in commit ( https://github.com/zarr-developers/zarr/commit/3c00d52356fb59968d05b8764b05a66c50457850 ). Instead this checks to see if a `dict` instance is being used to back chunk storage. If it is, this coerces the chunk data to `bytes` (if it is not already `bytes`). This avoids a copy for well-defined backends that already protect their data against unwanted tampering. Also continues to avoid copies when compressors and/or filters already return the data as `bytes`. However this will copy in any case where a non-`bytes` object (e.g. an `ndarray`) is placed in the chunk store (e.g. no filters/compressors are used or some specific filter is used at the end). This behavior for `dict`-based chunk stores is analogous to what `DictStore` does …
> Special case chunk encoding for `dict` chunk store

- zarr/tests/test_core.py
Pulled from PR ( https://github.com/zarr-developers/zarr/pull/309 ) and added to `TestArray` so that it can be applied to multiple storage classes. Credits to @funkey for adding these tests.
TODO:
> Test Array storing different compressors, endian and attributes

- zarr/tests/test_core.py
Adds a test for all stores to ensure that all keys are text.
TODO:
> Test store keys are all text

- zarr/tests/test_core.py
The N5 spec does not currently list support for datetime, timedelta, and complex typed data. So customize `test_dtype` for `N5Store` to avoid these and instead focus on the types `N5Store` does support. Should fix the [CI failure on `master`]( https://travis-ci.org/zarr-developers/zarr/builds/498601006 ) accidentally introduced by PR ( https://github.com/zarr-developers/zarr/pull/363 ).
TODO:
> Skip datetime, timedelta, and complex with N5Store

- docs/release.rst
- zarr/tests/test_core.py
- zarr/tests/test_hierarchy.py
- zarr/tests/test_storage.py
Fixes https://github.com/zarr-developers/zarr/issues/419
Updates the tests to make `azure-storage-blob` an optional testing requirement.
TODO:
> Make azure-storage-blob optional for testing

- docs/release.rst
- zarr/convenience.py
- zarr/meta.py
- zarr/n5.py
- zarr/storage.py
- zarr/tests/test_core.py
Cleans up some Python 2/3 code for handling JSON parsing by simply always coercing metadata to text regardless of Python version.
xref: https://github.com/zarr-developers/zarr/pull/372
xref: https://github.com/zarr-developers/zarr/pull/401
TODO:
> Coerce data to text for JSON parsing

- docs/release.rst
- zarr/attrs.py
- zarr/convenience.py
- zarr/meta.py
- zarr/n5.py
- zarr/storage.py
- zarr/util.py
This refactors out the JSON utility functions created in PR ( https://github.com/zarr-developers/zarr/pull/429 ) and moves them from `zarr.meta` to `zarr.util`. It also employs them in other places where the `json` module was being used directly. Should make it easier to leverage the buffer protocol as part of the loading process. Finally includes the `encode` step within `json_dumps`, which eliminates the need for it to be done every time `json_dumps` is called, which simplifies the code a bit.
TODO:
> Collect JSON utility functions

- docs/release.rst
- zarr/attrs.py
- zarr/compat.py
- zarr/convenience.py
- zarr/hierarchy.py
- zarr/storage.py
- zarr/tests/util.py
When importing abstract base classes from `collections` (e.g. `MutableMapping`), a `DeprecationWarning` was issued stating that these would no longer be available in Python 3.8 and that we should use `collections.abc`s for this purpose instead. Here we handle importing `MutableMapping` in the `compat` module and have other modules import it from there. This allows us to have the right Python 2/3 behavior while avoiding these `DeprecationWarning`s.
TODO:
> Fix `collections`'s `DeprecationWarning`s

- zarr/storage.py
Fixes the issue described in [this SO question]( https://stackoverflow.com/q/56904331/3877089 ).
This call to `decode` has been made unnecessary thanks to the `json_loads` utility function used here. Unfortunately this code was left over when that was added in. Drop this now unneeded code so as to better handle `bytes`-like data.
cc @martindurant
TODO:
> Drop `decode` from `ConsolidatedMetadataStore`

- README.rst
- docs/conf.py
- docs/contributing.rst
- docs/index.rst
- docs/release.rst
- docs/talks/scipy2019/submission.rst
- docs/tutorial.rst
- setup.py
> Fix URLs to point to zarr-python

- docs/api/storage.rst
- docs/release.rst
- docs/tutorial.rst
- zarr/__init__.py
- zarr/hierarchy.py
- zarr/storage.py
- zarr/tests/test_convenience.py
- zarr/tests/test_hierarchy.py
- zarr/tests/test_storage.py
This PR renames `DictStore` to `MemoryStore` while providing an alias for `DictStore` that raises a depreciation warning for backwards compatibility. Closes #356. 
TODO:
> Rename DictStore to MemoryStore

- docs/release.rst
- docs/tutorial.rst
- zarr/creation.py
- zarr/tests/test_core.py
- zarr/tests/test_sync.py
- zarr/tests/test_util.py
- zarr/util.py
This PR updates `normalize_chunks` to apply the same chunking to all dimensions when `chunks` is specified as an integer. Closes #364.
TODO:
> Use uniform chunking when specifying chunks as an integer

- docs/api/codecs.rst
Add missing closing parenthesis in code snippet.
TODO:
> DOC: fix typo in code snippet

- docs/release.rst
- zarr/n5.py
n5-blosc expects the original blosc parameters including 'blocksize'
TODO:
> undo parameter renaming for compatibility with n5-blosc

- docs/tutorial.rst
Adds a `>` character to the end of the URL so it's rendered properly
> Fix N5 link in tutorial

- docs/release.rst
- zarr/hierarchy.py
- zarr/tests/test_hierarchy.py
This PR adds a `recurse` parameter to the `Group.array_keys` and `Group.arrays` methods. To maintain backwards compatibility, `recurse` is `False` by default. Closes #260
TODO:
> Add recurse keyword to array_keys and arrays

- docs/tutorial.rst
This PR updates the "Configuring Blosc" section of the tutorial to import `blosc` from `numcodecs` instead of `zarr`. Closes #292
TODO:
> Import blosc from numcodecs in tutorial

- docs/release.rst
- docs/tutorial.rst
- requirements_dev_minimal.txt
- setup.py
- zarr/util.py
As Numcodecs is able to convert `bytes`-like data to text, use its functionality in Zarr and drop equivalent functions in Zarr.
TODO:
> Use `ensure_text` from Numcodecs

- docs/release.rst
- zarr/core.py
- zarr/indexing.py
- zarr/util.py
Instead of using `numpy.ceil`, use `math.ceil` on scalars. After all this is `math.ceil`'s primary use case (unlike `numpy.ceil`).
TODO:
> Use `math.ceil` for scalars

- docs/release.rst
- zarr/tests/test_convenience.py
- zarr/tests/test_core.py
- zarr/tests/test_hierarchy.py
- zarr/tests/test_storage.py
- zarr/tests/util.py
This PR replaces (almost all) occurrences of `try`/`except` blocks to determine if a library is available with [`pytest.importorskip`](http://doc.pytest.org/en/latest/skipping.html#skipping-on-a-missing-import-dependency). I wasn't able to replace this `LZMA` import
https://github.com/zarr-developers/zarr-python/blob/55ae9eb95d2c7c59582fed02f1dba88298f10fda/zarr/tests/test_core.py#L1944-L1947
because it's used in other conditional statements in `test_core.py`. 
Also added a `skip_test_env_var` utility function to `zarr/tests/util.py` to replace some of the boilerplate code related to skipping tests based on environment variables (e.g. `ZARR_TEST_ABS`)
Closes #229 
TODO:
> Use pytest.importorskip in tests

- docs/release.rst
- zarr/storage.py
To make it easier for users to implement their own methods for reading and writing from disk ( like memory-mapping https://github.com/zarr-developers/zarr-python/pull/377 ), refactor out `_tofile` and `_fromfile` methods that are called to handle the reading and writing of the value. Should avoid duplicating a lot of other logic when trying to extend `DirectoryStore`s for these cases.
TODO:
> Refactor out `_tofile`/`_fromfile` from `DirectoryStore`

- docs/tutorial.rst
Small update to fix the azure-storage-blob link being rendered as a block quote in the tutorial.
On `master`:
With changes in this PR:
TODO:
> Fix azure link rendering in tutorial

- docs/release.rst
- zarr/core.py
As we can coerce any object that is array-like to an `ndarray`, there should be no need for these explicit `ndarray` checks. So eliminate them by using `ensure_ndarray` to get an `ndarray` object instead.
TODO:
> Use `ensure_ndarray` in a few more places

- docs/release.rst
- zarr/core.py
Previously we were calling `ascontiguousarray` and `asfortranarray` based on whether we wanted a C or Fortran ordered array. However we can simplify this by using `astype` to capture both cases. Additionally those functions ensure the array is at least 1-D, but that doesn't seem to matter for this use case since the scalar case is handled in a different branch. So we leave that part out.
TODO:
> Ensure contiguous data using `astype`

- .github/PULL_REQUEST_TEMPLATE.md
- .travis.yml
- docs/conf.py
- docs/release.rst
- docs/tutorial.rst
> Add documentation build to CI

- docs/api/hierarchy.rst
- docs/release.rst
- docs/tutorial.rst
- zarr/hierarchy.py
- zarr/tests/test_hierarchy.py
For compatibility with other group-like things (e.g. `h5py.File`),
`Groups` now have enter/exit methods for use as a context manager.
If the underlying store has a `close` method, that will be called on
exit; otherwise this does nothing.
See issue #509.
It would have been nice to extend the context manager stuff to a Store superclass (an ABC which also inherits from MutableMapping), but as described in the issue, that makes guarantees that existing code may already break (e.g. using a raw `dict` as a store).
TODO:
> Group as context manager

- docs/release.rst
- zarr/storage.py
- zarr/tests/test_core.py
- zarr/tests/test_hierarchy.py
- zarr/tests/test_storage.py
Fixes '/' prepend bug in `ABSStore`, issue: https://github.com/zarr-developers/zarr-python/issues/525
TODO:
> Fixed '/' prepend bug in ABSStore

- docs/release.rst
- zarr/creation.py
- zarr/storage.py
- zarr/tests/test_storage.py
By default zipfile.writestr write files with permissions 600 when called with a filename.
These permissions are too restrictive for ZipStore to be shared with other users. In order to
fix the problem, I pass zipfile.writestr a zipfile.ZipInfo object in which I have set more open
permissions. Fixes #505 
TODO:
> Fixing permissions for files inside a ZipStore

- docs/release.rst
Includes some other Changelog entries for 2.4.
xref: https://github.com/zarr-developers/zarr-python/issues/529
cc @jrbourbeau
TODO:
> Add 2.4 Changelog

- .travis.yml
- requirements_dev_optional.txt
Let's see if this works...
TODO:
> Attempt to fix coveralls

- zarr/indexing.py
- zarr/tests/test_meta.py
- zarr/util.py
These were uncovered lines in [this Coveralls report]( https://coveralls.io/builds/29088639 ). As we already dropped Python 2 in PR ( https://github.com/zarr-developers/zarr-python/pull/470 ), go ahead and drop this no longer need Python 2 code.
Also smooth over differences in `unravel_index`'s signature across NumPy versions.
> Maximize coverage

- docs/release.rst
- setup.py
- zarr/tests/test_util.py
- zarr/util.py
Resolves https://github.com/zarr-developers/zarr-python/issues/537
Adds a custom error message when failing to import `ipytree` in jupyter notebooks along with instructions on how to get it (`pip install zarr[jupyter]`). Also added `jupyter` itself to `extras_require["jupyter"]` seeing as `jupyter` isn't a requirement in-and-of-itself of `zarr`. Let me know if anything doesn't make sense, happy to change.
TODO:
> Add better ipytree error handling in jupyter notebooks

- docs/release.rst
- zarr/tests/test_core.py
- zarr/tests/test_hierarchy.py
- zarr/tests/test_storage.py
This is especially troublesome on 32-bit systems with LMDB, as opening
an LMDB store maps 2\**28 blocks, and letting the gc clean them up can
cause excess memory pressure. Eventually, this results in LMDB tests
failing to open a store because it can't find a 2**28 block to mmap.
* [N/A] Add docstrings and API docs for any new/modified user-facing classes and functions
* [N/A] New/modified features documented in docs/tutorial.rst
* [N/A] Docs build locally (e.g., run ``tox -e docs``)
> Explicitly close stores during tests.

- zarr/convenience.py
- zarr/tests/test_convenience.py
This simple PR enables using `chunk_store` argument in `open_consolidated()`. It also fixes testing in pydata/xarray/pull/3804. No change to documentation required.
> Allow chunk_store argument in open_consolidated()

- pytest.ini
This is useful when inspecting CI builds to have an idea of what takes
the longest time – especially since CI may have some slow resources
(disk, network). And may help to speedup test suite, which is always
good for fast development.
> Always display the 10 slowest test when running pytest.

- docs/index.rst
This PR changes the very first sentence of our documentation from
> Zarr is a Python package providing an implementation of chunked, compressed, N-dimensional arrays.
to
> Zarr is format for the storage of chunked, compressed, N-dimensional arrays. These documents describe the Zarr format and its Python implementation.
I think it's important at this stage to make this clarification.
Should we also consider linking to the implementations in other languages?
> modify top level description of zarr

- docs/release.rst
- docs/tutorial.rst
- zarr/hierarchy.py
- zarr/storage.py
- zarr/util.py
As discussed during the last community call, a non-HDF5 user recently explained their confusion to me over the term "dataset" in `create_dataset`. @alimanfoo explained that this was intended for compatibility with h5py. I've added that explanation (copied from the tutorial) to the individual method blocks, and updated the few other non-HDF5 uses of "Dataset" that  I could find. The remaining uses all appear to be intentional:
```
(base) ~/opt/zarr $git grep dataset | grep -v create_dataset | grep -v require_dataset
docs/release.rst:  metadata keys within a dataset hierarchy under a single key, and
docs/talks/scipy2019/submission.rst:of datasets. Key design goals include: a simple protocol and format
docs/talks/scipy2019/submission.rst:satellite observation datasets to Zarr [6_], and have …
```
> docs: replace usages of "Dataset" with "Array"

- docs/index.rst
Folder in cloned repo is incorrect.
> Correct typo in folder location

- docs/conf.py
- docs/index.rst
- docs/spec/v1.rst
- docs/spec/v2.rst
Numpy docs have move, update links to newer version.
> Spec v2 update link to stable numpy docs

- zarr/storage.py
Zarr is only Python 3.5+ so this check is not necessary anymore.
> Remove redundant Conditional imports.

- docs/api/storage.rst
- requirements_dev_optional.txt
- zarr/creation.py
- zarr/hierarchy.py
- zarr/storage.py
- zarr/tests/test_storage.py
- zarr/tests/util.py
Fixes #540 
Ref https://github.com/zarr-developers/zarr-python/pull/373#issuecomment-592722584 (@rabernat )
Introduces a short Store implementation for generic fsspec url+options. Allows both lowercasing of keys and choice between '.' and '/'-based ("nested") keys.
For testing, have hijacked the TestNestedDirectoryStore tests just as an example - this is not how things will remain.
> Add FSStore

- zarr/creation.py
without the stacklevel the warning point to the frame where the warnign
is issued. In this case we likely want to be at least two callers up as
we want to see the caller of `create` or `open_array`.
> Set stacklevel on warning for proper issue pinpointing.

- docs/release.rst
- zarr/storage.py
- zarr/tests/test_storage.py
usage of os.walk for tree (os.scandir for folders) is faster than
listdir as it avoids many stats call.
This Should make the DirectoryStore faster.
See #562 
TODO:
> Attempt to use os.walk to speedup reading from Directory Store

- requirements_dev_minimal.txt
- requirements_dev_numpy.txt
cleanup py27 requirement no longer necessary.
> Remove requirements for Python 2.7

- zarr/storage.py
Numpydoc expect space on each side of the colon, on it may mis-parse
what this actually means.
> Numpydoc consistency.

- .travis.yml
limiting only to master means that forks do not run tests except on
master.
This was presumably done originally as development of feature branches
and stable were on the same repo, as everyone is going through PRs this
seem unnecesasry now.
> Reactivate travis on all branches.

- pytest.ini
- zarr/storage.py
- zarr/tests/test_storage.py
Adding the versing number make it slightly easier on consumers to update
to the new naming as they will get a sens of compatibility.
Also update pytest to fail is any deprecation warning are not marked in
the test suite, and catch them in more places.
In particular we realise that many more places trigger the warnings in
create_store so we catch the warning there, but also that
`pickle.load()` can trigger it.
TODO:
> Update Deprecating Warning with version number.

- docs/release.rst
- zarr/convenience.py
- zarr/core.py
- zarr/creation.py
- zarr/errors.py
- zarr/hierarchy.py
- zarr/storage.py
I believe this has several advantage:
1) reading the code it is obvious we are directly raising instead of
doing more stuff.
2) in traceback the last frame will be correct, so it's easier to find
where the error occurs.
3) All of these are now subclasses which can be caught independently
by libraries while still being subclass of ValueError, so backward
compatible. Can be caught without catching other ValueErrors.
4) the name of the class is descriptive
I'm not too sure about some naming. Is ContainsXxxxError sufficient to
understand that it contain Xxxxx but Xxxx was not expected ?
TODO:
I'm not too sure if I should remove the err_ function, as they may be public APIs.
Thus the coverage will decrease; 
if you are +1 on this approach I'll do the few remaining and update the docs.
> Use Error subclasses instead of functions.

- .travis.yml
- docs/release.rst
- mypy.ini
- pytest.ini
- requirements_dev_optional.txt
- zarr/codecs.py
- zarr/indexing.py
- zarr/meta.py
- zarr/storage.py
- zarr/util.py
Mostly make it a bit clearer what is allowed/expected where.
In particular many of the decode fucntions allow already decoded
objects.
TODO:
> Add some typings informations and typecheck

- docs/release.rst
- zarr/errors.py
- zarr/indexing.py
- zarr/storage.py
Convert also one more err_ function into a proper exception that derives
from ValueError.
TODO:
> Remove error utils function (not used anymore)

- zarr/convenience.py
In case where 'shape' is passed as argument, this will avoid calling
"contains_array" which does store queries, as well as avoid testign if
the array contains a group as anyway this is what we were going to do in
the else case.
This does change behavior in edge case:
- if shape is passed and the key is a group, we'll try to open as array
instead of groups.
- if contains_array or contains_group would have raise we might skip
over those checks.
Though both of the above case should not be found in user code and
are bugs AFAICT, and would just fail differently.
--- 
Let's see if this triggers any test failure. 
TODO:
> Reduce number of store queries in open(mode='a').

- .github/workflows/releases.yml
- docs/contributing.rst
- pyproject.toml
Setup a github workflow based on numcodec to build sdist and wheel. Adapted from numcodec. 
I have to check what ciwheel do, as zarr wheels are likely universal and dont' need to be per-platform
TODO:
> Use github workflow to build sdist/wheel and upload.

- docs/release.rst
Misc addition to release notes.
I've also tagged all the PRs merged since 2.4 with the 2.5 milestone.
TODO:
> Misc release notes

- .travis.yml
- appveyor.yml
- docs/release.rst
- setup.py
- tox.ini
Remove references to 3.5 from CI and test configuration, setup.py, and tox, as per #602
Note that the ipython notebooks seem to have been run against 3.5; we should consider running them against 3.8 and check them in again to future-proof us a little longer.
Strictly, 3.5 only becomes EOL 2020-09-13, so take the weekend ;) As stated in https://github.com/zarr-developers/governance/issues/11 it may be worth putting out a final patch version supporting 3.5 before this goes in.
> End support for EOL python 3.5

- requirements_dev_numpy.txt
The comment in the file suggest that the numpy version should be the
latest one, it is not.
This would help to make sure that there is no regression in numpy,
and/or that the test suite would catch numpy deprecated functionality.
> Bump numpy version in requirements_dev.

- zarr/tests/test_hierarchy.py
- zarr/tests/util.py
That should remove all the Python 3.5 codepath, at leat all the explicit
ones.
TODO:
> Remove some extra Python 3.5 conditionals.

- zarr/tests/test_core.py
this is part of the goal to go back to 100% coverage.
> Remove uncovered lines in test.

- docs/tutorial.rst
- zarr/convenience.py
- zarr/core.py
- zarr/storage.py
- zarr/tests/test_storage.py
> Fsspec writing

- codecov.yml
Codecov report are a bit noisy, this mute them a bit y removing the
large graph and postigin only if there is a coverage change.
> Mute a bit codecov report.

- .gitattributes
Add .gitattributes so that can be correctly labelled as python project
Before
```
85.21%  Jupyter Notebook
14.53%  Python
0.23%   Roff
0.04%   Batchfile
```
After
```
98.19%  Python
1.55%   Roff
0.26%   Batchfile
```
TODO:
> add .gitattributes to fix repo language

- zarr/creation.py
- zarr/hierarchy.py
Move it to the only two places where it is used;
technically this is a change of API, but the function
`normalize_store_arg` is only used internally.
This make it a bit easier to follow what might happens when it is
called; in particular this will let us be sure that it always returns a
Store as as long as it is passed is a Store or a string, whicl before it
could have returned anything depending on the value of default.
> Remove unused `default` keyword that is only used internally

- zarr/storage.py
- zarr/tests/test_storage.py
Fixes directory caching issues that can occur in `zarr/tests/test_storage.py::TestFSStore::test_s3_complex`. Also removed code that was used to previously fix the issue.
fixes issue #653 
TODO:
> fixes s3 fixture for s3 test complex

- zarr/n5.py
- zarr/tests/test_creation.py
In the N5 spec, https://github.com/saalfeldlab/n5#file-system-specification
point 3, the `{"n5": "$version"}` metadata is only expected at the root level.
Datasets missing the metadata on inner groups fail to load:
```
In [43]: list(zarr.hierarchy.Group(store=zarr.n5.N5Store("ex.n5")).groups())
...
ValueError: group not found at path 'setup0'
```
This changes the group parsing logic to not fail if the metadata is
missing. Suggestions welcome on how to detect the top group/array in
order to special case the parsing.
see https://github.com/tischi/i2k-2020-s3-zarr-workshop/issues/1#issuecomment-726224950  for the original report
TODO:
> n5: prevent failure on missing group metadata

- zarr/convenience.py
- zarr/core.py
- zarr/storage.py
- zarr/tests/test_storage.py
> Fixes #649

- zarr/n5.py
Follow-up to PR ( https://github.com/zarr-developers/zarr-python/pull/651 )
As `.pop(...)` already catches the `KeyError` if a default value is supplied, use that to simplify the code a bit.
TODO:
> Provide default if `.pop(...)` errors

- zarr/n5.py
We are interested in using lossy jpeg compression for 2D / 3D uint8 data. A java implementation of this exists for n5: https://github.com/saalfeldlab/n5-jpeg, but zarr cannot decode these chunks because `jpeg` is not in the list of hard-coded compressors in `zarr/n5.py` . Because this jpeg compression is specialized to the point of being a hack, it doesn't make sense to add it to the list of hard-coded compressors. Instead, this PR enables reading/writing an `N5Store` with an arbitrary compressor.   
TODO:
> enable arbitrary compressors for N5Store

- docs/release.rst
- zarr/convenience.py
- zarr/tests/test_convenience.py
Closes #613 
This only affect the root as _copy does the right thing on recursion.
> Copy also attributes on root in copy_all

- .github/workflows/releases.yml
- zarr/__init__.py
It seem like setuptools scm can screw up and this should ensure we catch
that in CI before making the wheel.
> Add guard as to version number;

- zarr/storage.py
Fixes https://github.com/zarr-developers/zarr-python/issues/669
`LMDBStore` had its own way of handling text before `ensure_text` was added to Numcodecs. With that utility function now available, we can simplify this a bit and avoid some subtleties of the LMDB implementation.
Similarly `DBMStore` had some of its own text handling issues that can be solved the same way.
Finally inline all `str.encode` calls to make it clearer what is happening in both  `LMDBStore` and `DBMStore`.
TODO:
> Simplify text handling in DB `Store`s

- .travis.yml
- README.md
- requirements_dev_optional.txt
- windows_conda_dev.txt
There are regular issue where it shows decrease of coverage while only
non-executable lines are added (e.g. comments), this might be dues to
out of order reception of reports from travis-ci jobs.
We did activate codecov.io, which does not appear to have this issue.
> Finish removing coverall

- .github/workflows/python-package.yml
- requirements_dev_optional.txt
We are out of travis.ci hours; start migrating to actions.
Not complete; none of the coverage uploading and testing with Mongo or azure is ran here.
> Start migrating away from Travis

- .github/workflows/python-package.yml
- requirements_dev_optional.txt
Travis not working anymore; so now we are using github action. 
Slowly rebuild the functionality of travis-ci and test on 3.6 and 3.8 as well as multiple numpy version.
> Grow testing matrix on 3.6, 3,8 and latest numpy

- .github/workflows/python-package.yml
- zarr/tests/test_core.py
- zarr/tests/test_storage.py
Again to get back to our 100% coverage.
> try to install azurite on github action

- zarr/storage.py
NDBM is not package by conda on non-mac; so it's hard to test on github action. 
Marking as skip to try to get coverage back to 100%
> try to skip ndbm in coverage.

- .coveragerc
- zarr/tests/test_storage.py
The ndbm tests are also ignored from coverage as ndb is not installable
on ghaction on non-macos.
> Ignore bench file in coverage report, ignore skipped tests.

- appveyor.yml
1) On appveyor, ABS store represent close to 25% of the test time  8min
total, see 10 slowest tests below).
2) Appveyor is the slowest of the CI, the one we wait for most of the
time.
3) ABS has not reason to behave differently on different Python
versions.
4) We might be able to also test windows on WSL in GH-actions.
```
========================== slowest 10 test durations ==========================
43.32s call     zarr/tests/test_core.py::TestArrayWithABSStore::test_resize_2d
21.28s call     zarr/tests/test_hierarchy.py::TestGroupWithABSStore::test_getitem_contains_iterators
17.72s call     zarr/tests/test_core.py::TestArrayWithABSStore::test_np_ufuncs
17.54s call     zarr/tests/test_core.py::TestArrayWithABSStore::test_array_2d
14.79s call …
```
> Test Azure on only one version of Python on windows.

- zarr/storage.py
- zarr/tests/test_storage.py
Newer version of azure and azurite are stricter on allowing queries on
empty blob names; here we add checks that blob names are non empty, as
well as take the slow path (which is the correct one) when trying to get
a store size.
> Update azure code and skip gdbm coverage.

- docs/release.rst
- requirements_dev_minimal.txt
- zarr/core.py
- zarr/creation.py
- zarr/errors.py
- zarr/indexing.py
- zarr/tests/test_core.py
- zarr/tests/test_indexing.py
- zarr/tests/test_storage.py
- zarr/util.py
This PR adds the capability to partially read and decompress chunks in an arrays that are initialized with blosc decompression and an fsspec based backend. Its related to [zarr-specs #59](https://github.com/zarr-developers/zarr-specs/issues/59)
I did some initial benchmarking showing processing time for indexing with various array and chunk shapes filled with random numbers stored on s3:
array_shape=(1000, 1000), chunk_shape=(100, 500)
-------------------------------------------------------------------------
array_shape=(10000, 10000), chunk_shape=(1000, 1000)
-------------------------------------------------------------------------------------
array_shape=(10000, 10000), chunk_shape=(2000, 5000)
---------------------------------------------------------------------------------- …
> Partial read

- .github/workflows/python-package.yml
- zarr/indexing.py
- zarr/tests/test_core.py
- zarr/util.py
Those were ran by tox, and got lost in the migration.
Maybe we want to make them a separate  job at some point for speed and not run them on all matrix elements.
> Reenable mypy and flake8 linting on CI.

- zarr/meta.py
Changes in zarr's annotations, numpy, and/or mypy have led to failures on `mypy zarr/`across a large number of PRs. This tries to take the most direct route to passing GitHub actions so that PRs can be unblocked.
Thanks to @rgommers and @seberg for jumping in.
TODO:
> Update dtype usage in zarr/meta.py

- .github/workflows/releases.yml
- tox.ini
This will run way faster than travis and should allow to distinguish
actual test failure from formatting failures in PRs if we deactivate
flake8 from tox.
> Remove 3.5 configuration from tox, run pyflakes on ghaction.

- zarr/storage.py
- zarr/tests/test_storage.py
key_separator: fix handling of meta keys
This rebases and cleans a fix from Martin's original PR.
Two new test methods fail without it and pass with since
keys for meta-files like `.zarray` were being converted
into `/zarray`.
see: https://github.com/martindurant/zarr/pull/1/commits/5795bc7368eb0b86aaeb1956ffed514e672db96e
TODO:
* [] Add docstrings and API docs for any new/modified user-facing classes and functions
> FSStore: key_separator fix

- zarr/tests/test_convenience.py
The main reason for this is that closing h5py files using `atexit` seems to be a bit buggy. If I run with `pytest`, it's fine, but if I use `python setup.py test`, it will crash on exit.
Using pytest fixtures, we can avoid `atexit` entirely and files will be closed at the end of the test. Unfortunately, this means `unittest.TestCase` cannot be used, so switch to a plain class works. With the fixture, we can parametrize zarr vs. h5py and drop the extra classes.
TODO:
* [N/A] Add docstrings and API docs for any new/modified user-facing classes and functions
* [N/A] New/modified features documented in docs/tutorial.rst
* [N/A] Changes documented in docs/release.rst
* [N/A] Docs build locally (e.g., run ``tox -e docs``)
> Fixtureize and parametrize h5py copy tests.

- .github/workflows/releases.yml
- docs/release.rst
- requirements_dev_optional.txt
Prepares the release notes for a version before merging more v3 specific code, during which `master` will be in a pre-release state (`.devX`, `.betaY`, etc.)
Also fixes two build issues which are making recent PRs fail:
* duplicate block in `releases.yml` likely introduced during conflict resolution
* moto recently went to 2.0 and now requires `moto[server]` for installation
> 2.7.0: update release section

- zarr/core.py
- zarr/tests/test_hierarchy.py
closes #717
I added a couple of FSStore test classes to test_hierarchy.py. The "NestedFSStore" class tests the fix on the specific case raised in #717.
TODO:
~* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions~
~* [ ] New/modified features documented in docs/tutorial.rst~
> Update Array to respect FSStore's key_separator 

- docs/spec/v2.rst
Various implementations allow for defining the separator between the
dimension indexes when writing chunks:
* n5-zarr defines a `dimensionSeparator` parameter;
* zarr-python's NestedDirectoryStore does so by default
* and FSStore provides a `key_separator` parameter;
* tensorstore has a `key_encoding` parameter; and
* jzarr is looking to add the same functionality.
When writing an array, it is straight-forward to set this separator
and have arrays properly configured. Consumers of such arrays,
however, must either know *a priori* if their arrays use a
non-default separator or must loop through all possible chunks keys
searching for the right one.
By defining adding an optional metadata key to the .zarray, we:
* preserve the efficient configuration of arrays
* while keeping the v2 spec …
> v2 spec: add optional dimension_separator (see #707)

- docs/release.rst
- zarr/core.py
- zarr/creation.py
- zarr/hierarchy.py
- zarr/meta.py
- zarr/n5.py
- zarr/storage.py
- zarr/tests/test_core.py
- zarr/tests/test_storage.py
- zarr/tests/test_util.py
- zarr/util.py
Implements the new optional array metadata key, `dimension_separator`, from #715 for the Python library.
close: #530
* All top-level storage classes now take an optional `dimension_separator`
parameter which defaults to `None`, but can also be `.` or `/`.
* A ValueError is raised at normalization time if this is not the case.
* `None`s are normalized to the default of `.` in all except the
NestedDirectoryStore case.
* The value is stored as `self._dimension_separator` on participating classes
so that array creation can lookup the value.
* This value deprecates the `key_separator` value from FSStore.
* Wrapper classes like LRUCacheStore and ConsolidatedMetadataStore *do not*
follow this pattern and instead rely on the value in the underlying store.
> Implement `dimension_separator` for Python storage classes (See #715)

- zarr/creation.py
- zarr/tests/test_hierarchy.py
#Description
While working on the zarr_implementations repository, at one point I generated data with `create_dataset` using `dimension_separator='/'`, but with the default FSStore which has a key_separator of '.'. This did not result in any warning, but generated a flat storage format despite the specification of `dimension_separator`. This PR is intended to prevent this by checking for consistency between a store's dimension separator and the one passed as an argument to `create_dataset`.
TODO:
> raise an error if create_dataset's dimension_separator is inconsistent with the provided store

- zarr/tests/test_util.py
- zarr/util.py
Jupyterlab 3 changed how widgets are installed. Now both the frontend and backend are installed via pip/conda. If a user also then installs the front using the `jupyter labextension install` command then they can end up breaking things by trying to install
an old version. This should hopefully help avoid leading users astray.
TODO:
* [NA] Add docstrings and API docs for any new/modified user-facing classes and functions
* [NA] New/modified features documented in docs/tutorial.rst
* [NA?] Changes documented in docs/release.rst
> Updated ipytree warning for jlab3

- zarr/core.py
- zarr/tests/test_hierarchy.py
This reverts commit 449ed26fbb63915f159735214ce840b3ddcb42a9.
see: #709 #728
> Revert "Update Array to respect FSStore's key_separator  (#718)"

- docs/tutorial.rst
Add some candidate rechunking docs as discussed in #727 
TODO:
> add section on rechunking to chunk optimisation section of tutorial 

- zarr/storage.py
close #739
Set normalize_keys to False by default to have unification across all the store implementations.
TODO:
> FSStore: default to normalize_keys=False

- .github/workflows/python-package.yml
- tox.ini
Builds that are pinned to the 1.16.x numpy series are starting to fail. Dropping those in favor of 1.17.x numpy to keep as much backwards compatibility as possible.
see:
* #774 which drops Python 3.6
* #749 which bumps h5py to 3.2
> Drop the additional numpy 1.16 test

- docs/spec/v2.rst
The only real change here "simple" -> "arbitrary".
This came up in:
https://github.com/zarr-developers/zarr-specs/issues/41#issuecomment-841726137
TODO:
> [spec] Clarify that arbitrary key/value pairs are OK for attributes

- zarr/tests/test_core.py
I came across a missing assert in the `test_hexdigest` method of `TestArray` (needed to verify that the checksums match the expected values)
TODO:
~* [ ] Add unit tests and/or doctests in docstrings~
~* [ ] Add docstrings and API docs for any new/modified user-facing classes and functions~
~* [ ] New/modified features documented in docs/tutorial.rst~
~* [ ] Changes documented in docs/release.rst~
~* [ ] Test coverage is 100% (Codecov passes)~
> add missing assert when comparing array checksums in TestArray

- docs/conf.py
`add_stylesheet` was deprecated in 1.8 and removed in 4.0 [1]. The replacement, `add_css_file` was added in 1.0.
You don't have a minimum Sphinx version specified, so I'm not sure what is required, but 1.0 is pretty old.
[1] https://www.sphinx-doc.org/en/master/extdev/deprecated.html?highlight=add_stylesheet
> Fix build with Sphinx 4.

- docs/contributing.rst
see: https://github.com/zarr-developers/zarr-python/issues/544
This matches what I'm currently doing. Alternatively, we can add steps into the workflows for the zenodo linkage.
> Update release notes

- docs/release.rst
- requirements_dev_optional.txt
With #773 now merged (:tada:), I'd like to get this out (today? Even thought it's a Friday?!) but it's a fairly big one. Any thoughts? Would anyone want an RC to test with?
> 2.9.0 release notes

- docs/release.rst
- zarr/tests/test_dim_separator.py
see:
* https://github.com/conda-forge/zarr-feedstock/pull/48
* #817
The conda-forge release failed since fsspec is not installed by default. In order to get Zarr deployed ASAP (re: https://github.com/DiamondLightSource/python-tristan/pull/62) this simply properly handles the test issue that @QuLogic brought up in #817.
It might be that moving forward, fsspec should be installed & tested for conda-forge releases. If not, then a minimal test workflow should be added here to show that the conda-forge requirements (below) suffice to run or skip all tests:
```
channels:
- conda-forge
- defaults
dependencies:
- python < 3.9.0
- wheel
- numcodecs
- numpy
- pip
- pip:
- asciitree
- fasteners
- pytest
- setuptools_scm
```
> Zarr 2.9.1: fix conda release

- docs/release.rst
- zarr/tests/test_dim_separator.py
Be stricter about where and how regression data are discovered, during testing.  This fixes some tests that are failing during the Conda-forge release process.
As previously mentioned in https://github.com/zarr-developers/zarr-python/pull/819#discussion_r694717559:
- Ensure that, regardless of the test runner working directory, the regression data can be found.
- During `zarr.tests.test_dim_separator.test_open`, open an array in read-only mode, to prevent accidental creation of an empty array when the expected array does not exist, which would leave droppings in the test runner working directory.
TODO:
> Be more robust in how regression data are discovered

- docs/release.rst
- zarr/tests/test_dim_separator.py
Codecov recognises that we aren't testing with `fsspec`.  Perhaps it is less picky if we use `pytest.param` to parametrise the tests.
TODO:
> Circumvent Codecov's legitimate complaint without resorting to pragma

- docs/release.rst
- requirements_dev_optional.txt
- zarr/codecs.py
- zarr/meta.py
- zarr/storage.py
- zarr/tests/test_core.py
- zarr/tests/test_meta.py
- zarr/util.py
* Ensures that the fill value of structured arrays that contain objects
is encoded using object_codec.
TODO:
> Fix structured arrays that contain objects #806

- zarr/creation.py
- zarr/tests/test_convenience.py
If a store does not have a `dimension_separator` set,
then requesting a non-`None` value should not be an
error.
TODO:
> Ignore None dim_separators in save_array (fix #831)

- zarr/storage.py
Set `normalize_keys` to `False` by default in `FSStore`. Addresses #841
> set normalize_keys=False in fsstore constructor

- zarr/n5.py
- zarr/tests/test_core.py
Fix for #693  
Changed both N5 and N5FS
Added test fixture to capture stdout
Updated test making sure a warning is printed
Let me know if there are any docs changes I need to do.
Thanks!
TODO:
> Fix: N5 keywords now emit UserWarning instead of raising a ValueError

- zarr/tests/test_core.py
Should fix partial read test by defining blocksize for Blosc compression.
related to conversation in #859 
TODO:
> defines blocksize for array, updates hexdigest values

- zarr/util.py
Unused variable, as indicated by [lgtm.com](https://lgtm.com/projects/g/zarr-developers/zarr-python/snapshot/9546f2312c02be3e91a4a67c8631e21bbb9c73e9/files/zarr/util.py?sort=name&dir=ASC&mode=heatmap#xcd2184c787afdbd8:1)
TODO:
> blocks_to_decompress not used in read_part function

- .github/workflows/python-package.yml
- .github/workflows/windows-testing.yml
- requirements_dev_minimal.txt
- tox.ini
In an attempt to track down https://github.com/zarr-developers/zarr-python/issues/858
Closes #629
TODO:
> Activate Python 3.9

- .github/workflows/minimal.yml
- zarr/tests/test_dim_separator.py
Under some test conditions (conda-forge, Debian builds), the
fixtures directory is not available and is then re-created.
When dimension_separator is not passed to DirectoryStore, then
no metadata is assigned to the file. For the "flat" (as opposed
to "flat_legacy") fixture, this meant that the NestedDirectoryStore
did not correct its behavior leading to a failure.
see:
- https://github.com/conda-forge/zarr-feedstock/pull/56
- https://github.com/zarr-developers/zarr-python/issues/858
TODO:
fix #858
> Pass dimension_separator on fixture generation (fix #858)

- docs/contributing.rst
- docs/release.rst
- docs/spec/v1.rst
- docs/spec/v2.rst
- docs/tutorial.rst
- zarr/core.py
- zarr/creation.py
- zarr/n5.py
- zarr/storage.py
- zarr/tests/test_dim_separator.py
- zarr/tests/test_storage.py
Started looking into Zarr, just fixing a few typos, mostly in docs.
TODO:
> Fix typos found by codespell

- zarr/core.py
- zarr/indexing.py
- zarr/tests/test_core.py
- zarr/tests/test_util.py
- zarr/util.py
Built-in functions [all()](https://docs.python.org/3/library/functions.html#all) and [any()](https://docs.python.org/3/library/functions.html#any) do not require a comprehension, they operate directly on a generator expression.
This fixes these DeepSource.io alerts:
https://deepsource.io/gh/DimitriPapadopoulos/zarr-python/issue/PTC-W0016/occurrences
I suppose there is no need to document such a minor commit in `docs/tutorial.rst`, is there?
TODO:
> Unnecessary comprehension

- zarr/convenience.py
- zarr/indexing.py
- zarr/sync.py
- zarr/tests/test_core.py
- zarr/tests/test_creation.py
- zarr/tests/test_hierarchy.py
- zarr/tests/test_storage.py
- zarr/tests/test_sync.py
- zarr/util.py
In Python 3, all classes implicitly inherit from `object`.
This fixes these DeepSource.io alerts:
https://deepsource.io/gh/DimitriPapadopoulos/zarr-python/issue/PYL-R0205/occurrences
TODO:
> No need to inherit from `object`

- zarr/core.py
Python implicitly returns `None` anyway.
This fixes this DeepSource.io alert:
https://deepsource.io/gh/DimitriPapadopoulos/zarr-python/issue/PYL-R1711/occurrences
TODO:
> Useless `return`

- zarr/_storage/absstore.py
- zarr/n5.py
- zarr/storage.py
These methods don't use `self`.
This fixes a few of these DeepSource.io alerts:
https://deepsource.io/gh/DimitriPapadopoulos/zarr-python/issue/PYL-R0201/occurrences
I have not changed the multiple occurrences under `zarr/test_*.py`.
TODO:
> Decorate a few method with `@staticmethod`

- zarr/tests/test_storage.py
Fix this DeepSource.io alert:
https://deepsource.io/gh/DimitriPapadopoulos/zarr-python/issue/PTC-W0018/occurrences
> It is unnecessary to use a `list` or `tuple` literal within a call to `tuple`, [list](url), [set](url), or [dict](url) since there is a literal syntax for these types.
TODO:
> Remove unnecessary literal

- zarr/storage.py
Fix this DeepSource.io alert:
https://deepsource.io/gh/DimitriPapadopoulos/zarr-python/issue/PYL-R1706/occurrences
An instance of the pre-Python 2.5 ternary syntax is being used. It is recommended to use an `if` expression such as: `foo if condition else bar`. Using `[condition] and [on_true] or [on_false]` may also give wrong results when `on_true` has a false boolean value.
TODO:
> use an if `expression` instead of `and`/`or`

- zarr/convenience.py
- zarr/creation.py
- zarr/tests/test_core.py
Fixes these DeepSource.io alerts:
https://deepsource.io/gh/DimitriPapadopoulos/zarr-python/issue/PTC-W0039/occurrences
> It is unnecessary to provide `None` as the default value when the key is not present in the dictionary as `get` implicitly returns `None`.
TODO:
> Unnecessary `None` provided as default

- docs/tutorial.rst
- zarr/storage.py
Pulls doc fixes from PR ( https://github.com/zarr-developers/zarr-python/pull/636 ). Namely using `tobytes` in docs (the preferred NumPy API for this functionality [going forward]( https://numpy.org/doc/stable/reference/generated/numpy.ndarray.tostring.html )).
TODO:
> Use `tobytes` in docs

- zarr/storage.py
Fixes #881.
Fix this DeepSource.io alert:
https://deepsource.io/gh/DimitriPapadopoulos/zarr-python/issue/PTC-W0063/occurrences
> Calls to `next()` should be inside `try-except` block.
> 
> When the iterator is exhausted, `StopIteration` exception is raised. When used inside a generator, this can cause unexpected behavior. If not handled, it will propagate out of the generator causing termination. [PEP-479](https://www.python.org/dev/peps/pep-0479/) has been accepted to fix this problem. It will modify the behavior of `StopIteration` in generators.
> 
> Each call to `next()` should be wrapped in a `try-except` block to explicitly handle `StopIteration` exceptions.
TODO:
> Unguarded next inside generator

- requirements_dev_optional.txt
Use of the short rather than `fsspec` and `s3fs` separately leads
to an old version of s3fs being installed. (The benefit of the
shortcut is that it prevents dependabot PRs from failing.)
see:
* https://github.com/fsspec/s3fs/issues/528
* https://github.com/zarr-developers/zarr-python/pull/914
> Drop shortcut `fsspec[s3]` for dependency

- zarr/tests/test_storage.py
Variable `port` is initialized as an integer, should be formatted with `%d`.
TODO:
> Proper C-style formatting for integer

- zarr/convenience.py
- zarr/tests/test_storage.py
This PR fixes a small bug in the `consolidate_metadata` convenience function where, when using fsspec compatible store paths, the `FSStore` was opened as read-only, causing the write of the consolidated metadata key to fail.
Closes #915  
cc @martindurant, @freeman-lab
TODO:
> fix consolidate_metadata with FSStore

- zarr/storage.py
- zarr/tests/test_storage.py
There is a bug causing incorrect length being written to the zip file, because Zipfile thinks the len() of the passed object is the length in bytes, but it was passing a ndarray, whose len() is the number of rows. The fix is to convert to bytes before passing to zipfile.writestr()
More details on how to reproduce this bug are here:
https://github.com/zarr-developers/zarr-python/issues/931
> Fix bug where the checksum of zipfiles is wrong

- .github/workflows/python-package.yml
- requirements_dev_optional.txt
This upgrades the mongodb service in github actions. 
Closes #905 
TODO:
> Upgrade MongoDB in test env

- docs/release.rst
As requested by @joshmoore, this PR adds a release note regarding the recent addition of `BaseStore` and `KVStore` in Zarr 2.11. Please suggest improvements/clarifications!
I think the changes should be transparent to the typical user of Zarr (especially those using it indirectly via Dask or Xarray). It is mainly important for library authors or those developing their own store classes.
TODO:
> add release note regarding introduction of BaseStore and KVStore

- .github/workflows/minimal.yml
- .github/workflows/python-package.yml
- docs/release.rst
- docs/tutorial.rst
- environment.yml
- requirements_dev_minimal.txt
- setup.py
- tox.ini
- windows_conda_dev.txt
- zarr/_storage/absstore.py
- zarr/core.py
- zarr/creation.py
- zarr/util.py
In #738, despite general agreement that most people expect write_empty_chunks to default to False, @d-v-b decided to go the safe, uncontroversial route to get the PR merged, and made the default value True. All this PR does is set the default to False.
Convenient links to discussion suggesting write_empty_chunks=False should be the default:
- @meggart [says](https://github.com/zarr-developers/zarr-python/pull/738#issuecomment-848649951): "In Zarr.jl, *not* writing empty chunks is already the default [...] so I would be in favor of changing the default behavior in Python as well.
- @shoyer [says](https://github.com/zarr-developers/zarr-python/pull/738#issuecomment-848950903): "it is not clear to me why you would *not* want to do this. I think this could be the new default behavior."
- …
> Set write_empty_chunks to default to False

- .github/workflows/minimal.yml
- docs/release.rst
Quite a bit of text so opening the release notes for 2.11 as a PR. Feedback welcome over the next few hours. Then I'll get the release out and start work on the blogpost (https://github.com/zarr-developers/zarr-python/issues/901)
cc: @msankeys963 @d-v-b @jni @jakirkham @grlee77 @rabernat
> Release notes 2.11.0

- docs/release.rst
- zarr/convenience.py
- zarr/creation.py
- zarr/hierarchy.py
- zarr/storage.py
- zarr/tests/test_convenience.py
- zarr/tests/test_storage.py
This PR removes the `clobber` argument from `normalize_store_arg` and fixes #975 .
~TODO:~
> remove `clobber` from `normalize_store_arg` to enable writes to consolidated FSStore groups

- docs/release.rst
- zarr/indexing.py
- zarr/tests/test_indexing.py
Fixes #967 by adding a check for scalar numpy types.
TODO:
> Fix indexing for scalar numpy values (#967)

- docs/release.rst
- docs/tutorial.rst
- zarr/core.py
- zarr/creation.py
This PR resolves #965 by changing the default of `write_empty_chunks` to `True`. I am not sure if we want to document the current limitations of `write_empty_chunks=False`, or if we want to treat those as bugs that will be fixed eventually. In the future we may want to error if a user sets `write_empty_chunks=True` with an unsupported data type, but that change should probably be made in a future PR that implements the solution described in https://github.com/zarr-developers/zarr-python/issues/965#issuecomment-1058723797 and https://github.com/zarr-developers/zarr-python/issues/965#issuecomment-1058725944
TODO:
> Revert change to default write_empty_chunks.

- .github/workflows/minimal.yml
- .github/workflows/python-package.yml
- .github/workflows/windows-testing.yml
- docs/release.rst
- docs/tutorial.rst
- zarr/core.py
- zarr/creation.py
Backport #1001 on top of 2.11.1 for immediate release.
TODO:
> 2.11.2 release

- zarr/creation.py
Fix issue identified in https://github.com/zarr-developers/zarr-python/pull/1001#issuecomment-1090155352. I have manually tested this change with:
```python
>>> import zarr
>>> zarr.__version__
'2.11.2'
>>> a = zarr.create((100, 100), chunks=(100, 50), dtype="i4", store="example.zarr")
>>> a[:] = 0
>>> import os
>>> os.listdir("example.zarr")
['.zarray', '0.0', '0.1']
```
TODO:
> Fix missing case to fully revert change to default write_empty_chunks.

- zarr/__init__.py
- zarr/convenience.py
- zarr/hierarchy.py
- zarr/storage.py
- zarr/tests/test_convenience.py
- zarr/tests/test_core.py
- zarr/tests/test_hierarchy.py
The first commit here fixes a couple of bugs in the v3 convenience functions that were revealed when working on a branch of Xarray that adds tests with Zarr v3.
The `rename` method on MemoryStoreV3 was also fixed here (GroupV3 tests with this store type had inadvertently been left commented out in the previously merged PR).
Some outdated commments/TODOs were also cleaned up and comments were added explaining some cases where desired v3 behavior is not fully clear (e.g. `test_path`).
TODO:
> misc Zarr V3 bug fixes: open_group, open_consolidated and MemoryStoreV3

- zarr/core.py
- zarr/tests/test_core.py
This PR is trying to address the issue reported in #938:
```
When I repeatedly append data to a zarr array in s3, appending takes longer and longer and longer
```
The issue appears to be coming from [a method in zarr/core.py](https://github.com/zarr-developers/zarr-python/blob/e381bf76261a1cc9c10613465ab39b968a24737b/zarr/core.py#L2414) when trying to [remove any chunks not within range](https://github.com/zarr-developers/zarr-python/blob/e381bf76261a1cc9c10613465ab39b968a24737b/zarr/core.py#L2430).
Basically the existing implementation iterates through **all** the `old` chunks and removes those that don't exist in the `new` chunks. This seems time-consuming and unnecessary when appending new chunks to the end of an existing array with a large number of chunks.
Regarding this, this PR …
> Appending performance improvement

- docs/release.rst
- docs/tutorial.rst
- zarr/storage.py
- zarr/tests/test_convenience.py
- zarr/tests/test_core.py
- zarr/tests/test_storage.py
This PR adds a new argument to `FSStore` which allows one to pass an existing fsspec filesystem object from which to generate the FSStore. The need to initialize an FSStore from an existing filesystem came up in https://github.com/pangeo-forge/pangeo-forge-recipes/issues/254. It seems like this is something people may want to do more generally.
Also fixes #993 by simply removing the check for list-ability when initializing an FSStore.
TODO:
> Create fsstore from filesystem

- zarr/core.py
This PR adds more comments to `resize` method to address [possible end-user concerns described in this issue report](https://github.com/zarr-developers/zarr-python/issues/1017).
TODO:
> Update resize doc

- docs/release.rst
Updated release docs for review before the first pre-release tag of 2.12.
> Release notes for 2.12.0a1

- pytest.ini
Following on from #654, I wanted to make sure that no warnings are being missed by the tests. This widens those that are considered errors to everything coming from a zarr.* package. (We could consider including closely related packages like fsspec, numcodecs, etc.)
The only ignore statement that was needed, perhaps for review by @d-v-b, was the n5/compression statement.
> Make all unignored zarr warnings errors

- .github/workflows/minimal.yml
- .github/workflows/python-package.yml
- .github/workflows/windows-testing.yml
- docs/release.rst
- zarr/_storage/store.py
- zarr/convenience.py
- zarr/core.py
- zarr/hierarchy.py
- zarr/tests/test_convenience.py
- zarr/tests/test_core.py
- zarr/tests/test_creation.py
- zarr/tests/test_hierarchy.py
- zarr/tests/test_storage_v3.py
Following discussion at this week's community call, a few additional
precautions are being implemented here:
All tests should continue passing in GHA since the variable is set. Local runs, however, need some consideration in order to properly `xfail`.
See also #1020
> Mark V3 API experimental

- .github/workflows/Pre-commit-hooks.yml
- .github/workflows/minimal.yml
- .github/workflows/python-package.yml
- .github/workflows/windows-testing.yml
- README.md
- codecov.yml
- docs/conf.py
- docs/contributing.rst
- docs/index.rst
- docs/release.rst
- docs/tutorial.rst
Closes https://github.com/zarr-developers/community/issues/44
Moves all branch references from `master` to `main`. These are self-referential links (other Numcodecs things like CI).
Also updates terminology in doc generating code similarly and 3rd party links.
Other GitHub Actions and 3rd party links are left alone if they haven't already made the transition.
xref: https://github.com/pypa/gh-action-pypi-publish/issues/83
xref: https://github.com/conda-incubator/setup-miniconda/issues/231
xref: https://github.com/Blosc/c-blosc/issues/336
TODO:
> Move `master` to `main`

- README.md
Removed Travis-CI badge and added GH-Actions badge for Linux Testing in README.md file.
Related to #1041
> Replace Build Status badge with Linux testing.

- .deepsource.toml
The default Python version has become 3.x.x:
https://deepsource.io/docs/analyzer/python/
> `runtime_version`
> * **Type**: [String](https://toml.io/en/v1.0.0#string)
> **Presence**: optional
> **Description**: Runtime version of your language in [semver](https://semver.org/).
> * **Available Values**: "2.x.x", "3.x.x"
> * **Default Value**: "3.x.x"
TODO:
> Update DeepSource configuration

- docs/release.rst
- docs/tutorial.rst
Tiny typo fix to close quotes in the docs code snippets
TODO:
> Close quote typo fix

- docs/release.rst
- docs/tutorial.rst
- zarr/core.py
- zarr/meta.py
Fix a few typos found by codespell.
TODO:
> More typos found by codespell

- docs/conf.py
- docs/release.rst
- requirements_rtfd.txt
Added `sphinx_copybutton` extension to documentation.
Configuration strips `>>>`, `$`, and cell outputs, etc. Also supports multi line shell scripts `\\` (if needed in the future)
Here is the build with it enabled. It seems to be working as expected.
https://zarr--1124.org.readthedocs.build/en/1124/index.html
If the copy button has to be styled we can add a CSS too, right now its the default.
closes #1084 
TODO:
> Add copy button to documentation

- docs/contributing.rst
- docs/release.rst
As discussed with @rabernat and @jakirkham, in order to encourage
more folks with push rights to release zarr-python, this change
makes it clear that a release is possible completely from within
GitHub. The previous instructions will continue to work but have
been removed to avoid confusion.
TODO:
> Simplify release docs

- zarr/_storage/store.py
- zarr/creation.py
- zarr/hierarchy.py
- zarr/storage.py
- zarr/tests/test_convenience.py
- zarr/tests/test_core.py
- zarr/tests/test_creation.py
- zarr/tests/test_hierarchy.py
- zarr/util.py
closes #1039
v3 spec states path = '/' for arrays gives an array at /meta/root.array.json
path = '/' for groups gives a group at /meta/root.array.json
In this implementation `path=None` will also result in a root array. Creation routines default to `path=None`, so this makes it so that the path argument does not have to be manually specified. 
TODO:
> Zarr v3: support root path

- docs/_static/custom.css
- docs/release.rst
Add recent notes e.g. for #1123, #1085, #934 which could use some testing.
(@madsbk I note from the TODO list below that a next step would be an update to the tutorial with `meta_array`)
TODO:
> 2.13.0a2 release notes

- setup.py
`zarr` actually depends on `numcodecs>=0.10`, because it [imports `numcodecs.compat.ensure_ndarray_like`](https://github.com/zarr-developers/zarr-python/blob/main/zarr/util.py#L13) that has been introduced in `0.10.0`.
TODO:
> Fix numcodecs dependency

- zarr/_storage/v3.py
- zarr/indexing.py
[Redundant list comprehension can be replaced using generator PYL-R1728](https://deepsource.io/gh/DimitriPapadopoulos/zarr-python/issue/PYL-R1728/occurrences)
> Using a container in place of a generator for calls that can accept both, slows down the performance. Consider using generators for all function calls which accept both containers and genertors.
TODO:
> Use generator instead of list comprehension

- zarr/convenience.py
closes #1141
`path=None` support for v3 was previously added in gh-1085. This change should have also been made at that time.
TODO:
> allow empty path in open_consolidated for zarr v3

- .github/workflows/Pre-commit-hooks.yml
- .pre-commit-config.yaml
- docs/contributing.rst
- docs/release.rst
> Prepare 2.13.0 release

- docs/release.rst
- zarr/tests/test_storage.py
See description in https://github.com/zarr-developers/zarr-python/pull/1143 Testing locally, however, does not suffice. In this case, the relative path in the test worked for me, but doesn't work on conda-forge. The only reliable way to be sure is to run `./build-locally.py` in the zarr-feedstock **against pre-tagged code**. ⚠️ 
TODO:
> 2.13.2: another fix for the conda-forge tests

- docs/release.rst
- zarr/indexing.py
- zarr/tests/test_indexing.py
This stops chunks being read unnecessarily when a slice selection with a step was used (reported in #843). 
Previously all chunks spanning the start-end range would be used regardless of whether they contained any elements. The changes in this PR are a small modification to `zarr.indexing.SliceDimIndexer` to stop it yielding empty selections up to `zarr.Array._get_selection`. Previously the chunk would be read and have no elements extracted from it, this stops it ever looking at the empty chunk.
I'm unsure about if a unit test should be added for this. It would be feasible to have a test asserting that only the minimal set of chunks are read, but that feels like it's testing an implementation detail. I'm happy to construct a test if that would be useful. Regardless I'll add some test code …
> Omit chunks with no elements in slice selection with step

- docs/index.rst
- docs/installation.rst
> fix #1167: Added installation.rst to docs

- .pre-commit-config.yaml
This will avoid this kind of warnings with codespell 2.2.2:
```
WARNING: Decoding file using encoding=utf-8 failed: fixture/8/0/11
WARNING: Trying next encoding iso-8859-1
```
Seen in:
https://results.pre-commit.ci/run/github/48049137/1666036569.rj425j-vQKyvNbJ0CUHdcQ
TODO:
> Tell codespell to skip `fixture` / fix pre-commit

- pyproject.toml
I completely forgot that `setuptools` introduced editable installs in `v64.0.0`. This means that the installation will fail if a developer, who has `setuptools` < `v64.0.0` installed locally, tries to install `Zarr` with `pip install -e .` right now.
With this PR, the local version of `setuptools` will be automatically updated to the compatible version.
For more information see this tweet - https://twitter.com/juanluisback/status/1557734536586625025?t=rzVtT-91AwzSOvBHanCJ9g&s=19
TODO:
> Require `setuptools` 64.0.0+

- .lgtm.yml
LGTM.com is being deprecated and replaced by GitHub code analysis:
[The next step for LGTM.com: GitHub code scanning!](https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/)
See also:
* #909
* #1127
* https://github.com/zarr-developers/zarr-python/pull/1158#issuecomment-1279834293
TODO:
> Remove LGTM.com configuration file

- .github/workflows/minimal.yml
- .github/workflows/releases.yml
Closes #1148
Dependabot will now automatically update the actions with their latest stable release!
TODO:
> Pin action versions (pypi-publish, setup-miniconda) for dependabot

- tox.ini
> Turned on isolated_build in tox.ini file

- zarr/creation.py
- zarr/hierarchy.py
- zarr/storage.py
Fix possible unbound variable error
Avoid extra zarr version check
Add Optional typing to indicate value might be None
> Fix linting errors

- zarr/errors.py
- zarr/hierarchy.py
- zarr/storage.py
* Yield from an iterable instead of iterating to yield items.
* `io.open()` is an alias for for the builtin `open()` function:
https://docs.python.org/3/library/io.html#io.open
* `IOError` is kept for compatibility with previous versions; starting from Python 3.3, it is an alias of `OSError`:
https://docs.python.org/3/library/exceptions.html#IOError
TODO:
> Apply some pyupgrade suggestions

- docs/contributing.rst
- zarr/hierarchy.py
This PR modifies the v3 implementation of `Group._array_iter`. Previous behavior unnecessarily called `contains_array` for keys known to be arrays (i.e. keys that ended in `.array.json`). These changes fast track the iterator to return v3 array keys. In practice, this reduces the number of times a key is searched for in a store.
TODO:
> fastpath _array_iter for array_keys

- zarr/hierarchy.py
> Add documentation for find/findall using visit

- .coveragerc
- .github/workflows/python-package.yml
- docs/contributing.rst
- docs/release.rst
- pyproject.toml
Following [the coverage configuration docs]( https://coverage.readthedocs.io/en/6.5.0/config.html#configuration-reference ) this moves `.coveragerc` into `pyproject.toml`.
<hr>
TODO:
> Consolidate `.coveragerc` into `pyproject.toml`

- .github/labeler.yml
- .github/workflows/needs_release_notes.yml
- docs/release.rst
See https://github.com/zarr-developers/zarr-python/pull/1193#issuecomment-1298824828
This will -
- label a PR with "needs release notes" if `docs/release.rst` has not been edited
- remove the label as soon as `docs/release.rst` is edited
A working demo - https://github.com/Saransh-cpp/zarr-python/pull/1
This will encourage (or maybe require, depending on the maintainers) developers to update `release.rst` with every PR! 
TODO:
> Workflow to label PRs with "needs release notes"

- docs/release.rst
- zarr/_storage/v3.py
- zarr/storage.py
- zarr/tests/test_storage.py
- zarr/tests/test_storage_v3.py
Re: https://github.com/zarr-developers/zarr-python/issues/1296
TODO:
> Handle fsspec.FSMap using FSStore store

- .github/workflows/releases.yml
- docs/release.rst
2.13.4 and 2.13.5 were not released due to the following error:
```
Error: Unable to resolve action `pypa/gh-action-pypi-publish@v1`, unable to find version `v1`
```
TODO:
> Bump pypi action

- zarr/storage.py
- zarr/tests/test_core.py
- zarr/util.py
Fixes https://github.com/zarr-developers/zarr-python/issues/1279
TODO:
> FSStore: use `ensure_bytes()`

- docs/release.rst
- zarr/storage.py
- zarr/tests/test_storage.py
NestedDirectoryStore which inherits from DirectoryStore only supports '/' as a dimension separator. However listdir uses the parent DirectoryStore.listdir which produces keys with an incorrect separator '.'
Fixes #1334
TODO:
> use store dimension separtor in DirectoryStore.listdir

- docs/release.rst
- pyproject.toml
- zarr/n5.py
- zarr/tests/test_core.py
Now that `blosc` support has been in the `n5` ecosystem for a while now (https://github.com/saalfeldlab/n5-blosc), we can remove the warnings relating to creating arrays with blosc compression via `n5store` variants.
TODO:
> remove blosc warnings from n5 compressor handling

- zarr/tests/test_attrs.py
This is a temporary fix for the larger issue of out-of-tree testing described in #1347, but this should allow a release of 2.14.1 which passes on conda.
TODO:
> Generate fixture for #1312 if it is missing

- docs/release.rst
- zarr/hierarchy.py
- zarr/tests/test_hierarchy.py
Closes #1352 and #1353
cc @flamingbear @rabernat 
TODO:
> Ensure `zarr.group` uses writable mode

- docs/api.rst
- docs/api/v3.rst
Hi all. I've added the API reference for V3 implementation in the docs. This issue was raised in the [community meeting](https://zarr.dev/community-calls) on 2/8 this week.
Linking this from #1337. Preview available here: https://zarr--1345.org.readthedocs.build/en/1345/api/v3.html
Let me know what you think. Suggestions welcome.
CC: @joshmoore @grlee77 @jstriebel 
TODO:
> Add API reference for V3 Implementation in the docs

- .pre-commit-config.yaml
- docs/release.rst
- zarr/_storage/v3.py
- zarr/tests/test_storage_v3.py
Fixes readonly error in `_normalize_store_arg_v3`
TODO:
closes #1382
> fix for readonly error in _normalize_store_arg_v3

- docs/release.rst
- zarr/tests/test_core.py
- zarr/util.py
`np.product` will be deprecated in favor of `np.prod` in the upcoming `numpy=1.25` release (xref https://github.com/numpy/numpy/pull/23314). I noticed some [related warnings](https://github.com/dask/dask/actions/runs/4860114177/jobs/8663559847?pr=10245#step:5:24892
) being emitted from `zarr` over in the `dask` test suite. This PR just replaces `np.product` with `np.prod`, which should be backwards compatible with older version of `numpy`. 
TODO:
> Avoid deprecated `product` in ``numpy=1.25``

- docs/release.rst
- zarr/tests/test_util.py
- zarr/util.py
The FutureWarning identified in https://github.com/zarr-developers/zarr-python/issues/552 is now a `TypeError` in the latest numpy release. We can fix this bu checking whether `isinstance(fill_value, np.void)` *before* checking whether `fill_value == 0` (that way, if `fill_value` is already a structured dtype, then we do not compare it with a scalar).
One symptom of this is that
```python
import numpy as np
import zarr
dtype = np.dtype([("a", np.float64), ("b", np.int64)])
zarr.open_array([], shape=1000, dtype=dtype
```
will crash with
```
TypeError                                 Traceback (most recent call last)
Cell In[4], line 1
----> 1 zarr.open_array({}, shape=1000, dtype=dtype)
File ~/workspace/zarr-python/zarr/creation.py:586, in open_array(store, mode, shape, chunks, dtype, …
```
> Fix `normalize_fill_value` for structured arrays

- zarr/indexing.py
You can pass a tuple of types you want to check as the second argument to `isinstance`. Therefore, merge multiple consecutive `isinstance` calls into one. It is clearer and improves readability.
TODO:
> Merge isinstance calls

- .github/workflows/python-package.yml
- .github/workflows/windows-testing.yml
- docs/release.rst
- pyproject.toml
This adds Python 3.11 to the Zarr test suite. 
TODO:
> test(ci): Run tests against python 3.11

- docs/release.rst
- zarr/creation.py
- zarr/tests/test_meta_array.py
Like the other creation functions, `open_array()` now takes the  `meta_array` argument.
TODO:
> `open_array()`: adding the `meta_array` argument

- docs/release.rst
Preparation for release of 2.15.0
TODO:
> 2.15.0: Remove pre-release warning

- docs/release.rst
- zarr/storage.py
Over at https://github.com/bayer-science-for-a-better-life/tiffslide/issues/72, we noticed that reading from a `tifffile.ZarrTiffStore` calls the store's `__getitem__` member function twice for each chunk. This is due to `k in self` below being routed through `KVStore.__getitem__`. 
https://github.com/zarr-developers/zarr-python/blob/8c98f4518ea20251c8ef3258276860a3cbef9eeb/zarr/_storage/store.py#L160
This patch adds a `KVStore.__contains__` member function, which does not require reading and decoding chunks for the membership test.
Using this patch, performance almost doubled using the benchmarks in the linked issue.
TODO:
> Add __contains__ method to KVStore

- .gitignore
- docs/api/core.rst
- docs/release.rst
- docs/tutorial.rst
- zarr/core.py
- zarr/indexing.py
- zarr/tests/test_core.py
- zarr/tests/test_indexing.py
Closes #518, #543, #545, #991.
This feature has been requested many times.
This adds the basic functionality of Dask's [`dask.array.Array.blocks`](https://docs.dask.org/en/stable/generated/dask.array.Array.blocks.html) indexing.
I explained the implementation in detail in #991. Please see details there.
This PR implements #991 and adds tests, tutorial, and docs.
This does allow integer and slice (with step of 1) block indexing, or a mix of the two, for Zarr arrays.
**QUESTION**
* I wasn't exactly sure where to put it in the change log. Currently its in 2.15.0, however, should I move that to Unreleased section??
TODO:
> Support Block (Chunk) Indexing

- docs/release.rst
- requirements_dev_optional.txt
- zarr/meta.py
- zarr/tests/test_meta.py
This PR refactors how codecs are instantiated in the current V3 implementation. This allows for default parameters to be omitted.
TODO:
closes #1443
> [V3] Allow for incomplete codec metadata using numcodecs.get_codec

- docs/release.rst
- zarr/storage.py
- zarr/tests/test_core.py
- zarr/util.py
It's the same thing as https://github.com/zarr-developers/zarr-python/pull/1305, but without ruff + black linting applied to the whole codebase, and thus a much cleaner diff.  
Some type hints were improved outside the core tests to ensure that mypy was happy.
TODO:
* [] Add unit tests and/or doctests in docstrings
* [] New/modified features documented in docs/tutorial.rst
> Refactor core tests, round 2

- .github/workflows/python-package.yml
Perhaps this resolves #1472 
TODO:
> expose codecov token in ci

- docs/contributing.rst
cc: @rabernat
Starting a hand-full of versions ago, GitHub added a "Generate release notes" button. This generates links to all PRs as well as to new contributors. I've updated the 2.16.0 release, but I'd be for always clicking this button when making a release.
> Add "Generate release notes" to release process

- docs/release.rst
- pyproject.toml
This use to be a requirement in `setup.py`, but it got lost in the `pyproject.yaml` migration
https://github.com/zarr-developers/zarr-python/blob/d6e35a5641c66bcc668ee1a666086ea04837b9db/setup.py#L28
So readding it here
Also this lines up with [the conda-forge recipe requirement on `setuptools_scm`]( https://github.com/conda-forge/zarr-feedstock/blob/3e4ae21cd8d2e9e909e21ffea8f246b8ad24b50b/recipe/meta.yaml#L24 )
<hr>
TODO:
> Require `setuptools_scm` version `1.5.4`+

- docs/release.rst
- zarr/tests/test_creation.py
- zarr/util.py
This PR will make sure that chunks of an array are created as `tuple[int, ..]`, even if provided as `tuple[float, ...]` (#1461). This is already the case for shape and this PR ensures that the behavior is the same between those two.
I opened this as a draft PR with a failing test to ensure that github actions fail as expected. I will add the fix and push separately. Please feel free to squash as needed upon merge of the PR.
Fixes #1461 
TODO:
> Ensure that chunks is tuple of ints upon array creation

- zarr/hierarchy.py
- zarr/tests/test_meta_array.py
Now `zarr.group` forwards the `meta_array` argument to `zarr.Group`. Fixes #1484.
TODO:
> `zarr.group` now accept the `meta_array` argument

- docs/release.rst
- zarr/_storage/v3.py
- zarr/storage.py
- zarr/tests/test_storage.py
Fixes #1497 by caching `LRUStoreCache.__contains__` calls individually.
Apparently in `ZarrTiffStore`, a successful "contains" check of `key` doesn't necessarily means that `key` is in `ZarrTiffStore.keys()`. 
E.g. if `key` is a string and **not** in `ZarrTiffStore.keys()`, it still might be "contained" by `ZarrTiffStore`, see https://github.com/cgohlke/tifffile/blob/master/tifffile/tifffile.py#L12222
I guess that is why `LRUStoreCache` has both a key and a contains cache?
TODO:
* ~[ ] Add docstrings and API docs for any new/modified user-facing classes and functions~
* ~[ ] New/modified features documented in docs/tutorial.rst~
cc. @cgohlke
> `LRUStoreCache`: cache "contains" by contains checks

- docs/release.rst
This bumps the version number in the docs in anticipation of releasing 2.16.1.  This release will contain 3 PRs:
- #1477
- #1494 
- #1499
> Prepare for 2.16.1 release

- .pre-commit-config.yaml
As observed in the past, pre-commit.ci automatically pushes changes to PRs (even when not requested). This has caused issues in some cases ( https://github.com/zarr-developers/zarr-python/pull/1459 ). This disables automatic pushes by pre-commit in PRs (based on [the `autofix_prs` config parameter]( https://pre-commit.ci/#configuration-autofix_prs )). It is still possible to ask pre-commit to push a changed, but at least in that case it is an option (and not done without a user request)
TODO:
> Disable pre-commit.ci's PR autofixes

- LICENSE.txt
The world's smallest PR :slightly_smiling_face:. All I've done is to change `Copyright (c) 2015-2022` to `Copyright (c) 2015-2023` in `LICENSE.txt`.
> Tiny tweak: Extend copyright notice to 2023

- .pre-commit-config.yaml
- docs/release.rst
This removes the limitation of running `black` via `pre-commit` on Python 3.8. The python version that black is run on doesn't actually affect the output, so this change doesn't make a difference to what black does.
Fixes https://github.com/zarr-developers/zarr-python/issues/1545
TODO:
> Allow black to be run on any Python version

- docs/release.rst
- zarr/tests/test_storage.py
Why use a list literal to initialise a set? Just use a set literal.
It's also consistent with the previous line:
https://github.com/zarr-developers/zarr-python/blob/6ec746ef1242dd9fec26b128cc0b3455d28ad6f0/zarr/tests/test_storage.py#L1167
TODO:
> Unnecessary list literal → set literal

- .gitignore
- docs/conf.py
- docs/spec.rst
- docs/spec/v1.rst
- docs/spec/v2.rst
- docs/spec/v3.rst
Hi everyone! 👋🏻 
I've made minor changes to the documentation. They are as follows:
- Change `Copyright` year; 2022 → 2023
- Currently, the [Specifications](https://zarr.readthedocs.io/en/stable/spec.html) page lists out the whole index of V2 and V1 spec. It looks messy. I changed it to display the titles which, upon clicking, would open the respective specification documents.
- Removed `Under development` from V3 specification.
Please review. Thanks!
CC: @zarr-developers/python-core-devs 
TODO:
> Minor edits in docs

- docs/release.rst
- zarr/core.py
- zarr/tests/test_core.py
When constructing the updated metadata for a resized V2 array, preserve the `dimension_separator` field so it is not reverted to the default after resizing.
Fixes #1533.
TODO:
> Preserve dimension separator metadata when resizing arrays

- docs/release.rst
- zarr/convenience.py
In Python 3, `io.open()` is an alias for the builtin `open()` function:
https://docs.python.org/3/library/io.html#io.open
TODO:
> io.open → open

- docs/conf.py
- docs/release.rst
- docs/tutorial.rst
This adds links through to the `numcodecs` docs where classes are mentioned in the tutorial section of the docs.
TODO:
> Add links to numcodecs docs in tutorial

- .readthedocs.yaml
- docs/Makefile
- docs/conf.py
- docs/index.rst
- docs/release.rst
I noticed that the documentation build allows warnings through - these can include things like broken links, broken RST, or duplicate references. I've enabled the `-W` flag by default in the makefile so these get caught, and fixed the few existing warnings.
TODO:
> Fail doc build on warnings

- .readthedocs.yaml
- docs/index.rst
Fixed #1551.
xref: https://docs.readthedocs.io/en/stable/config-file/v2.html#formats
TODO:
> DOC: Enable offline formats

- .gitignore
- docs/api/core.rst
- docs/conf.py
- pyproject.toml
- zarr/core.py
This PR uses the [automodapi sphinx extension](https://sphinx-automodapi.readthedocs.io/en/latest/#) to automatically document members of the `Array` class. Previously these were manually listed, meaning they have to be manually updated every time the actual method or property is updated in the code. Now they are autogenerated.
Fixes https://github.com/zarr-developers/zarr-python/issues/1546
TODO:
> Automatically document Array members

- docs/contributing.rst
- docs/tutorial.rst
I just wanted to make a very minor suggestion I had while reading through the tutorial (which is very nice, thank you for that!):
In the advanced indexing section, the array used in the 1D examples is `np.arange(10)`. This means that the indices and corresponding values are the same. There's nothing wrong with this of course, but I thought the example might be more immediately grokkable if a different example array were used where the values were different than the indices. I arbitrarily chose `np.arange(10) ** 2`, but any other choice would be equally valid. This is of course a very minor point and pretty subjective, so please feel free to ignore!
I also added two other minor commits that popped up while running through the contributor guide to make the PR:
- I noticed `virtualenv` was …
> DOC: Minor tweak to advanced indexing example in tutorial

- docs/release.rst
- zarr/storage.py
`FSStore._fsspec_installed()` is run in a lot of hierarchy operations, and has a significant runtime overhead for each invocation. Given the result will not change between invocations, cache the very first invocation for subsequent runs.
Example profiling of effects without (`main`) behaviour (6sec total runtime)
and with caching the invocation (2sec total runtime)
Most of the runtime is spent in the repeated lookup of `FSStore._fsspec_installed()`
TODO:
> Cache result of FSStore._fsspec_installed()

- .pre-commit-config.yaml
- bench/compress_normal.py
- zarr/_storage/absstore.py
- zarr/_storage/store.py
- zarr/_storage/v3.py
- zarr/attrs.py
- zarr/convenience.py
- zarr/creation.py
- zarr/hierarchy.py
- zarr/indexing.py
- zarr/meta.py
- zarr/n5.py
- zarr/storage.py
- zarr/tests/test_attrs.py
- zarr/tests/test_convenience.py
- zarr/tests/test_creation.py
- zarr/tests/test_dim_separator.py
- zarr/tests/test_filters.py
- zarr/tests/test_hierarchy.py
- zarr/tests/test_indexing.py
- zarr/tests/test_info.py
- zarr/tests/test_meta.py
- zarr/tests/test_storage.py
- zarr/tests/test_storage_v3.py
- zarr/tests/test_sync.py
- zarr/tests/test_util.py
- zarr/util.py
Pulled out of https://github.com/zarr-developers/zarr-python/pull/1448, and I added the fixes that the new version of `black` makes. Hopefully this makes for slightly easier review than doing all the pre-commit version bumps in one go.
TODO:
> Bump version of black in pre-commit

- zarr/tests/test_indexing.py
Even if this is only a test, list comprehensions are faster than repeatedly call `append()`.
Also use tuple instead of list when possible.
TODO:
> Use list comprehension where applicable

- .pre-commit-config.yaml
- pyproject.toml
Starting with codespell 2.2.2, options can be specified in `pyrpoject.toml` in addition to `setup.cfg`:
https://github.com/codespell-project/codespell#using-a-config-file
Specifying options in a config file instead of command line options in `.pre-commit-config.yaml` ensures codespell uses the same options when run as pre-commit hook or from the command line in the repository root directory.
TODO:
> Move codespell options around

- TEAM.md
Welcoming @normanrz to the core-dev team!
> Add Norman Rzepka to core-dev team

- docs/release.rst
- docs/tutorial.rst
Per discussion here, add information about about accessing zip files on s3: https://github.com/zarr-developers/zarr-python/discussions/1613
TODO:
> Update tutorial.rst to include section about accessing Zip Files on S3

- docs/release.rst
- zarr/_storage/v3_storage_transformers.py
- zarr/meta.py
- zarr/tests/test_attrs.py
- zarr/tests/test_convenience.py
- zarr/tests/test_core.py
- zarr/tests/test_creation.py
- zarr/tests/test_dim_separator.py
- zarr/tests/test_hierarchy.py
- zarr/tests/test_indexing.py
- zarr/tests/test_n5.py
- zarr/tests/test_storage.py
- zarr/tests/test_storage_v3.py
- zarr/tests/test_sync.py
In `main`, `DummyStorageTransformer` is defined in the test suite and imported by `zarr/storage/v3_storage_transformers`. Because the distributed version of `zarr` should not be importing code from the tests, I moved the definition of `DummyStorageTransformer` to `zarr/storage/v3_storage_transformers`, and now the tests that use this class can import it like any other zarr code.
In the test suite, I also changed imports of the form `from zarr.test.module.. import bla` to `from .module import bla`. 
Both of these changes are necessary for moving to a `src/zarr` layout.
xref: #1592
> Don't import from tests

- pyproject.toml
- requirements_dev_numpy.txt
This PR bumps the minimum supported Python and Numpy versions for the V3 branch. These are aligned with Spec0000 (see #1616) assuming we are planning to release in late Q1 or Q2 of 2024. 
Knowing that we are developing against Python 3.10+ will help smooth over some syntax pain, especially when working on [the goal of 100% type hint coverage](https://github.com/zarr-developers/zarr-python/blob/main/v3-roadmap-and-design.md#python-type-hints-and-static-analysis).
TODO:
> [V3] Update minimum supported Python and Numpy versions 

- .github/workflows/python-package.yml
- .github/workflows/releases.yml
- .pre-commit-config.yaml
- .readthedocs.yaml
This skips running mypy on the v3 branch for the moment. This will be a very temporary state as we are hoping for 100% mypy coverage on this branch before we release. 
I'll make a note in #1593 to revert this asap.
> temporarily disable mypy in v3 directory

- src/zarr/v3/codecs/bytes.py
- src/zarr/v3/group.py
- tests/test_group_v3.py
Small follow up to #1634. This fixes the `Group`'s class methods and adds a test. 
I also have been experiencing some pain with attrs with `init=False`. You'll see I disabled a few instances related to this pain. Likely not a big deal since @d-v-b is close to removing attrs.
> fix sync group class methods

- .github/workflows/test-v3.yml
- pyproject.toml
Part of #1648 
The `extras` are packages that should be optional (with import skipping), which could be addressed separately.
The current setup includes 8 combinations (below), would appreciate feedback on this.
```
$ hatch env show --ascii
Standalone                
+---------+---------+----------+---------+
| Name    | Type    | Features | Scripts |
+=========+=========+==========+=========+
| default | virtual |          |         |
+---------+---------+----------+---------+
| docs    | virtual | docs     | build   |
|         |         |          | rtd     |
|         |         |          | serve   |
+---------+---------+----------+---------+
Matrices                                         
+------+---------+---------------------------+----------+----------------+--------------+
| …
```
> Add test matrix for V3

- pyproject.toml
- zarr/sync.py
This patch makes fasteners dependencies conditional on not-emscripten and moves
the fasteners import from top level into the function where it is used. It is the one patch
needed for zarr to work in Pyodide/
> Pyodide support: don't require fasteners on emscripten

- zarr/tests/test_indexing.py
`numpy.reshape` not only accepts a tuple of ints, but also a simple int.
Besides `(10)` is not a tuple and is identical to `10`, unlike `(10,)`.
TODO:
> Proper argument for numpy.reshape

- zarr/_storage/absstore.py
- zarr/_storage/v3.py
- zarr/_storage/v3_storage_transformers.py
- zarr/creation.py
- zarr/storage.py
Not very exciting, but carrys on the typing train. This PR adds typing to wherever a dimension separator argument is used in functions/methods.
TODO:
> Add typing to dimension separator arguments

- LICENSE.txt
- docs/conf.py
- docs/release.rst
Hi all.
This PR updates the `release.rst` to include #1425 and #1641 and prepares for the `2.17.1` release.
TODO:
> Update release.rst for v2.17.1

- docs/tutorial.rst
Fixing link to close https://github.com/zarr-developers/zarr-python/issues/1683
TODO:
> docs(tutorial.rst): fix link to GCSMap

- .github/workflows/python-package.yml
- docs/release.rst
- pyproject.toml
Curious if this works now. Will follow up if CI fails.
TODO:
> Add Python 3.12 to CI

- docs/release.rst
My release notes from #1719 landed in the wrong place. This moves them to the "Unreleased" section.
> Fix release notes (following #1719)

- docs/release.rst
- zarr/hierarchy.py
- zarr/tests/test_hierarchy.py
Closes #1716
This avoids expensive lookups against object stores.
TODO:
> Override ipython repr methods.

- docs/release.rst
- zarr/core.py
- zarr/hierarchy.py
- zarr/util.py
Avoid repeated computes of the same value `getsize`
From 6 getsize requests to 1.
TODO:
> Optimize Array.info and Group.info

- .github/workflows/python-package.yml
- requirements_dev_minimal.txt
An attempt to resolve https://github.com/zarr-developers/zarr-python/pull/1671. The issue was installing the package in non-editable mode creates a copy of the package, and `pytest` gets confused about which of the duplicate files it should be importing. Installing in editable mode fixes this.
TODO:
> Fix tests with Pytest 8

- zarr/hierarchy.py
Let's try grabbing the array.json and group.json files, and check for `*NotFoundError`, instead of using contains first.
TODO:
> Avoid redundant __contains__

- docs/release.rst
- zarr/attrs.py
- zarr/core.py
- zarr/hierarchy.py
Spotted this quick (possible) optimization.
`_load_metadata` (two lines above) has already downloaded the attributes. May as well populate the cache ahead of the time if `cache_attrs is True` (which is the default)
TODO:
> Array & Group: Use already loaded attributes to populate cache.

- docs/release.rst
- zarr/attrs.py
Again remove one `__contains__` and just try to grab the json.
TODO:
> Optimize attribute setting

- docs/release.rst
- zarr/storage.py
- zarr/tests/test_storage.py
**note**: This PR is a copy of PR #1237 which had become stale. Description from @martindurant is:
> (for v2 for now)
> 
> When FSStore gets exceptions, these correctly become the fill value when they are translated to KeyError. However, some exceptions do not equate to missing keys but to other permanent problems such as PermissionError. This change makes sure they are correctly raised to the caller even within getitems (getitem already was correct).
TODO:
* (NA) Add docstrings and API docs for any new/modified user-facing classes and functions
* (NA) New/modified features documented in docs/tutorial.rst
> Make sure fs exceptions are raised if not MissingFs exceptions (clone)

- docs/release.rst
Updates changelog for 2.17.2
closes https://github.com/zarr-developers/zarr-python/issues/1747
> chore(release): update changelog for 2.17.2

- .pre-commit-config.yaml
- src/zarr/v3/abc/metadata.py
- src/zarr/v3/array.py
- src/zarr/v3/chunk_grids.py
- src/zarr/v3/chunk_key_encodings.py
- src/zarr/v3/codecs/transpose.py
- src/zarr/v3/group.py
- src/zarr/v3/metadata.py
- src/zarr/v3/store/core.py
- src/zarr/v3/store/local.py
- src/zarr/v3/sync.py
Attempts to address https://github.com/zarr-developers/zarr-python/issues/1593
There are still two unsolved issues around the nonexistant `Store.from_path` in `core.py`.
TODO:
> Resolve Mypy erorrs in `v3` branch

- docs/release.rst
Add's unreleased section back to our changelog.
> chore(docs): reset release notes as unreleased

- .github/workflows/test-v3.yml
Addresses @jhamman's request from https://github.com/zarr-developers/zarr-python/pull/1656#discussion_r1483310948. Not the cleanest solution, but seems to be the only option until https://github.com/pypa/hatch/issues/858 is resolved.
TODO:
> Specify hatch envs using GitHub actions matrix for v3 tests

- pyproject.toml
This allows `dmypy`, the `mypy` daemon to be run on the v3 branch. In turn this allows the `mypy` plugin to be used in VSCode.
`follow_imports` is not supported by the daemon, but not needed, and `namespace_packages = false` is needed so `mypy` doesn't interpret `src/` as a package.
TODO:
> Allow dmypy to be run on v3 branch

- pyproject.toml
- src/zarr/_storage/store.py
- src/zarr/_storage/v3_storage_transformers.py
- src/zarr/meta.py
- src/zarr/storage.py
- src/zarr/util.py
I'm going to be putting in a few PRs to improve typing in the v3 branch 🕺 
This one removes unused typing ignore comments. (and for good measure adds a couple of other mypy options that didn't require any extra fixes)
TODO:
> Remove unused typing ignore comments

- pyproject.toml
- src/zarr/attrs.py
- src/zarr/n5.py
- src/zarr/v3/sync.py
Part of https://github.com/zarr-developers/zarr-python/issues/1783. This enables the `check_untyped_defs` mypy rule, and makes some of the easiest fixes. For the tricker fixes, I added the files to the a mypy override list, and I think it's easiest if each of these is done in separate PRs so we can enable this rule now (to stop any more violations), but incrementally improve it.
TODO:
> Check untyped defs on v3

- pyproject.toml
No fixes needed for these, but worth enabling them anyway to get closer to enabling `strict=True` in mypy.
> [v3] Enable some more strict mypy options

- src/zarr/v3/store/local.py
implement __eq__ for LocalStore
> implement __eq__ for LocalStore

- docs/release.rst
I've noticed that the release notes for 2.17.2 are incomplete.  Please compare [this](https://github.com/zarr-developers/zarr-python/releases/tag/v2.17.2) and [this](https://zarr.readthedocs.io/en/stable/release.html#release-2-17-2).
This PR completes the release notes for the current release.
TODO:
> Update release.rst for v2.17.2

- docs/release.rst
Small doc update ahead of the pending 2.18 release. 
TODO:
> add note to the top of the release page noting the plan for 2.18.* and 3.0

- docs/api/v3.rst
- docs/release.rst
- zarr/convenience.py
Follow up to #1802 adding warnings to the docs about the pending deprecation of experimental v3 code path.
TODO:
> dep(docs): deprecate experimental v3 support in docs

- pyproject.toml
- src/zarr/common.py
- src/zarr/indexing.py
This tightens up mypy again, disallowing untyped calls. As with other PRs I made some simple fixes, and put the more complex sub-modules in a list to ignore this error which we can fix one at a time in subsequent PRs.
> Disallow untyped calls

- .github/workflows/test.yml
- pyproject.toml
- src/zarr/v2/meta.py
- tests/v2/test_meta.py
closes #1818 
cc @jakirkham 
TODO:
> chore(ci): add numpy 2 release candidate to test matrix

- docs/release.rst
- pyproject.toml
- zarr/_storage/absstore.py
- zarr/_storage/store.py
- zarr/storage.py
This adds a simple deprecation warning to the following stores: 
closes https://github.com/zarr-developers/zarr-python/issues/1756
TODO:
> deprecate(stores): add deprecation warnings to stores that we plan to remove in v3

- docs/release.rst
- zarr/meta.py
- zarr/tests/test_meta.py
This is a small backport of the numpy 2 compatibility changes that came up in #1828. This would be nice to slide into the 2.18 release. 
TODO:
> use np.inf instead of PINF/NINF

- .pre-commit-config.yaml
If/when we start type checking tests, this will be needed to give `mypy` type information from `pytest`. See also https://github.com/zarr-developers/zarr-python/pull/1844#issuecomment-2097462278.
TODO:
> Add pytest to mypy dependencies

- docs/release.rst
- pyproject.toml
- zarr/_storage/absstore.py
- zarr/_storage/v3_storage_transformers.py
- zarr/core.py
- zarr/creation.py
- zarr/hierarchy.py
- zarr/indexing.py
- zarr/meta.py
- zarr/meta_v1.py
- zarr/n5.py
- zarr/storage.py
- zarr/tests/test_meta.py
- zarr/tests/test_storage.py
- zarr/tests/test_storage_v3.py
- zarr/util.py
Start working on https://github.com/zarr-developers/zarr-python/discussions/1701.
TODO:
> Enable ruff/bugbear rules (B) and fix issues

- pyproject.toml
- src/zarr/abc/store.py
- src/zarr/group.py
- src/zarr/store/local.py
- src/zarr/store/memory.py
- src/zarr/testing/__init__.py
- src/zarr/testing/store.py
- src/zarr/v2/storage.py
- tests/v2/test_storage.py
- tests/v3/test_storage.py
This PR peels a few bits off from #1743, primarily focused on moving the output of the store list_* methods to `AsyncGenerators`. 
A few other nice things that ended up here:
- add zarr.testing.store module to support downstream use cases
- set pytest-asyncio mode to auto
> feature(store): list_* -> AsyncGenerators

- src/zarr/codecs/registry.py
- tests/v3/package_with_entrypoint-0.1.dist-info/entry_points.txt
- tests/v3/package_with_entrypoint/__init__.py
- tests/v3/test_codec_entrypoints.py
This PR adds tests for registering codecs via entry point. The test code is copied from numcodecs.
Seems to work 👌 
Contributes to #1748
> Test codec entrypoints

- pyproject.toml
- src/zarr/array.py
> Fix any generics in zarr.array

- pyproject.toml
- src/zarr/common.py
This fixes some untyped functions in `zarr.common`, which in turn fixes most of the untyped calls that now don't have to be ignored in `pyproject.toml`.
TODO:
> Fix some untyped calls

- pyproject.toml
- src/zarr/__init__.py
- src/zarr/codecs/pipeline.py
- src/zarr/common.py
- src/zarr/store/core.py
- src/zarr/store/local.py
- src/zarr/store/memory.py
- src/zarr/store/remote.py
- src/zarr/sync.py
- src/zarr/v2/_storage/absstore.py
- src/zarr/v2/meta.py
- src/zarr/v2/n5.py
- src/zarr/v2/storage.py
- tests/v2/test_storage_v3.py
- tests/v2/test_sync.py
Note: #1867 is the same applied to the [`main`](https://github.com/zarr-developers/zarr-python/tree/main) branch
TODO:
> Enable some ruff rules (RUF) and fix issues

- docs/release.rst
- zarr/core.py
- zarr/indexing.py
- zarr/tests/test_core.py
Fixes a regression in indexing out scalars from size-1 chunks.
TODO:
> Fix a regression with scalar indexing due to #1800

- .github/workflows/test.yml
closes #1788
cc @dstansby and @d-v-b 
TODO:
> chore(ci): remove mypy from test action in favor of pre-commit action

- pyproject.toml
- src/zarr/v2/core.py
- src/zarr/v2/hierarchy.py
- src/zarr/v2/indexing.py
- src/zarr/v2/storage.py
- tests/v2/test_util.py
- tests/v3/conftest.py
- tests/v3/test_group.py
Note: #1866 is the same applied to the [`main`](https://github.com/zarr-developers/zarr-python/tree/main) branch
TODO:
> Enable ruff/flake8-raise rules (RSE) and fix issues

- src/zarr/codecs/sharding.py
- src/zarr/common.py
- src/zarr/v2/meta.py
- tests/v2/test_core.py
Note: #1707 is the same applied to the [`main`](https://github.com/zarr-developers/zarr-python/tree/main) branch
TODO:
> Apply assorted ruff/refurb rules (FURB)

- pyproject.toml
- src/zarr/codecs/crc32c_.py
- src/zarr/codecs/pipeline.py
- src/zarr/codecs/sharding.py
- src/zarr/codecs/transpose.py
- src/zarr/store/remote.py
- src/zarr/v2/convenience.py
- src/zarr/v2/indexing.py
- src/zarr/v2/util.py
Note: #1837 is the same applied to the [`main`](https://github.com/zarr-developers/zarr-python/tree/main) branch
TODO:
> Enable ruff/flake8-implicit-str-concat rules (ISC) and fix issues

- pyproject.toml
These files must have been fixed at some point without the mypy overrides being removed, so remove them.
TODO:
> Remove some unused mypy overrides

- docs/release.rst
- zarr/codecs.py
- zarr/meta.py
- zarr/tests/test_meta.py
This adds `zstd` to the list of codecs supported by the old V3 code path. This is essentially a backport to support existing data that was already written this way.
TODO:
*  ~Add docstrings and API docs for any new/modified user-facing classes and functions~
*  ~New/modified features documented in docs/tutorial.rst~
> Add zstd to old V3 supported codecs

- docs/release.rst
Release notes for a small patch update fixing an issue with the experimental v3 compressor codepath.
TODO:
> doc: update release notes for 2.18.2

- .pre-commit-config.yaml
- pyproject.toml
- src/zarr/codecs/sharding.py
- src/zarr/codecs/zstd.py
- src/zarr/common.py
- src/zarr/config.py
- src/zarr/group.py
- src/zarr/v2/n5.py
- src/zarr/v2/util.py
This enables strict mypy typing, fixing (almost) https://github.com/zarr-developers/zarr-python/issues/1783 🎉 
TODO:
> Make typing strict

- pyproject.toml
- src/zarr/buffer.py
- src/zarr/codecs/sharding.py
- src/zarr/indexing.py
- src/zarr/metadata.py
- src/zarr/testing/store.py
Enable extra mypy error codes. Another part of https://github.com/zarr-developers/zarr-python/issues/1783
TODO:
> Enable extra mypy error codes

- src/zarr/abc/codec.py
- src/zarr/codecs/pipeline.py
- src/zarr/indexing.py
- src/zarr/v2/indexing.py
I think an empty tuple conveys "drop no axes" as effectively as `None`, with less code.
> narrow the type of drop_axes to just tuple[int, ...]

- pyproject.toml
- src/zarr/codecs/_v2.py
- src/zarr/codecs/blosc.py
- src/zarr/store/local.py
- src/zarr/store/memory.py
One of the last parts of https://github.com/zarr-developers/zarr-python/issues/1783, a few simple fixes and the ignores I put in because it looks like those code paths will go when v2 is completely gone anyway?
TODO:
> Enable warn_unreachable for mypy

- .readthedocs.yaml
- pyproject.toml
In https://github.com/zarr-developers/zarr-python/pull/1918 I noticed that errors on the doc build are not failing the readthedocs build. This is because sphinx runs `hatch run docs:rtd`, which in turn runs `sphinx-build` with no options, which does not fail on warnings.
Instead I think it's better to let readthedocs manage calling sphinx itself, and manage dependencies itself too for caching reasons. This allows it to use the configuration options that we define in the `Makefile`, which is the only way to configure sphinx to error on warnings.
I also updated the `hatch run docs:build` script to use `make html`, so it also catches sphinx warnings and turn them into errors.
TODO:
> Run sphinx directly on readthedocs

- .pre-commit-config.yaml
- pyproject.toml
This makes sure the list of dependencies in the mypy pre-commit environment mirrors the dependencies of the package (+ any dependencies needed for tests). I also had to make a small fix in `zstd`, which I think is correct?
TODO:
> Fix list of packages in mypy pre-commit environment

- pyproject.toml
- src/zarr/array.py
- src/zarr/metadata.py
- src/zarr/store/remote.py
This should fix the final typing errors. Fixes https://github.com/zarr-developers/zarr-python/issues/1783
> Fix final typing errors

- src/zarr/codecs/__init__.py
- tests/v3/test_group.py
- tests/v3/test_sync.py
Fix issues reported by `ruff check --preview`.
I have no experience using [`asyncio`](https://docs.python.org/3/library/asyncio.html), so I am not confident in the [`RUF029`](https://docs.astral.sh/ruff/rules/unused-async/) fixes.
TODO:
> Apply preview ruff rules

- pyproject.toml
- src/zarr/metadata.py
I feel the modified code is consistent with the `ArrayV3Metadata` dataclass:
https://github.com/zarr-developers/zarr-python/blob/19365e20522e5d67b0b14698a7c6c953c450c5c6/src/zarr/metadata.py#L167
TODO:
> Enable and apply ruff rule RUF009

- src/zarr/array.py
- src/zarr/group.py
- tests/v3/test_array.py
- tests/v3/test_group.py
> Feature: group and array name properties

- docs/release.rst
This PR prepares the doc build for the 3.0.0.alpha release.
> doc: update release notes for 3.0.0.alpha

- src/zarr/config.py
- src/zarr/group.py
- src/zarr/metadata.py
- tests/v3/test_config.py
Level of JSON indentation is set by by the global config object.
resolves #704 
TODO:
> [v3] add json indentation to config

- pyproject.toml
- src/zarr/store/remote.py
- tests/v3/test_store/test_remote.py
This PR changes the `.__str__` method of `RemoteStore` to make it similar to `LocalStore` and `MemoryStore` (i.e., `RemoteStore("s3://path").__str__` returns `s3://path`). 
~I also add tests for UPath, and tweaked the test suite accordingly. The tests are failing, and I don't know why. @martindurant could you take a look if you have time?~ edit: tests are passing
TODO:
> Update `RemoteStore.__str__` and add UPath tests

- src/zarr/indexing.py
- src/zarr/v2/context.py
- src/zarr/v2/indexing.py
Also fixes a `mypy` error, not sure why it's showing up here..
> Fix doc build warnings

- src/zarr/api/asynchronous.py
- tests/v3/test_api.py
This is a compatibility fix for v3.
It should fix #1965 - although I haven't tested it directly.
TODO:
> Allow 'chunks' as an alias for 'chunk_shape' in array creation

- src/zarr/v2/hierarchy.py
> Use f-strings instead of legacy interpolation

- src/zarr/store/remote.py
Fix typo in legacy string interpolation (`,` instead of `%`) by replacing with f-string.
TODO:
> Fix string interpolation

- .github/workflows/test.yml
- pyproject.toml
Now that NumPy 2.0 is out, we should be testing against the latest version.
TODO:
> Bump NumPy to 2.0

- .github/workflows/test.yml
I left this out of #1983 due to an unrelated failure. That has since been corrected so we're good to go here now.
TODO:
> build(ci): enable python 3.12 in github actions

- docs/release.rst
This catches our change log up with 3.0.0.alpha... @MSanKeys963, would you be up for helping format this?
closes #1769 
TODO:
> doc: copy 3.0.0.alpha changelog into release.rst

- src/zarr/codecs/transpose.py
- src/zarr/group.py
- src/zarr/store/remote.py
- tests/v2/test_indexing.py
- tests/v2/test_storage.py
- tests/v2/test_sync.py
Avoid importing the same module multiple times.
TODO:
> Multiple imports for an import name

- src/zarr/abc/metadata.py
- src/zarr/chunk_grids.py
- src/zarr/chunk_key_encodings.py
- src/zarr/metadata.py
- tests/v3/test_metadata/test_v2.py
- tests/v3/test_metadata/test_v3.py
- handle creating v3 metadata from a dict without an `attributes` key (`attributes` will be set to `None` in the resulting metadata document).
- handle null entries in `dimension_names` correctly at validation
- ensure that collection types become `tuple` during metadata serialization
- make a copy of the input dict in `from_dict` method of array v3 metadata, to avoid mutating the input dict
- allow creating `ChunkKeyEncoding` from dicts without `configuration`, because it's optional.
- add a test case that revealed the problems fixed by all of the above changes.
closes #2024 
TODO:
> Handle missing attributes key from metadata, and other fixes

- pyproject.toml
(note: pending some discussion at https://github.com/zarr-developers/zarr-python/issues/2068#issuecomment-2274067546 on the desired behavior w.r.t `zarr.testing.StoreTests`)
- removed pytest as a required dep
- move test hatch env dep to a "test" optional dependency and include as a feature
Here's the output of `hatch env run -e test.py3.10-1.24-minimal pip list`
```
Package            Version
------------------ -----------
aiobotocore        2.13.1
aiohappyeyeballs   2.3.5
aiohttp            3.10.1
aioitertools       0.11.0
aiosignal          1.3.1
asciitree          0.3.3
async-timeout      4.0.3
attrs              24.2.0
blinker            1.8.2
boto3              1.34.131
botocore           1.34.131
certifi            2024.7.4
cffi               1.17.0
charset-normalizer 3.3.2
click …
```
> Updated test dependencies in pyproject.toml

- pyproject.toml
- src/zarr/api/asynchronous.py
- src/zarr/array.py
- src/zarr/codecs/pipeline.py
- src/zarr/codecs/sharding.py
- src/zarr/group.py
- src/zarr/store/core.py
- src/zarr/store/local.py
- src/zarr/store/remote.py
- tests/v3/test_codecs/test_codecs.py
Ignore [`TRY003`](https://docs.astral.sh/ruff/rules/raise-vanilla-args/) for now. I don't like it in this context.
TODO:
> Enforce ruff/tryceratops rules (TRY)

- pyproject.toml
- zarr/core.py
- zarr/creation.py
This fixes doctests to run with numpy 2.0, and skips them if numpy is < 2. This isn't a very elegant solution to these values changing with a new version of numpy, but I think it's a pragmatic solution to getting CI working again for v2.
> [v2] Fix doctests with numpy 2.0

- docs/release.rst
- zarr/core.py
- zarr/tests/test_core.py
> Fix orthogonal indexing with a scalar

- .github/dependabot.yml
Fixes https://github.com/zarr-developers/zarr-python/issues/2045. I don't think there's a way to test this before merging it?
TODO:
> Re-enable dependabot on main branch

- docs/release.rst
- zarr/core.py
This updates __array__ for numpy 2.1, specifically by implementing the copy keyword argument.
The one test failure is an issue with a new version of numcodecs (0.13.0) which is a simple fix, but easier to make when we bump the numocdecs version in the test dependencies, so I'd advocate for merging this PR and dealing with the numcodecs bump in a follow up PR.
TODO:
> Fix Array.__array__ for numpy 2.1

- requirements_dev_minimal.txt
- zarr/tests/test_meta.py
This bumps the test version of numcodecs to 0.13.0, and fixes a test where the output changed with 0.13.0. Along the way I made the test a bit simpler to avoid having to deal with multi-line strings.
TODO:
> Bump test version of numcodecs

- zarr/core.py
This PR slightly modifies #2106 to allow for any args/kwargs to be passed to `__array__`.  Without this, earlier versions of NumPy error with the following traceback:
```
def __array__(self, dtype=None, copy=None):
>       return np.array(self[...], dtype=dtype, copy=copy)
E       ValueError: NoneType copy mode not allowed.
```
@dstansby - mind giving this a look
TODO:
> fix: numpy 1.24 compat for Array.__array__

- src/zarr/store/memory.py
- src/zarr/store/remote.py
- src/zarr/testing/store.py
Ensures that nested children are listed properly.
Closes #2116
> Fixed MemoryStore.list_dir

- .github/workflows/python-package.yml
https://github.com/zarr-developers/zarr-python/pull/2123 fixed a bug that was introduced with an older version of numpy. This puts back numpy 1.23 in the test matrix on GitHub actions to catch stuff like this in the future.
I think this was previously enabled, but accidentally lost when Python 3.9 support was dropped.
> Run tests on numpy 1.23

- .github/workflows/python-package.yml
- docs/release.rst
- pyproject.toml
Updates minimum numpy version to 1.24.
TODO:
> chore: bump minimum numpy version to 1.24

- .github/workflows/python-package.yml
- .github/workflows/windows-testing.yml
These are either installed elsewhere (from a dependencies file), or not required for the tests. Should speed up v2 CI a little bit 🚀 
TODO:
> Remove un-needed package installs in CI

- src/zarr/core/metadata.py
Fixes part of https://github.com/zarr-developers/zarr-python/issues/2131. `UByteDType` is a type alias for `UInt8DType`, so fine to change it and it's now recognised as a proper type.
> Fix dtype type error

- .pre-commit-config.yaml
- src/zarr/codecs/crc32c_.py
- src/zarr/codecs/sharding.py
- src/zarr/core/metadata.py
This includes some fixes to get mypy type checks passing.
Closes https://github.com/zarr-developers/zarr-python/issues/2131
> mypy fixes for NumPy 2.1.0

- src/zarr/core/group.py
- tests/v3/test_group.py
Standardizes on `name` as the first arg to `Array.create`. 
closes https://github.com/zarr-developers/zarr-python/issues/2112
TODO:
> [v3] clean up `create_array` signatures in group/asyncgroup classes

- src/zarr/core/common.py
- src/zarr/core/group.py
- tests/v3/test_group.py
This PR adds the h5py compat methods to the Zarr Group API from v2. 
The plan described in #1583 was to remove these but after looking into it, a bit more, I came to the conclusion that `require_group` and `require_dataset` are actually pretty useful. I'm open to adding deprecation warnings to `create_dataset` and `require_dataset` (perhaps replacing the latter with `require_array`) if we want to phase out the h5py specific language. 
closes #1597
TODO:
> [v3] h5py compat methods on Group

- .pre-commit-config.yaml
- pyproject.toml
https://learn.scientific-python.org/development/guides/repo-review/?repo=zarr-developers%2Fzarr-python&branch=v3
TODO:
> Enforce Repo-Review rules

- .pre-commit-config.yaml
- pyproject.toml
Fixes some kwarg typing, and adds `universal-pathlib` to the type checking and as a package dependency.
> Add UPath dependency/type checking

- tests/v3/test_buffer.py
TCH003 Move standard library import into a type-checking block
TODO:
> Fix new ruff/flake8-type-checking TCH003 error

- .gitignore
- docs/Makefile
- docs/api/index.rst
- docs/api/zarr.rst
- docs/conf.py
- pyproject.toml
- src/zarr/codecs/blosc.py
- src/zarr/codecs/bytes.py
- src/zarr/codecs/sharding.py
- src/zarr/core/array.py
- src/zarr/core/buffer/core.py
- src/zarr/core/indexing.py
- src/zarr/testing/strategies.py
- src/zarr/v2/indexing.py
- src/zarr/v2/meta.py
- src/zarr/v2/n5.py
This updates the doc build to automatically generate all API docs. I've set it so any module with a part that starts with "_" is not documented, so that's the way to make a sub-module private.
See https://zarr--2002.org.readthedocs.build/en/2002/_autoapi/zarr/index.html for the API ref in the build of this PR. 
I think it's worth merging this to make sure new additions/removals to the API don't break API docs, and we can bikeshed what's in/out of the public API in a follow up PR.
Fixes https://github.com/zarr-developers/zarr-python/issues/1993.
> Autogenerate all API docs

- src/zarr/store/memory.py
- tests/v3/test_store/test_memory.py
The `store_dict or {}` is Falsey for empty dicts, so the user provided dict wasn't being used.
TODO:
> Ensure that store_dict used for empty dicts

- docs/conf.py
pydata-sphinx-theme has a dual-sidebar system that makes some pretty specific assumptions about the structure of docs to work well, but has some odd behaviors otherwise. This PR makes the tutorial page look a little tidier.
Currently on the tutorial page, the primary sidebar is totally empty. on wide screens, this is sort of a curiosity, but it becomes a nuisance on narrower screens. More than anything is just looks weird and unfinished (not your fault, byproduct of the theme)
Wider than medium breakpoint:
Below medium breakpoint:
Thankfully pydata-sphinx-theme also gives us nice control over the sidebars! Simply removing the primary sidebar makes it look tidier and uses screen space better.
Wider than medium breakpoint:
Below medium breakpoint:
Another option is to move the page toc to …
> [docs] remove primary sidebar from tutorial

- src/zarr/api/asynchronous.py
- src/zarr/testing/store.py
The `path` component was included twice when calling `create` from `open_array`, once in `store_path` and once in `path`.
The new test confirms that users can create an array at a given path and then read it at that same path.
Closes https://github.com/zarr-developers/zarr-python/issues/2166
TODO:
> Fixed path segment duplication in open_array

- .pre-commit-config.yaml
- pyproject.toml
- tests/v3/conftest.py
- tests/v3/test_codec_entrypoints.py
- tests/v3/test_common.py
- tests/v3/test_config.py
- tests/v3/test_group.py
- tests/v3/test_indexing.py
- tests/v3/test_metadata/test_v3.py
- tests/v3/test_properties.py
- tests/v3/test_store/test_core.py
- tests/v3/test_store/test_remote.py
- tests/v3/test_store/test_stateful_store.py
- tests/v3/test_sync.py
- tests/v3/test_v2.py
This builds on https://github.com/zarr-developers/zarr-python/pull/2150 (cc @TomAugspurger) to:
- move the config for mypy type checking tests from `pre-commit-config.yaml` to `pyproject.toml`, so `mypy` run outside of `pre-commit` also picks up the config.
- Add an explicit list of tests to ignore errors for (which we can fix one by one)
- Make some low hanging typing fixes to the tests
TODO:
> Simplify mypy config for tests

- src/zarr/api/asynchronous.py
- src/zarr/core/buffer/core.py
- src/zarr/core/buffer/cpu.py
- src/zarr/core/buffer/gpu.py
- src/zarr/store/common.py
- tests/v3/test_group.py
This updates how we handle a plain dictionary provided to `open_group` and friends so that the following works:
`group = await zarr.api.asynchronous.open_group(store={}, mode="w")`
The dictionary is interpreted as the `store_dict` argument of `zarr.store.MemoryStore`. This effectively mirrors the behavior of zarr-python v2, and I think doesn't introduce an ambiguity. Previously a TypeError was raised.
This change will make it slightly easier to get xarray's test suite running with zarr v3.
TODO:
> Accept dictionaries for `store` argument

- src/zarr/api/asynchronous.py
- src/zarr/core/config.py
- tests/v3/test_api.py
- tests/v3/test_config.py
> fix: opening a group with unspecified format finds either v2 or v3

- tests/v3/test_group.py
- tests/v3/test_store/test_memory.py
An automated merge conflict resolution went awry in #2006, leading to a number of tests being inadvertently removed. This PR brings them back to the v3 branch.
Thanks @TomAugspurger for catching these!
TODO:
> fix: replace tests that went missing in #2006

- src/zarr/abc/codec.py
- src/zarr/abc/metadata.py
- src/zarr/codecs/_v2.py
- src/zarr/codecs/blosc.py
- src/zarr/codecs/bytes.py
- src/zarr/codecs/pipeline.py
- src/zarr/codecs/sharding.py
- src/zarr/codecs/transpose.py
- src/zarr/core/array.py
- src/zarr/core/common.py
- src/zarr/core/metadata/v2.py
- src/zarr/core/metadata/v3.py
- tests/v3/test_metadata/test_v2.py
A typing / metadata cleanup now that #2163 is in.
In `v3`, the JSON type looks like this:
`JSON = None | str | int | float | Enum | dict[str, "JSON"] | list["JSON"] | tuple["JSON", ...]`
I narrowed this type to
`JSON = None | str | int | float | Mapping[str, "JSON"] | tuple["JSON", ...]`
- I don't think we need to support `list` AND `tuple`; as `tuple` is immutable, I got rid of the `list` variant. 
- I switched `dict[str, JSON]` to `Mapping[str, JSON]` out of the same preference for immutability.
- Allowing `Enum` is a back door around type safety, so I removed it; instead of serializing enums, the relevant classes serialize the enum values. Maybe we could put `Enum` back in `JSON` if there's a way to tell the type checker that our enums only wrap JSON values. 
Along with narrowing the …
> Narrow JSON type, ensure that `to_dict` always returns a dict, and v2 filter / compressor parsing  

- src/zarr/core/array.py
Quick fix for the issue causing CI to fail. xref https://github.com/zarr-developers/zarr-python/pull/2179/files#r1765600769
Right now `ChunkSpec.fill_value` is `Any`, so mypy doesn't have a chance to catch this. I think we have a requirement that the type of `fill_value` somehow match / be compatible with the `dtype`. I don't know if we can do that yet, but we can address it once CI is passing again.
> Fixed codec for v2 data with no fill value

- src/zarr/api/asynchronous.py
- src/zarr/core/group.py
- tests/v3/test_group.py
This PR implements `Group.{empty,zeros,ones,full,empty_like, zeros_like,onest_like,full_like}` for V3. Here we simply call the top-level functions from `zarr.api.asynchronous` to accomplish this. 
Closes #2125 
TODO:
> [v3] Implement Group methods for empty, full, ones, and zeros

- src/zarr/store/memory.py
- tests/v3/test_store/test_memory.py
See https://github.com/zarr-developers/zarr-python/pull/2006#discussion_r1765275948l for motivation.
> Make MemoryStore serializable

- tests/v3/test_indexing.py
This fixes a lot of the typing issues in test_indexing. It doesn't fix all of them, because I think the remaining ones will need typing additions/fixes in the actual library, but this is a good start in reducing the volume of errors.
TODO:
> Typing fixes for test_indexing

- src/zarr/core/group.py
- tests/v3/test_group.py
Defines a set of array / group iterators.
- .groups / .arrays: over (name, value) pairs
- .group_keys / .array_keys: over keys
- .group_values / .array_values: over values
Closes #2212
> Make Group.arrays, groups compatible with v2

- src/zarr/testing/store.py
> fix typo in store integration test

- src/zarr/core/attributes.py
- tests/v3/test_attributes.py
Restores Attributes.asdict, for zarr v2 compatibility.
xref #2214, which has some open questions about Group.attrs vs. AsyncGroup.attrs.
TODO:
> Added Attributes.asdict

- pyproject.toml
- src/zarr/abc/store.py
- src/zarr/api/asynchronous.py
- src/zarr/codecs/transpose.py
- src/zarr/core/array.py
- src/zarr/core/attributes.py
- src/zarr/core/buffer/core.py
- src/zarr/core/buffer/cpu.py
- src/zarr/core/buffer/gpu.py
- src/zarr/core/group.py
- src/zarr/core/indexing.py
- src/zarr/core/metadata/v3.py
- src/zarr/core/sync.py
- src/zarr/registry.py
- src/zarr/store/common.py
- src/zarr/store/local.py
- src/zarr/store/memory.py
- src/zarr/store/remote.py
- src/zarr/testing/strategies.py
- tests/v3/conftest.py
- tests/v3/test_array.py
- tests/v3/test_group.py
- tests/v3/test_indexing.py
- tests/v3/test_metadata/test_v3.py
- tests/v3/test_properties.py
- tests/v3/test_store/test_remote.py
- tests/v3/test_store/test_stateful_store.py
- tests/v3/test_v2.py
* Apply [`PERF401`](https://docs.astral.sh/ruff/rules/manual-list-comprehension/), but do not enforce for now - see https://github.com/pypa/setuptools/pull/4449#issuecomment-2239482683 and https://github.com/numpy/numpy/pull/26876#issuecomment-2223009885 and make your own opinion :smile:
* Apply [`PT022`](https://docs.astral.sh/ruff/rules/pytest-useless-yield-fixture/). Do not enforce for now, I fear you won't like other [`PT`](https://docs.astral.sh/ruff/rules/#flake8-pytest-style-pt) rules.
* ~~Enforce [`TCH`](https://docs.astral.sh/ruff/rules/#flake8-type-checking-tch) rules.~~
* Enforce [`PGH`](https://docs.astral.sh/ruff/rules/#pygrep-hooks-pgh) rules.
* Apply [`C405`](https://docs.astral.sh/ruff/rules/unnecessary-literal-set/) and …
> Apply and enforce more ruff rules

- src/zarr/codecs/_v2.py
- src/zarr/core/metadata/v2.py
- tests/v3/test_v2.py
Closes #2243 
The previous implementation used the codec config, rather than the codec itself. In memory, ArrayV2Metadata has the concrete codec, so we'll just use that.
cc @normanrz.
> Update V2 codec pipeline to use concrete classes

- pyproject.toml
- src/zarr/core/group.py
- src/zarr/store/remote.py
> Enforce ruff/flynt rules (FLY)

- pyproject.toml
- src/zarr/abc/store.py
- src/zarr/core/buffer/core.py
- tests/v3/conftest.py
- tests/v3/test_store/test_stateful_store.py
> Enforce ruff/flake8-return rules (RET)

- src/zarr/core/array.py
- src/zarr/store/memory.py
- tests/v3/test_store/test_remote.py
> Fix multiple identical imports

- pyproject.toml
- src/zarr/testing/store.py
- tests/v3/conftest.py
- tests/v3/test_array.py
- tests/v3/test_chunk_grids.py
- tests/v3/test_codec_entrypoints.py
- tests/v3/test_codecs/test_blosc.py
- tests/v3/test_codecs/test_codecs.py
- tests/v3/test_codecs/test_endian.py
- tests/v3/test_codecs/test_gzip.py
- tests/v3/test_codecs/test_sharding.py
- tests/v3/test_codecs/test_transpose.py
- tests/v3/test_codecs/test_zstd.py
- tests/v3/test_config.py
- tests/v3/test_group.py
- tests/v3/test_indexing.py
- tests/v3/test_metadata/test_v3.py
- tests/v3/test_store/test_memory.py
- tests/v3/test_store/test_remote.py
- tests/v3/test_store/test_zip.py
> Enforce ruff/flake8-pytest-style rules (PT)

- .github/ISSUE_TEMPLATE/config.yml
Replace Gitter link with ZulipChat.
TODO:
> Replace Gitter link with Zulip

- tests/v3/test_indexing.py
Slight simplification of logic in `test_accessed_chunks`
TODO:
> Use `map(str, *)` in `test_accessed_chunks`

- bench/compress_normal.py
- pyproject.toml
- src/zarr/codecs/sharding.py
- src/zarr/store/memory.py
- src/zarr/store/zip.py
- tests/v3/test_group.py
- tests/v3/test_store/test_remote.py
> Enforce ruff/flake8-comprehensions rules (C4)

- .deepsource.toml
Get rid of `.deepsource.toml`.
TODO:
> No need to run DeepSource any more - we use ruff

- src/zarr/core/metadata/v2.py
- src/zarr/core/metadata/v3.py
- src/zarr/store/zip.py
ANN204 Missing return type annotation for special method `__init__`
TODO:
> Apply ruff/flake8-annotations rule ANN204

- src/zarr/core/indexing.py
- src/zarr/store/zip.py
- src/zarr/testing/store.py
> Apply assorted ruff/flake8-simplify rules (SIM)

- src/zarr/core/config.py
- tests/v3/test_config.py
Unbounded concurrency is not a good idea. This sets the default to 10. 
TODO:
> fix(async): set default concurrency to 10 tasks

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/documentation.yml
Added a new issue template for documentation-related issues. Looks something like:
Please review. Thanks!
TODO:
> Added a new issue template for documentation issues

- docs/_static/custom.css
Fixes https://github.com/zarr-developers/zarr-python/issues/2285. In general hard coding colours is a bad idea. I think these should just be deleted, but if we want to customize anything like this it's best to use the variables available in pydata-sphinx-theme: https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/styling.html#css-theme-variables
> Fix low contrast box titles

- src/zarr/core/group.py
- src/zarr/core/metadata/v2.py
- tests/v3/test_array.py
- tests/v3/test_group.py
- tests/v3/test_metadata/test_v2.py
Ignore unexpected keys in Zarr V2 metadata, to enable reading zarr files written by other systems, which might store additional data in the top level of the `.zgroup` and `.zarray` files`
Closes https://github.com/zarr-developers/zarr-python/issues/2296
> Ignore extra keys in v2 metadata

- docs/conf.py
Fixes (partially) https://github.com/zarr-developers/zarr-python/issues/2294. Here's an example with this change:
> Add maximum character length for signatures in docs

- src/zarr/core/metadata/v3.py
- tests/v3/test_metadata/test_v3.py
In working on #2036, I realized that the current treatment of the `data_type` attribute in V3 metadata was somewhat inconsistent. This class is meant to represent the Zarr metadata in an abstract way, in alignment with the spec. However, it was just using numpy dtypes internally.
This becomes a problem when we want to support dtypes that are not numpy dtypes, like `string`.
This PR changes the `ArrayV3Metadata` class such that the type of `data_type` is the existing `DataType`  enum. However, I've kept the `.dtype` property returning a numpy dtype. This allows this change to be minimally disruptive to other parts of the code.
> Change ArrayV3Metadata.data_type to DataType

- src/zarr/abc/codec.py
This renames `_Codec` to `CodecBase`, so that it gets documented and linked from e.g. [`ArrayArrayCodec`](https://zarr.readthedocs.io/en/v3/_autoapi/zarr/abc/codec/index.html#zarr.abc.codec.ArrayArrayCodec), which is currently missing a link to it.
I think in general it's nicer to document the full class heirarchy, but put warnings where we don't expect users to use specific classes. This fixes some broken links, a small part of https://github.com/zarr-developers/zarr-python/pull/2291
> Add BaseCodec to the docs

- src/zarr/core/group.py
- tests/v3/test_group.py
This changes the `prototype` keyword to `data` in the `Group.foo_like` methods, matching the keyword name in 2.x. 
Supports https://github.com/dask/dask/pull/11388, followup to https://github.com/zarr-developers/zarr-python/pull/2210
TODO:
> fix: array creation prototype

- .github/workflows/releases.yml
- src/zarr/core/group.py
- tests/v3/test_group.py
Some downstream applications (xarray.DataTree) were using `Group.get`. This PR adds that to the Group API for backward compatibility.  
TODO:
> fix: add get(key, default) method to Group APIs

- src/zarr/testing/store.py
- tests/v3/test_store/test_local.py
- tests/v3/test_store/test_memory.py
- tests/v3/test_store/test_remote.py
- tests/v3/test_store/test_zip.py
Small change that supports storage backends that don't have a synchronous interface
TODO:
> fix(storage): change StoreTests get/set methods to async

- src/zarr/abc/store.py
- src/zarr/testing/store.py
- tests/v3/test_store/test_zip.py
We were calling `store.empty` and `store.clear` more than we needed to. This changes the open logic to only call `clear` when `mode='w'` and only call `empty` when `mode='w-'`. 
TODO:
> fix(store): speed up Store.open by avoiding empty/clear calls unless needed

- src/zarr/abc/store.py
On defining a keyword argument before variable positional arguments, one can end up in having multiple values passed for the aforementioned parameter in case the method is called with keyword arguments. It is recommended to define keyword arguments after variable positional arguments.
TODO:
> Keyword argument defined before variable positional arguments

- src/zarr/core/indexing.py
Variable is being assigned to itself. It is unnecessary to assign a variable to itself without any modification.
TODO:
> Assigning the same variable to itself

- src/zarr/testing/strategies.py
A lambda that calls a function without modifying any of its parameters is unnecessary. Python functions are first-class objects and can be passed around in the same way as the resulting lambda. It is recommended to remove the lambda and use the function directly.
TODO:
> Unnecessary lambda expression

- .pre-commit-config.yaml
- pyproject.toml
- src/zarr/api/asynchronous.py
- src/zarr/core/array.py
- src/zarr/core/group.py
- src/zarr/storage/zip.py
I started reviewing one of the docstring pull requests, and found it quite tricky to review large PRs where the contents have to be consistent with function/class signatures.
This PR implements some [numpydoc validation checks](https://numpydoc.readthedocs.io/en/latest/validation.html) to give some more consistent validation fo docstrings. To keep this PR simple I've only included a few error codes and fixes, but I'm happy to roll this out to other error codes if folks are pro adding this validation.
> Add some numpydoc validation checks

- src/zarr/codecs/_v2.py
- src/zarr/codecs/blosc.py
- src/zarr/codecs/gzip.py
- src/zarr/codecs/zstd.py
- src/zarr/core/common.py
- src/zarr/core/config.py
- src/zarr/core/sync.py
- src/zarr/storage/local.py
- tests/v3/test_config.py
- tests/v3/test_sync.py
Previously, Zarr was using a home rolled `to_thread` function to offload work to an implicit executor. This PR changes this in three main ways:
1. Use `asyncio.to_thread` instead of the home rolled version
2. Setup a configurable `ThreadPoolExecutor` alongside the IOthread and IOloop. The number of threads can be configured using `threading.max_workers`.
3. Provide a teardown function (`zarr.core.sync.cleanup_resources`) to explicitly cleanup resources created by Zarr at runtime. This function is executed at shutdown (via `atexit`) and can also be triggered manually (e.g. in the dask test suite)
TODO:
> feature(threading): use explicit/configurable thread pool executor

- src/zarr/core/array.py
- tests/v3/test_array.py
- tests/v3/test_group.py
Closes #2328 
This now follows the same update logic used in the `AsyncGroup` class.
TODO:
> fix(attrs): update array attrs in place

- src/zarr/storage/local.py
- tests/v3/test_store/test_local.py
Closes https://github.com/zarr-developers/zarr-python/issues/2334
> Ensure path created for LocalStore when not in readonly mode.

- src/zarr/storage/remote.py
- tests/v3/test_store/test_remote.py
> fix RemoteStore.empty

- .github/workflows/minimal.yml
- .github/workflows/python-package.yml
- .github/workflows/windows-testing.yml
Run's CI on support branch. Wait to merge until after #2345 is settled.
TODO:
> ci: run test actions on support branch

- src/zarr/core/group.py
- tests/v3/test_group.py
Small patch on the back of #1161. 
Without this change, the logic in `members` was identifying `.zmetadata` as a valid key in the store and looking for its children (e.g. `foo/.zmetadata/.zarray`). The result was a bunch of noisy warnings about unrecognized keys.
TODO:
> fix(consolidated metadata): skip .zmetadata key in members search

- .pre-commit-config.yaml
Fix this [pre-commit.ci warning](https://results.pre-commit.ci/run/github/48049137/1728839294.EoOsgWOISUunzcKMy5la9A):
```
[WARNING] top-level `default_stages` uses deprecated stage names (commit, push) which will be removed in a future version.  run: `pre-commit migrate-config` to automatically fix this.
```
TODO:
> Update deprecated stage names

- docs/_static/custom.css
> Fix logo height in doc navbar

- pyproject.toml
- src/zarr/core/sync.py
- src/zarr/storage/logging.py
> Use lazy % formatting in logging functions

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/workflows/python-package.yml
- .github/workflows/windows-testing.yml
- docs/release.rst
- docs/tutorial.rst
- pyproject.toml
- zarr/storage.py
As per SPEC 0 we can drop Python 3.10, and this also adds tests for Python 3.13. Fixes https://github.com/zarr-developers/zarr-python/issues/2317
> Add Python 3.13, drop Python 3.10

- docs/conf.py
- tests/v3/test_array.py
- tests/v3/test_v2.py
> Imported name is not used anywhere in the module

- pyproject.toml
- src/zarr/abc/codec.py
PYI013 Non-empty class body must not contain `...`
Note that documentation is enough to fill the class body.
TODO:
> Enforce ruff/flake8-pyi rule PYI013

- .pre-commit-config.yaml
- pyproject.toml
This is no longer used in Zarr and can be safely removed.
TODO:
> deps: remove fasteners from list of dependencies

- pyproject.toml
- src/zarr/abc/store.py
- src/zarr/core/array.py
- src/zarr/core/chunk_grids.py
- src/zarr/core/common.py
- src/zarr/core/indexing.py
- src/zarr/storage/memory.py
- src/zarr/storage/zip.py
- tests/test_group.py
> Enforce ruff/refurb rules (FURB)

- src/zarr/core/group.py
- tests/test_group.py
Fixes #2402
Thanks @TomAugspurger for adding `_deprecate_positional_args`!
TODO:
> fix(group): deprecate positional args in Group.{zeros,ones,etc.}

- src/zarr/core/metadata/v3.py
- tests/test_array.py
We were not replacing NaNs and Infs with the string versions.
TODO:
> Fix JSON encoding of complex fill values

- .github/workflows/gpu_test.yml
- .github/workflows/hypothesis.yaml
- .github/workflows/test.yml
- .pre-commit-config.yaml
- pyproject.toml
- src/zarr/storage/local.py
- tests/test_sync.py
This PR adds CI matrix entries for OSX and Windows. 
Closes #1648 
Notes:
There are some interesting failures here.
~- [ ] path handling in local store~
> test(ci): test on windows and osx

- src/zarr/core/array.py
- tests/test_array.py
This changes the API of AysncArray.nchunks_initialized to change it from a property to an async function. The motivation here comes from
1. general cleanliness (a property access calling async functions doing I/O feels a bit wrong)
2. Work on Array.info (#2400 ), where I hit a strange error:
<details>
```python
File "/Users/tom/gh/zarr-developers/zarr-python/src/zarr/core/array.py", line 3011, in info_complete
return sync(self._async_array.info_complete())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/tom/gh/zarr-developers/zarr-python/src/zarr/core/sync.py", line 141, in sync
raise return_result
File "/Users/tom/gh/zarr-developers/zarr-python/src/zarr/core/sync.py", line 100, in _runner
return await coro
^^^^^^^^^^
File "/Users/tom/gh/zarr-developers/zarr-python/src/zarr/core/array …
```
> Make AsyncArray.nchunks_initialized async

- pyproject.toml
- src/zarr/abc/codec.py
- src/zarr/abc/metadata.py
- src/zarr/api/asynchronous.py
- src/zarr/codecs/gzip.py
- src/zarr/core/chunk_grids.py
- src/zarr/core/group.py
- src/zarr/core/indexing.py
- src/zarr/core/metadata/__init__.py
- src/zarr/core/metadata/v3.py
- src/zarr/core/strings.py
- tests/test_api.py
- tests/test_codecs/test_codecs.py
- tests/test_metadata/test_consolidated.py
> Add more ruff rules

- src/zarr/abc/store.py
- src/zarr/storage/local.py
- src/zarr/storage/logging.py
- src/zarr/storage/memory.py
- src/zarr/storage/remote.py
- src/zarr/storage/zip.py
The `None` was added in 0e035fb / #1844, let's try to remove it.
TODO:
> `AsyncGenerator` should not yield `None`

- src/zarr/core/group.py
The keyword argument `shape` is mandatory.
TODO:
> Missing mandatory keyword argument

- src/zarr/storage/logging.py
- tests/test_store/test_local.py
- tests/test_store/test_zip.py
Remove useless `!s` in `f"...{...!s}..."`.
> Remove useless `{...!s}`

- src/zarr/abc/store.py
- src/zarr/storage/local.py
- src/zarr/storage/logging.py
- src/zarr/storage/memory.py
- src/zarr/storage/remote.py
- src/zarr/storage/zip.py
Fixes #2377.
See https://github.com/microsoft/pyright/discussions/4741.
TODO:
> AsyncGenerator → AsyncIterator

- src/zarr/core/indexing.py
- src/zarr/errors.py
- src/zarr/storage/common.py
- src/zarr/storage/local.py
- src/zarr/storage/memory.py
- src/zarr/storage/zip.py
Small fixes around `{...!r}` occurrences.
TODO:
> Assorted small fixes for f-strings

- src/zarr/api/asynchronous.py
- tests/test_api.py
- tests/test_v2.py
Raises `FileNotFoundError` if `open_array` is invoked with `mode=r+` when no extant array is found.
Fixes #2491 
TODO:
> fix open_array for mode r+

- src/zarr/storage/common.py
`StorePath.delete_dir` does not need to normalize paths, because it calls  `store.delete_dir`, which does its own path normalization. 
TODO:
> don't normalize paths in StorePath.delete_dir

- src/zarr/storage/zip.py
Zipstore's implementation of `delete_dir` was not normalizing input paths correctly, resulting in the empty string '' being replaced with '/', which would fail to match anything.
> handle empty string prefix in zipstore delete dir

- .pre-commit-config.yaml
- pyproject.toml
Remove asciitree dependency. I couldn't find any use of it in the codebase.
Fixes #1370
Contributes to #2391
> Remove asciitree dependency

- src/zarr/core/array.py
- tests/test_array.py
Now that Store.getsize is a thing, we can do info_complete which includes the number of chunks written and the size of those bytes.
The current implementation unfortunately does two `list_prefix`es on the same prefix. The first to get the count of chunks initialized and the second to get the bytes stored under a prefix. Unfortunately, these down compose well. I haven't thought of a nice way to eliminate that yet. We can do this naively by doing a single `list_prefix` and then counting the number of keys as we call `getsize` on each. But we also have a `Store.getsize_prefix` for those stores that have fastpaths for getting the total number of bytes under a prefix. I don't really want a `Store.getsize_and_count_prefix`, but maybe some kind of `Store.statistics_prefix`? Probably not worth …
> Added Array.info_complete

- src/zarr/core/array.py
- tests/test_indexing.py
> Error when attempting to set with an array of incompatible shape.

- src/zarr/api/asynchronous.py
- src/zarr/storage/common.py
Also discard commented out code. Code commented out without a comment doesn't help. The reason here was circular imports.
TODO:
> `zarr.store` → `zarr.storage`

- .github/workflows/test.yml
Adds a "test complete" step to the test CI pipeline so that we can use that as a requirement for auto-merging.
> add a complete step to the test CI

- src/zarr/api/asynchronous.py
- src/zarr/api/synchronous.py
- src/zarr/core/group.py
- tests/test_api.py
We probably should have deprecated this in 2.18 but alas, here we are. This PR uses `Group.tree` for `zarr.tree` but adds a deprecation warning stating that we'll remove this after 3.0.
TODO:
> [v3] implement / deprecate zarr.tree

- docs/contributing.rst
- docs/installation.rst
- src/zarr/core/group.py
This improves the installation page by:
- Removing dev installation steps, instead link to the contribution guide
- Split into pip/conda sections, which enables:
- Documenting the pip extras available
> Improve installation page

- docs/conf.py
- docs/release.rst
- docs/tutorial.rst
- pyproject.toml
- requirements_dev_optional.txt
- zarr/storage.py
- zarr/tests/test_core.py
- zarr/tests/test_hierarchy.py
- zarr/tests/test_storage.py
- zarr/tests/test_storage_v3.py
See https://github.com/zarr-developers/numcodecs/issues/653 for context. This should make tests run again on the v2 branch.
Also fixes some parts of https://github.com/zarr-developers/zarr-python/pull/2344 that were broken regarding skipping the bsddb3 doctests (I'm not sure why tests didn't run in that PR...)
> Exclude bad version of numcodecs & fix bsddb3 doctests

- .pre-commit-config.yaml
* Python 3 is the default nowadays, no need to specify it.
* Update pre-commmit less often that the "weekly" default.
TODO:
> Improve pre-commit configuration

- src/zarr/core/array.py
- src/zarr/core/common.py
- src/zarr/core/metadata/common.py
- src/zarr/core/metadata/v2.py
- src/zarr/core/metadata/v3.py
- src/zarr/storage/_utils.py
- src/zarr/testing/store.py
- src/zarr/testing/strategies.py
- tests/test_codecs/test_vlen.py
- tests/test_metadata/test_v2.py
- tests/test_metadata/test_v3.py
- tests/test_store/test_memory.py
The `None` literal represents the absence of a value. For readability, it's preferred to write the more informative type expressions first.
TODO:
> Apply ruff preview rule RUF036

- src/zarr/api/asynchronous.py
- src/zarr/core/array.py
- src/zarr/core/group.py
- tests/conftest.py
- tests/test_array.py
- tests/test_group.py
- tests/test_v2.py
`exists_ok` is renamed to `overwrite`.  closes #2527 
TODO:
> rename exists_ok to overwrite

- docs/release.rst
- src/zarr/storage/__init__.py
- src/zarr/storage/common.py
- src/zarr/storage/fsspec.py
- tests/conftest.py
- tests/test_store/test_core.py
- tests/test_store/test_fsspec.py
Small namespace optimization here. Renaming `RemoteStore` -> `FsspecStore`. 
TODO:
> rename RemoteStore -> FsspecStore

- docs/guide/index.rst
- docs/guide/whatsnew_v3.rst
- pyproject.toml
Fixes https://github.com/zarr-developers/zarr-python/issues/2539.
> Clean up optional dependency groups

- docs/contributing.rst
This shortens the title a bit, so it takes up less room in the top navigation bar.
> Shorten contributing page title

- src/zarr/registry.py
- tests/test_config.py
- contributes to #2509 by removing a UserWarning if no codec implementation was selected in config but only 1 is registered 
TODO:
> Remove config warning if only one implementation exists

- src/zarr/core/array.py
- tests/test_array.py
`AsyncArray.nbytes` is very wrong, this PR corrects it (and adds tests)
closes #2575 
TODO:
> correct array.nbytes, and add tests

- zarr/tests/test_creation.py
- zarr/tests/test_util.py
- zarr/util.py
When shape or chunks contains float values, the digits after the decimal point are trimmed.
This pull request generates a UserWarning when one or multiple values in shape or chunks are non-integer.
The problem is described in more detail in #2530 and is already fixed in v3 by PR #2535.
TODO:
> Warn the user when shape or chunks contains float values

- test.py
removes a top-level `test.py` file that I think got committed inadvertantly
TODO:
> remove test.py

- docs/about.rst
- docs/getting_started.rst
- docs/index.rst
This PR adds a new `about` page to Zarr's documentation. 
Notes for reviewers:
- This was split out from https://github.com/zarr-developers/zarr-python/pull/2568 and builds on https://github.com/zarr-developers/zarr-python/pull/2589.
- This content was previously part of the `getting-started` page which is turning into the `quickstart` page in #2590.
> docs: add new top level about page

- src/zarr/storage/local.py
See https://github.com/zarr-developers/zarr-python/issues/2451 - although the request in that issue was to fix the code, this at least honestly documents what currently happens.
> Note that whole directories can be deleted in LocalStore

- pyproject.toml
I noticed when preparing #2613 and #2614 that our `run-coverage` scripts were not configured correctly. This adjusts the invocation of pytest to point at the `src` directory instead of `tests`.
> fix: run-coverage command now tracks src directory

- docs/conf.py
Fixes https://github.com/zarr-developers/zarr-python/issues/2604. I tried renaming the sub-modules, but that messed around with the codec registration, so this seems like the easiest fix.
> Don't document zarr.codec submodules

- src/zarr/convenience.py
- src/zarr/creation.py
- Add a better deprecation warning (I think these are intended to be used from `zarr.`?)
- Add a warning to the API docs page
> Improve deprecation of zarr.creation and zarr.convenience

- docs/conf.py
- docs/user-guide/arrays.rst
- docs/user-guide/attributes.rst
- docs/user-guide/config.rst
- docs/user-guide/consolidated_metadata.rst
- docs/user-guide/groups.rst
- docs/user-guide/performance.rst
- docs/user-guide/storage.rst
- pyproject.toml
This reverts using IPython for code examples in https://github.com/zarr-developers/zarr-python/pull/2589, and is targeted to that branch (not main). See https://github.com/zarr-developers/zarr-python/pull/2589#pullrequestreview-2525360742 for the motivation for not switching to IPython, but sticking with the doctest status-quo
> Use doctests for guide

- docs/index.rst
I think it makes more sense to go
- Getting started
- User guide
- API ref
...
Instead of having the "About" page breaking this order up.
> Move 'about' to end of table of contents

- docs/user-guide/v3_migration.rst
These are currently misaligned in the source, which is probably why it's funnily rendered.
TODO:
> Align lines for improved rendering

- pyproject.toml
The moto server used in [the fsspec tests](https://github.com/zarr-developers/zarr-python/blob/22634ea2dabc0ad9ecfa932e21079fabe94c1f50/tests/test_store/test_fsspec.py#L25) requires Flask, which is not installed by default with moto. This PR adds the necessary optional dependencies to the test environment using the method recommended in https://github.com/getmoto/moto/issues/5468#issuecomment-1260152788.
> Add moto[server] to test deps for FsspecStore

- src/zarr/core/metadata/v2.py
- tests/test_metadata/test_v2.py
Changes the zstd codec to not persist the checksum param, if it is set to False (the default). This is aimed at improving backwards compatibility.
See https://github.com/zarr-developers/zarr-python/issues/2647#issuecomment-2571758778
Fixes #2647
> Zarr v2 + Zstd: Don't persist the checksum param if false

- src/zarr/core/group.py
- tests/test_group.py
> Fix `Group.array()` with `data` argument

- src/zarr/core/sync.py
- tests/test_sync.py
While preparing an update to the performance documentation page, I noticed that the threadpool executor was not being created when `threading.max_workers` was set. Not sure what happened back in #2327 (perhaps a bad merge conflict resolution) but this should fix the issue. I improved the test to make sure this works end-to-end now.
> fix: threadpool configuration

- docs/conf.py
Adds a banner to the top of the documentation pointing readers to the 3.0 release announcement. 
Merge after https://github.com/zarr-developers/blog/pull/64
> doc: add release announcement banner

- docs/release-notes.rst
- src/zarr/core/array.py
- tests/test_v2.py
> Fix: order for v2 arrays

- .github/workflows/test.yml
- codecov.yml
- pyproject.toml
> test: enable codecov in main test action

- docs/developers/contributing.rst
This adds a new section for new release notes, and also updates the release guide to explain how to handle the release notes. The sections I chose for the release notes are very much up for change/suggestion.
> Bootstrap release notes post v3

- docs/release-notes.rst
I propose that we don't add usernames to changelog entries, because it's one extra bit of work to do, and as long as we have a link to the issue it's easy from that to see who contributed to the PR.
> Don't put usernames in changelog

- docs/quickstart.rst
- Updates the quickstart guide to explicitly specify `dtype` parameter in `zarr.create_array` examples, as it is a required parameter.
- Updates the quickstart guide to use correct compressor specification.
This fixes incorrect examples in the documentation that were missing the mandatory `dtype` parameter, which would cause errors if users tried to run them.
TODO:
> Quickstart guide alignment with V3 API

- docs/release-notes.rst
- src/zarr/core/group.py
- tests/test_metadata/test_consolidated.py
This is a quick fix for the problem reported in https://github.com/zarr-developers/zarr-python/issues/2694 where an empty consolidated dataset created with `zarr-python 2.x` fails to being read by `zarr-python 3.x` because of the absence of `.zattrs` from the store.
> Ensure backwards compatibility

- docs/release-notes.rst
- src/zarr/core/array.py
- src/zarr/core/group.py
- tests/test_group.py
- tests/test_metadata/test_consolidated.py
- tests/test_v2.py
> Ensure compressor=None results in no compression for V2

- .pre-commit-config.yaml
- pyproject.toml
- src/zarr/codecs/sharding.py
- src/zarr/core/indexing.py
- src/zarr/core/metadata/v3.py
- tests/test_properties.py
* Fix `RUF100` new warnings (`E402` unused).
* Enable `ISC001`/`ISC002` since the [documentation](https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules) now states that they are compatible with the ruff formatter if used together:
> When using Ruff as a formatter, we recommend avoiding the following lint rules:
> [...]
> [`multi-line-implicit-string-concatenation`](https://docs.astral.sh/ruff/rules/multi-line-implicit-string-concatenation/) (`ISC002`) if used without `ISC001` and `flake8-implicit-str-concat.allow-multiline = false`
TODO:
> Upgrade ruff to 0.9.1

- pyproject.toml
This fixes the minimum fsspec version we test on to actually match the minimum fsspec version in the dependencies. I also put in `zarr[remote]` as a test dep, which should prevent this happening in the future.
> Fix minimum fsspec test verseion

- .github/labeler.yml
- .github/workflows/needs_release_notes.yml
The filename changed (my bad for not updating this when I changed the filename). I also pinned the action to a specific version to avoid it changing under our feet without us checking, dependabot should automatically update this for us.
> Fix release notes labelling

- docs/release-notes.rst
- docs/user-guide/arrays.rst
Fixes doctests failures found in #2726.
TODO:
> doc: fix codec reprs in doctests

- docs/developers/contributing.rst
- pyproject.toml
I found the html coverage report simpler to use for monitoring progress in https://github.com/zarr-developers/zarr-python/pull/2693 and am wondering if you would consider a hatch command for this, such as the one suggested in the PR.
I also propose adding a `run-pytest` alias for `run` because I heard that using `hatch run --env <env> run` to run the tests was a bit confusing to new contributors at the Pangeo hackday.
> Add hatch command for html coverage report

- .github/labeler.yml
This seems to have gone wrong in https://github.com/zarr-developers/zarr-python/pull/2736, so trying to fix here.
Because the job is defined using `pull_request_target`, it's run from the GH actions config on the `main` branch, so this will need merging to fix the job.
> Fix label action

- .github/labeler.yml
This fixes the labeler to work correctly - it currently is the wrong way round:
- https://github.com/zarr-developers/zarr-python/pull/2693, which shouldn't have the label (but does)
- https://github.com/zarr-developers/zarr-python/pull/2758, which should have the label (but doesn't)
> Fix "needs release notes" labeler action

- changes/2762.bugfix.rst
- src/zarr/storage/_zip.py
- src/zarr/testing/store.py
Fixes https://github.com/zarr-developers/zarr-python/issues/2752. The issue was not all attributes were being pickeld for `ZipStore`. This changes the pickling to pickle everything by default, but exclude certain attributes, which I think is a bit safer to guard against other attributes changing in the future?
> Fix pickling of ZipStore

- .github/workflows/gpu_test.yml
I noticed that the GPU tests aren't uploading coverage to codecov - hopefully this should improve our test coverage a bit!
> Upload coverage after GPU tests

- changes/2782.bugfix.rst
- src/zarr/core/indexing.py
- tests/test_array.py
- tests/test_indexing.py
Avoid an unnecessary get when overwriting a whole chunk using "orthogonal selection"
TODO:
> Optimize is_total_slice for chunksize == 1

- .github/labeler.yml
- changes/2781.bugfix.rst
This PR updates the Pull Request Labeler configuration to use all/all matching criteria instead of the previous any/any setup for the `needs release notes` label. This change makes it so that the label is automatically removed when a `changes/*.rst` file is added/modified in the PR.
Fixes: #2779 
TODO:
> Support automatic removal of `needs release notes`

- .github/labeler.yml
- changes/2785.bugfix.rst
Well, this is embarrassing. Need to pluralize `glob` and `file` when using `all` as opposed to `any`. Makes sense. Missed it. Going to test things first by changing target to `pull_request` rather than `pull_request_target`
TODO:
> Pluralize glob and file in labeler.yml

- changes/2778.bugfix.rst
- src/zarr/storage/_fsspec.py
- src/zarr/testing/store.py
The point of replace here is just to remove the prefix instance but it has the unintended consequence of deleting separators when path is the empty string. This uses `removeprefix` explicitly and avoids that potential pitfall
Fixes #2777 
TODO:
> Use removeprefix rather than replace to avoid separator deletion

- changes/2807.bugfix.rst
- src/zarr/storage/_zip.py
- src/zarr/testing/store.py
It's important for stores that manually implement `__getstate__` and `__setstate__` that the store behavior is tested beyond a simply equality check. This is motivated by https://github.com/zarr-developers/zarr-python/pull/1661, where I first added incorrect serialization functionality even though it passed this test. This PR adds a simple set/get check on the serialization test and exposes an issue with ZipStore.
TODO:
> Strengthen pickling test and fix ZipStore __getstate__()

- .github/workflows/hypothesis.yaml
- changes/2804.feature.rst
- pyproject.toml
- src/zarr/storage/_local.py
- src/zarr/testing/stateful.py
- src/zarr/testing/strategies.py
- tests/conftest.py
- tests/test_store/test_stateful.py
Also restrict stateful tests to slow hypothesis CI workflow to speed up the CI a bit (cc @dstansby)
Seems to work:
-  `SKIPPED [6] tests/test_store/test_stateful.py: need --run-slow-hypothesis option to run`
Also fixes the LocalStore stateful test
TODO:
> Enable stateful tests for LocalStore

- .github/workflows/test.yml
- changes/2811.bugfix.rst
- tests/test_array.py
Fix is in upstream https://github.com/zarr-developers/numcodecs/pull/700 
Closes #2800
TODO:
> Regression test for codec overwriting.

- src/zarr/core/sync.py
- tests/test_array.py
I wanted to use this PR to add tests to ensure that basic array operations work in a multiprocessing context. But right now I just have 1 test, and it's failing with an infinite stall. Since this breaks the entire test suite, we should also fix the underlying bug in this PR. Stay tuned!
closes #2812
> Multiprocessing support

- changes/2799.bugfix.rst
- src/zarr/core/codec_pipeline.py
- src/zarr/core/metadata/v2.py
- tests/test_v2.py
Fixes omissions in https://github.com/zarr-developers/zarr-python/pull/2274
- initialise empty chunks to the default fill value during writing
- add default fill value for datetime, timedelta, structured, and other (void* fixed size) data types
- add test for "other" data type
Fixes the below:
```python
array = zarr.create_array(
store=zarr.storage.MemoryStore(),
dtype=np.uint8,
shape=(4,),
chunks=(2,),
fill_value=None,
zarr_format=2,
)
array[:3] = [1, 2, 3]
print(array[:]) # [1, 2, 3, undefined]
```
TODO:
> fix: implicit fill value initialisation

- changes/2784.feature.rst
- src/zarr/abc/codec.py
- src/zarr/codecs/sharding.py
- src/zarr/core/array.py
- src/zarr/core/codec_pipeline.py
- src/zarr/core/indexing.py
- src/zarr/storage/_logging.py
- src/zarr/testing/strategies.py
- tests/test_array.py
- tests/test_indexing.py
- tests/test_properties.py
Teach the *Indexer objects to detect when a selection corresponds to a whole chunk. Propagate that information down to the codec pipeline where reads can be skipped if it makes sense locally.
Closes #757
~I'm opening this for comments about the approach (@d-v-b , @normanrz ) it could definitely use more tests (edit: and some fixes)~
TODO:
> Always skip reads when completely overwriting chunks

- changes/2817.bugfix.rst
- src/zarr/codecs/sharding.py
- src/zarr/core/indexing.py
- tests/test_array.py
> fix: sharding codec with fancy indexing

- changes/2813.feature.rst
- src/zarr/testing/strategies.py
- tests/test_properties.py
Found this useful for icechunk and presumably will be useful in virtualizarr (https://github.com/zarr-developers/VirtualiZarr/pull/429#pullrequestreview-2606335493)
cc @TomNicholas @aimeeb @moradology 
TODO:
> Add Array metadata strategy

- changes/2822.feature.rst
- src/zarr/testing/strategies.py
Adds `shards` strategy and uses it in the `arrays` strategy
This does catch #2816 and needs #2817 to be merged to pass.
TODO:
> Add shards to array strategy

- changes/2661.feature.1.rst
- changes/2751.bugfix.rst
- changes/2751.doc.rst
- changes/2751.feature.rst
- changes/2755.bugfix.rst
- changes/2758.bugfix.rst
- changes/2778.bugfix.rst
- changes/2781.bugfix.rst
- changes/2784.feature.rst
- changes/2785.bugfix.rst
- changes/2795.bugfix.rst
- changes/2799.bugfix.rst
- changes/2801.bugfix.rst
- changes/2804.feature.rst
- changes/2807.bugfix.rst
- changes/2811.bugfix.rst
- changes/2813.feature.rst
- changes/2817.bugfix.rst
- changes/2822.feature.rst
- docs/release-notes.rst
> Changelog for v3.0.3

- changes/2847.fix.rst
- src/zarr/core/metadata/v2.py
- tests/test_array.py
- tests/test_metadata/test_v2.py
- tests/test_properties.py
We were violating the v2 spec by serializing "no filters" as the empty array. We created arrays in the wild with this metadata, so any fix should be backwards compatible.
To fix this bug, this PR changes the filters parsing function so that it no longer returns empty tuples, and instead return `None` when no filters are specified. For backwards compatibility with datasets created with earlier versions of zarr-python 3.x, the `from_dict` method will replace empty lists / tuples with the value `None` and emit a warning. 
After a reasonable amount of time (a few minor releases?) we should remove this special-casing and treat `filters = []` as an error. Happy to chat about the timeline.
closes https://github.com/zarr-developers/zarr-python/issues/2842
TODO:
> don't serialize empty tuples for v2 filters, and warn when reading such metadata

- changes/2851.bugfix.rst
- src/zarr/core/codec_pipeline.py
- src/zarr/storage/_fsspec.py
- src/zarr/testing/stateful.py
- src/zarr/testing/strategies.py
- tests/test_array.py
- tests/test_indexing.py
- tests/test_properties.py
Closes #2849
cc @ilan-gold 
TODO:
> Fix a bug when setting complete chunks

- tests/test_indexing.py
This PR simply uses the standard memory-based store to avoid creating `foo.zarr/` at the root of the project every time tests run
TODO:
> Avoid creating persistent files during tests

- docs/release.rst
- zarr/core.py
- zarr/creation.py
- zarr/tests/test_core.py
Since this was deprecated in numcodecs (https://github.com/zarr-developers/numcodecs/pull/619), deprecate it here too.
I think it would be good to put this in 2.18.5, then remove the code in 2.19.0 to reduce the maintenance burden on `zarr-python` v2. Any thoughts on that?
> Deprecate partial read/writes in v2

- changes/2870.bugfix.rst
- src/zarr/core/array.py
- src/zarr/core/attributes.py
- src/zarr/core/common.py
- src/zarr/core/group.py
- tests/test_attributes.py
- tests/test_group.py
This PR fixes attribute updating logic by clearing in calls to `put` and removing `clear` calls from all `update_attributes` methods. It also fixes an apparent oversight in the JSON type (advise if I'm wrong) which didn't allow lists. Sequence should handle both `tuple` and `list`
closes: #2867 
TODO:
> Prevent update_attributes from erasing all prior attributes

- src/zarr/codecs/blosc.py
The "see more" under BloscCname class contains [old link](https://zarr.readthedocs.io/en/stable/tutorial.html#configuring-blosc) to refer more information about configuring Blosc but it is currently shifted to [new link](https://zarr.readthedocs.io/en/stable/user-guide/performance.html#configuring-blosc)
> DOC: Fixed incorrect link in blosc.py

- docs/release.rst
- pyproject.toml
- zarr/_storage/v3.py
- zarr/storage.py
This is a minimal attempt to fix the failing sqlite tests on the 2.x branch
> Fix sqlite store in 2.x

- docs/user-guide/v3_migration.rst
My first contribution addressing #2733! This PR adds documentation to clarify store import changes in the v3 migration guide.
- Clear comparison table showing v2 vs v3 imports for MemoryStore/DirectoryStore
- Example using tempfile.TemporaryDirectory for TempStore migration
- Fixed formatting in the migration guide based on build feedback
✅ Docs updated in `user-guide/v3_migration.rst`  
✅ No code changes needed (pure documentation)  
✅ Built docs locally to verify formatting  
This helps users like those in imagecodecs#123 who encountered build errors with old imports. While it doesn't fix external projects directly, it:  
1. Shows proper v3 import paths  
2. Explains replacements for deprecated stores  
3. Provides copy-paste examples for common migrations  
I'm happy to make any …
> DOC: Add store import changes to v3 migration guide (fix #2733)

- .github/ISSUE_TEMPLATE/config.yml
- README.md
- docs/index.rst
Various places in the docs say something like "here is our zulip [link to zulip chat]". I think it's better to say "here is our developer chat [link to zulip chat]".
Two main reasons for this change:
- People might not know what zulip is. But they will know what developer chat is.
- We might hypothetically switch chat platforms. With these changes, we would only need to update the hyperlink.
TODO:
> refer to zulip chat as developer chat

- changes/2908.bugfix.rst
- src/zarr/core/attributes.py
- tests/test_attributes.py
Restore the bevahior of `del obj.attrs['some-key']` to the pre #2870 behavior
Fixes: https://github.com/zarr-developers/zarr-python/issues/2903
TODO:
> fix: restore attrs del functionality

- README.md
Modified the links in the main feature section of README.md from V2 docs to V2 docs for the issue #2914 
Most links that I've replaced have similar/identical content to the tutorial page from V2, but in different pages in V3.
TODO:
> Modify the link in README.md from V2 to V3 docs

- changes/2944.misc.rst
- src/zarr/storage/_local.py
This removes an unnecessary memory copy when writing to a local file, bringing the memory usage in line with Zarr Python v2 for this case (see https://github.com/tomwhite/memray-array).
TODO:
> Avoid memory copy in local store write

- pyproject.toml
Fixes https://github.com/zarr-developers/zarr-python/issues/2963 - I think worth getting this in and doing a release straight away, since it unbreaks an installation with just `pip install zarr<3`
> Pin numcodecs to < 0.16 to fix v2

- changes/2714.misc.rst
- pyproject.toml
- tests/test_array.py
- tests/test_store/test_fsspec.py
- tests/test_store/test_memory.py
- tests/test_store/test_stateful.py
- tests/test_store/test_wrapper.py
- tests/test_store/test_zip.py
- tests/test_sync.py
I'm hoping to clean up the warning filters in this PR, starting with making them all error, and then either fix the warnings that come up or add them back to the filters. Opening because I noticed some deprecation warnings in our tests that should probably either be explicitly caught or the code fixed.
Fixes https://github.com/zarr-developers/zarr-python/issues/2968
> Clean up warning filters in tests

- changes/2996.bugfix.rst
- src/zarr/core/group.py
- tests/test_metadata/test_consolidated.py
Fixes #2990 by reusing the special character replacement before encoding the same as the v3 metadata does 
TODO:
> Fix nan encoding in consolidated metadata

- src/zarr/core/metadata/v2.py
In #2802 a `print` statement was added to V2 metadata parsing for structured arrays. This is most likely a debugging statement. Removing this because it prints every time we open a group or array with structured arrays.
TODO:
> [v2] Remove `print` statement from structured dtype metadata parsing

- src/zarr/testing/strategies.py
> hypothesis: Don't generate node name: 'zarr.json'

- changes/2998.bugfix.md
- src/zarr/core/group.py
- tests/test_metadata/test_v2.py
> (fix): structured dtype fill value consolidated metadata

- pyproject.toml
This is an attempt to debug recent test failures, which I think might be caused by a very old version of s3fs being installed. I have no idea why that's happening though, so maybe adding a pin here will help debug?
Update: this fixes the tests, so I think it's fine (and good) to merge. Since this only updates dev dependencies, I don't think it needs a release note.
> Pin minimum s3fs (to fix tests)

- tests/test_group.py
- tests/test_store/test_core.py
> Replace redundant list comprehension with generator

- .pre-commit-config.yaml
- pyproject.toml
Replaces https://github.com/zarr-developers/zarr-python/pull/2966. I'm not a fan of making all type hints strings instead of actual types, so I added an exclusion to TC006. An example of changes that would happen if we enabled TC006 can be found at https://github.com/zarr-developers/zarr-python/pull/2966 if folks are interested.
Also replaces https://github.com/zarr-developers/zarr-python/pull/3032, because it seemed sensible to do that here too.
> Update pre-commit hooks

- src/zarr/testing/stateful.py
Since the store tests are insensitive to how data is encoded, use the simplest codecs to avoid compressing the data all the time these tests are run.
Should help a bit with https://github.com/zarr-developers/zarr-python/issues/3010.
> Don't compress data in hypothesis store testing

- changes/3068.bugfix.rst
- src/zarr/storage/_common.py
- tests/test_api.py
- tests/test_array.py
- tests/test_store/test_core.py
This avoids instances where mode='r' could be passed, by the resulting array is not read-only. Fixes https://github.com/zarr-developers/zarr-python/issues/2949
> Error on invalid store mode

- changes/3082.feature.rst
- src/zarr/core/buffer/cpu.py
I was profiling code and noticed a non-trivial amount of time spent on `np.full` with a `fill_value=0` so I did a little digging and at least on my machine:
```python
In [1]: import numpy as np
In [2]: %timeit np.full((10_000, 10_000), dtype=np.float32, fill_value=0, order="C")
33.2 ms ± 784 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)
In [3]: %timeit np.zeros((10_000, 10_000), dtype=np.float32, order="C")
1.04 μs ± 1.48 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
```
For example: 
https://github.com/zarr-developers/zarr-python/blob/481550a2b98d1bf51d731653208c26b5bcfce454/src/zarr/core/array.py#L1285-L1290
and
https://github.com/zarr-developers/zarr-python/blob/481550a2b98d1bf51d731653208c26b5bcfce454/src/zarr/codecs/sharding.py#L441-L443
are both points …
> (feat): use `np.zeros` for buffer creation with `fill_value=0`

- .github/workflows/gpu_test.yml
- .github/workflows/hypothesis.yaml
- .github/workflows/test.yml
- pyproject.toml
~~This is a bit of an experiment to see if using `'2'` will give us the latest verison of numpy to test on~~
This bumps to the latest version of numpy. We still need to fix typing to work with numpy 2.2, but worth running tests for now at least.
> Test using latest numpy

- changes/3100.bugfix.rst
- src/zarr/core/array.py
- tests/test_array.py
This PR removes the following code block:
https://github.com/zarr-developers/zarr-python/blob/0dd797f8a7eeab05982a1e4115990200d97d9d98/src/zarr/core/array.py#L771-L777
Neither of the two numpy dtypes that can model variable-length strings are subdtypes of `np.str_`:
```python
>>> np.issubdtype(np.dtypes.ObjectDType(), np.str_)         
False
>>> np.issubdtype(np.dtypes.StringDType(), np.str_)         
False
```
so there is no reason to use vlen-string codec here.
This was revealed by [regression testing against 2.18](https://github.com/zarr-developers/zarr-python/pull/3099). Zarr-python 2.18 cannot read certain arrays generated by zarr-python main because we inserting this codec.
> remove insertion of vlen-string codec for v2 metadata creation

- changes/3066.bugfix.rst
- changes/3066.feature.rst
- src/zarr/api/asynchronous.py
- src/zarr/errors.py
- tests/test_metadata/test_v3.py
Fixes https://github.com/zarr-developers/zarr-python/issues/2298.
Note I also updated the base zarr exception to no longer inherit from ValueError, because in general errors we raise are not always ValueErrors. I'll add a separate release note for this change.
> Add a GroupNotFoundError

- changes/2921.bugfix.rst
- src/zarr/api/asynchronous.py
- src/zarr/core/group.py
- tests/test_metadata/test_consolidated.py
This fixes a bug when recreating consolidated metadata, when one of the child groups picked up had (stale) consolidated metadata.
In `consolidate_metadata`, we already ignore the `group.metadata.consolidated_metadata` for the root group. The fix is to *also* ignore the consolidated metadata for any child nodes loaded by `.members()`.
For now, I've made this a new public parameter in `.members()`. It might be worth keeping it private (by making a `_members_private` method that takes this parameter). I don't immediately see any other use case for this parameter.
Closes #2921 
TODO:
> Ignore stale children when reconsolidating metadata

- pyproject.toml
- tests/test_metadata/test_consolidated.py
> Add pytest pin

- pyproject.toml
This removes fsspec from our upstream tests. Since s3fs depends on a released version of fsspec, we will test against that version when we pull in s3fs.
resolves #3115
> remove fsspec from upstream tests

- .github/workflows/hypothesis.yaml
- .github/workflows/test.yml
> Enable tests on 3.0.x branch

- .github/CONTRIBUTING.md
Just noticed a dead link when creating another PR and was therefore looking for the contributing guide
> Fix URL to contributing guide

- src/zarr/core/dtype/npy/structured.py
> Appending to dictionary following its definition

- .pre-commit-config.yaml
- src/zarr/core/buffer/core.py
- src/zarr/core/dtype/npy/bytes.py
- src/zarr/core/dtype/npy/structured.py
- src/zarr/core/dtype/npy/time.py
- src/zarr/storage/_memory.py
- src/zarr/storage/_zip.py
- tests/test_config.py
Replaces https://github.com/zarr-developers/zarr-python/pull/3109.
> Update pre-commit hooks + mypy fixes

- changes/3170.bugfix.rst
- src/zarr/core/dtype/__init__.py
- src/zarr/core/dtype/npy/bytes.py
- src/zarr/core/dtype/npy/string.py
- src/zarr/core/dtype/npy/structured.py
- tests/test_array.py
- tests/test_dtype/test_npy/test_bytes.py
- tests/test_dtype/test_npy/test_string.py
- tests/test_dtype/test_npy/test_structured.py
- tests/test_dtype_registry.py
- tests/test_regression/scripts/v3.0.8.py
- tests/test_regression/test_v2_dtype_regression.py
this PR fixes the issues reported in #3167.
There were two problems driving that issue:
- zarr python was not using the string `"str"` to denote a variable length string data type. Instead, in main we use NumPy's behavior and map `"str"` to a fixed-length UTF-32 string, which is not a useful data type for most people. 
In this PR, when a user requests `dtype=str` or `dtype="str"` or `dtype="string"` they get a `VariableLengthUTF8` dtype instead of the nearly-useless `U` dtype.
- zarr python could create data types for length-0 scalars. Since these data types cannot be associated with arrays that contain any values, they are useless. See #3168. This is a quirk of NumPy that we don't need to support. This PR contains logic to ensure that we don't create data types for length-0 scalars.
note …
> string dtype fixes

- changes/3191.feature.rst
- src/zarr/core/buffer/core.py
- src/zarr/core/buffer/cpu.py
- src/zarr/core/buffer/gpu.py
- src/zarr/testing/buffer.py
- src/zarr/testing/utils.py
- tests/test_buffer.py
In https://github.com/zarr-developers/zarr-python/issues/2904, I've found that `np.empty(...)` can be quite a bit faster than the `np.full` we use in places
(https://github.com/zarr-developers/zarr-python/blob/baabf08d07e8518e3d37bd83c493a1d46ea7ac1d/src/zarr/core/buffer/cpu.py#L149. Though note that `np.empty` and `np.zeros` are about the same for the cases where we use that.)
For the common case of chunk-aligned reads, the memset used by `np.full` or `np.zeros` should be unnecessary, because the codec pipeline will overwrite the memory anyway (or overwritten with `fill_value` if the store is missing the key).
This adds a new method `NDBuffer.empty`, mirroring `np.empty`. To preserve backwards compatibility, it's *not* abstract. It delegates to the less efficient `NDBuffer.create`. But …
> Add NDBuffer.empty

- changes/3193.bugfix.rst
- src/zarr/storage/_fsspec.py
- tests/test_store/test_fsspec.py
* Remove breaking check from _make_async
* Update expected error
* Change import structure to protect against AttributeError
* changelog
* add test to ensure that we can create a read-only copy of the store with auto_mkdir=False
* only test if the async wrapper is available
---------
(cherry picked from commit 5a24487f09d499c91ce25f24af910c2ede055b5a)
TODO:
> "Backport PR #3193 on branch 3.0.10 (Remove breaking check about auto_mkdir for FSSpecStore)"

- changes/3151.bugfix.rst
I think this was a fix to code introduced for the first time in 3.1.0 anyway, so this release note isn't needed for users?
TODO:
> Remove redundant release note

- changes/3232.bugfix.rst
- src/zarr/core/metadata/v2.py
Because `__init__` parses a `CompressorLikev2` input, I *think* the actual attribute type should simply be a `Codec` or None.
> Fix type of v2 compressors

- src/zarr/storage/_obstore.py
mypy was flagging problems with some of the obstore type annotations. I don't know what change precipitated these new errors, but this PR silences them by adding type: ignore statements. Obviously fixing the type annotations would be even better, but several obvious things that I attempted did not work, so I think we need an obstore expert for a real fix (@kylebarron)
until then, this PR keeps our CI clean
TODO:
> fix obstore type hints

- src/zarr/testing/stateful.py
This PR prevents the stateful group tests from deleting the root group
TODO:
> don't test self-deletion in stateful tests

- pyproject.toml
- tests/test_api.py
- tests/test_config.py
- tests/test_group.py
- tests/test_indexing.py
PT012 `pytest.raises()` block should contain a single simple statement
TODO:
> Apply ruff/flake8-pytest-style rule PT012

- pyproject.toml
- tests/test_api.py
- tests/test_codecs/test_codecs.py
- tests/test_config.py
- tests/test_group.py
PT030 `pytest.warns(UserWarning)` is too broad, set the `match` parameter or use a more specific warning
TODO:
> Apply ruff/flake8-pytest-style rule PT030

- changes/3273.doc.rst
- docs/user-guide/v3_migration.rst
This fixes/improves the migration guide for the topic of codecs.
> Improve migration guide for codecs

- pyproject.toml
- src/zarr/codecs/blosc.py
- src/zarr/codecs/bytes.py
- src/zarr/codecs/crc32c_.py
- src/zarr/codecs/gzip.py
- src/zarr/codecs/sharding.py
- src/zarr/codecs/transpose.py
- src/zarr/codecs/vlen_utf8.py
- src/zarr/codecs/zstd.py
This should improve the look of the table at https://zarr.readthedocs.io/en/stable/api/zarr/codecs/index.html, which currently just has a lot of base class docstrings.
> Give codecs docstrings

- changes/3112.bugfix.1.rst
- changes/3112.bugfix.2.rst
- changes/3112.bugfix.3.rst
- changes/3112.bugfix.4.rst
- changes/3112.bugfix.rst
- changes/3227.feature.rst
- changes/3249.doc.rst
- changes/3251.bugfix.rst
- changes/3258.bugfix.rst
- changes/3264.bugfix.rst
- changes/3268.misc.rst
- changes/3273.doc.rst
- changes/3280.bugfix.rst
- changes/3287.bugfix.rst
- docs/release-notes.rst
> Release notes for 3.1.1

- .github/workflows/gpu_test.yml
- pyproject.toml
Fixes https://github.com/zarr-developers/zarr-python/issues/3333 (hopefully). To prevent me having to copy/paste environment variables for four different hatch environments, I also de-duplicated the configuration of the test environments. 🤞 this works fine, happy to revert the de-duplication and do a copy-and-paste job if folks would prefer that to keep things a bit simpler.
> Fix test coverage

- changes/3372.misc.rst
- src/zarr/abc/store.py
`zarr.abc.store` imports symbols from modules in `zarr.core`; if you add a new ABC to `zarr.abc.store`, and use it in one of the modules that `zarr.abc.store` is depending on in `zarr.core`, you will get a circular import. 
This PR puts a band-aid on this problem by moving those imports to within the methods that actually need them. A better fix would be to re-organize the dependencies of this package so that we are structurally avoiding circularity. That can come later.
closes #3338 
TODO:
> use local imports in store ABC to avoid circular import issues

- src/zarr/api/synchronous.py
- src/zarr/core/group.py
When creating an array with data, the docs incorrectly said you could provide the dtype and shape as long as it matched the data's, but when you try to set all three parameters, an error is thrown.
```
Python 3.11.11 (main, Mar 17 2025, 19:26:36) [Clang 16.0.0 (clang-1600.0.26.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import zarr
>>> from zarr.storage import LocalStore
>>> store = LocalStore("test")
>>> a = zarr.create_group(store=store)
>>> import numpy as np
>>> b = np.array([1,2,3])
>>> a.create_array(data=b, dtype=b.dtype, shape=b.shape, name="array")
...
raise ValueError(msg)
ValueError: The data parameter was used, but the shape parameter was also used. This is an error. Either use the data parameter, or the shape parameter, but not …
```
> Update docs for user-facing `create_array` api on on `Group`. 

- pyproject.toml
This reverts e77f803e1a813a496d59c3d091a263602c308bf1.
No need to explicitly avoid a yanked release. Release `9.0.0` has been yanked on PyPI. Actually all `9.*.*` releases so far have been yanked, except for the current `9.2.0`:
https://pypi.org/project/setuptools-scm/#history
TODO:
> Relax obsolete constraints on setuptools-scm

- changes/3368.misc.rst
- src/zarr/abc/codec.py
- src/zarr/codecs/sharding.py
- src/zarr/core/array.py
This optimizes our read performance by using `NDBuffer.empty` instead of `NDBuffer.create` with a fill value. All chunks are filled, either with the values from the Store if that chunk was initialized, or the fill value if the Store returns `None` (the 
chunk wasn't initialized). By not memsetting values that will be overwritten anyway, things will be a bit faster.
I didn't see any documentation about CodecPipeline in the docs. Technically, users might see a behavior change, if the user's codec pipeline happened to rely on receiving an array filled with the `fill_value`. Do we know of anyone writing / using custom codec pipelines?
Here's a mini benchmark:
<details>
```python
import asyncio
import statistics
import time
import zarr.api.asynchronous
import zarr.storage
async def main(): …
```
> Optimize getitem with empty chunks

- changes/3395.bugfix.rst
- src/zarr/core/metadata/v3.py
- src/zarr/errors.py
- tests/test_metadata/test_v3.py
This converts the `KeyError` to a new zarr-specific `UnknownCodecError`, which since it indirectly inherits from `ValueError` won't be confused with responses by the store.
TODO:
> reraise the `KeyError` for unknown codecs with a more specific error class

- changes/3307.bugfix.rst
- src/zarr/storage/_common.py
- src/zarr/storage/_local.py
- tests/test_api.py
Fixes https://github.com/zarr-developers/zarr-python/issues/3295. I'm not sure if I came up with the most elegant solution, but I couldn't think of a way to solve this without passing the mode to `LocalStore.open()`. Other suggestions very welcome if anyone has any better ideas?
> Prevent mode='r+' from creating new directories

- changes/3083.feature.rst
- changes/3098.misc.rst
- changes/3144.bugfix.rst
- changes/3288.misc.rst
- changes/3299.bugfix.rst
- changes/3307.bugfix.rst
- changes/3318.misc.rst
- changes/3367.bugfix.rst
- changes/3368.misc.rst
- changes/3371.misc.rst
- changes/3372.misc.rst
- changes/3374.misc.rst
- changes/3378.bugfix.rst
- changes/3391.feature.rst
- changes/3395.bugfix.rst
- docs/release-notes.rst
this prepares the release notes for release 3.1.2.
TODO:
> generate 3.1.2 release notes

- changes/3411.bugfix.rst
- src/zarr/storage/_local.py
- tests/test_store/test_local.py
Fixes #3411
I use the standard strategy of writing to a temporary file in the same directory, and then renaming it to the desired name. This ensure that Zarr writes are either complete or not written at all.
It would be nice if partial writes (`_put()` with `start`) could also be atomic, but I'm honestly not sure if both atomic and efficient partial writes of files are possible. Interestingly, I don't see any uses of `set_partial_values()` inside Zarr, so maybe this feature isn't needed after all? (see https://github.com/zarr-developers/zarr-python/issues/2859 for discussion)
TODO:
> Use atomic writes for new files in LocalStore

- tests/test_store/test_local.py
This should have been part of https://github.com/zarr-developers/zarr-python/pull/3412 :)
> Simplify local store tests

- changes/2859.removal.rst
- src/zarr/abc/store.py
- src/zarr/storage/_common.py
- src/zarr/storage/_fsspec.py
- src/zarr/storage/_local.py
- src/zarr/storage/_logging.py
- src/zarr/storage/_memory.py
- src/zarr/storage/_obstore.py
- src/zarr/storage/_wrapper.py
- src/zarr/storage/_zip.py
- src/zarr/testing/stateful.py
- src/zarr/testing/store.py
- tests/test_store/test_fsspec.py
- tests/test_store/test_local.py
- tests/test_store/test_logging.py
- tests/test_store/test_memory.py
- tests/test_store/test_object.py
- tests/test_store/test_wrapper.py
- tests/test_store/test_zip.py
This feature was unused by the rest of Zarr-Python, and was only implemented for LocalStore and stores that wrap other stores.
The Zarr v3 spec still mentions partial writes, so it should probably also be updated.
Fixes #2859
TODO:
> Remove Store.set_partial_writes

- changes/3428.bugfix.rst
- src/zarr/core/group.py
- tests/test_metadata/test_consolidated.py
This ensures syntax like `root['/subgroup']` works equivalently to `root['subgroup']` when using consolidated metadata.
TODO:
> Ensure absolute paths work with consolidate metadata

- changes/3490.feature.md
- src/zarr/experimental/__init__.py
Adds a `zarr.experimental` module. We can use this module to deliver new features that might be useful but might also evolve significantly in the future. The "experimental" designation should temper user expectations about stability.
closes #3484
> add experimental module

- src/zarr/storage/_obstore.py
This makes `ObjectStore` generic with respect to the underlying store, mirroring similar structure in `LoggingStore` and `WrapperStore`. This allows type checkers to infer the type of the underlying store:
```python
from typing import reveal_type
import obstore.store
from zarr.storage import ObjectStore
store = ObjectStore(obstore.store.MemoryStore())
reveal_type(store.store)
```
> Make ObjectStore a generic class
