zarr-developers/zarr-python

- requirements.txt
- tox.ini
- zarr/compat.py
- zarr/ext.pyx
This PR adds support for Python 2.7.
> PY2 compatibility

- .gitignore
- PERSISTENCE.rst
- README.rst
- zarr/ext.pyx
- zarr/meta.py
- zarr/tests/test_array.py
- zarr/tests/test_chunk.py
This PR changes the disk format to use JSON for array metadata, resolving #6.
> JSON metadata

- zarr/__init__.py
- zarr/create.py
- zarr/ext.pyx
- zarr/tests/test_create.py
> Implement empty_like, zeros_like, etc.

- zarr/core.py
- zarr/meta.py
- zarr/store.py
- zarr/tests/test_core.py
- zarr/tests/test_meta.py
- zarr/tests/test_store.py
Flush and maintain metadata and attrs in data dict
> Refactor 3

- .gitignore
- docs/release.rst
- docs/tutorial.rst
- zarr/codecs.py
- zarr/core.py
- zarr/hierarchy.py
- zarr/storage.py
- zarr/sync.py
- zarr/tests/test_core.py
- zarr/tests/test_hierarchy.py
- zarr/tests/test_sync.py
- zarr/tests/test_util.py
Various minor fixes and improvements to test coverage.
> V2.1.1 dev

- zarr/tests/test_core.py
Was "behavioud" now is "behaviour".
> Fix a typo in a comment

- zarr/attrs.py
- zarr/creation.py
- zarr/hierarchy.py
- zarr/storage.py
- zarr/tests/test_attrs.py
- zarr/tests/test_core.py
- zarr/tests/test_creation.py
- zarr/tests/test_filters.py
- zarr/tests/test_hierarchy.py
- zarr/tests/test_meta.py
- zarr/tests/test_storage.py
- zarr/tests/test_util.py
- zarr/util.py
Resolves #170 by implementing ``__dir__`` and ``_ipython_key_completions_`` on the ``Group`` class.
> Add ipython completion support

- tox.ini
- zarr/compat.py
- zarr/errors.py
- zarr/storage.py
- zarr/tests/test_storage.py
Resolves #158. Also resolves a similar bug related to pickle/unpickle.
> Tests and fixes for zipstore bugs re mode "w"

- zarr/storage.py
- zarr/tests/test_storage.py
> Clean up dbm files properly

- zarr/tests/test_convenience.py
- zarr/tests/test_core.py
- zarr/tests/test_hierarchy.py
- zarr/tests/test_storage.py
Clean up properly this time. Resolves #205.
> Fix test atexit

- docs/index.rst
This was pointing to @alimanfoo's personal repo.
> Update repo references

- docs/release.rst
- docs/tutorial.rst
- requirements_dev.txt
This PR has minor work to prep the full 2.2.0 release.
TODO:
> Release 2.2.0

- zarr/core.py
> Mark decoding as not covered by Python 2 tests

- docs/talks/scipy2019/submission.rst
This PR has a draft submission for a talk on Zarr for the SciPy 2019 conference. 
Comments and suggestions very welcome.
Resolves #396.
> SciPy 2019 submission

- README.rst
Fixes https://github.com/zarr-developers/zarr/issues/311
Adds a badge to the README with a link to Gitter.
TODO:
> Add Gitter badge to the README

- docs/release.rst
Adds a changelog entry for PR ( https://github.com/zarr-developers/zarr/pull/427 ).
cc @QuLogic
TODO:
> Note fix for endianness in tests

- docs/release.rst
Adds user and issue to release note for #485.
> Add user and issue to release note

- requirements_rtfd.txt
As in title.
TODO:
* [N/A] Add unit tests and/or doctests in docstrings
* [N/A] Add docstrings and API docs for any new/modified user-facing classes and functions
* [N/A] New/modified features documented in docs/tutorial.rst
* [?] Changes documented in docs/release.rst
> DOC: Use unittest.mock on Python 3.

- docs/release.rst
> Tweak Numcodecs 0.6.4+ release note wording          [ci skip]

- zarr/core.py
> Replace "nuimber" with "number"

- .github/ISSUE_TEMPLATE.md
xref https://github.com/zarr-developers/zarr-python/issues/520#issuecomment-558205786.
> Mention zarr-specs repo in the issue template

- zarr/storage.py
- zarr/tests/test_storage.py
Reference to issue #439
A quick fix to issue #439 
TODO:
* NA Add docstrings and API docs for any new/modified user-facing classes and functions
* NA New/modified features documented in docs/tutorial.rst
* NA Changes documented in docs/release.rst
* NA Docs build locally (e.g., run ``tox -e docs``)
> Fix Sqlite Store Wrong Modification

- docs/release.rst
- zarr/n5.py
- zarr/tests/test_core.py
> Fix N5Store.__contains__

- docs/release.rst
Re-add add the "Next Section" to have a place to write release notes.
> release notes back to dev

- .travis.yml
- codecov.yml
Coverall seem to have to hiccups, and show decrease of coverage when there is none.
> Try coverage with codecov

- docs/release.rst
- zarr/core.py
- zarr/storage.py
- zarr/tests/test_core.py
Adds tests for `Array` set up with `FSStore` and fixes the bug in  #644 
TODO:
> FSStore indexer error fix

- docs/release.rst
- zarr/creation.py
- zarr/hierarchy.py
> Forward mode option through normalize store args.

- docs/release.rst
Mostly update the what's new after reviewing and tagging all merged PR  and closed issues in the last month or so with the right milestone.
> Update release notes for 2.6

- .github/workflows/python-package.yml
> Try to restore PyMongo tests.

- .github/workflows/python-package.yml
> Try to re-enable Redis

- .github/workflows/windows-testing.yml
If we manage to get azurite on gh action + windows, we might be able to deactivate azzurite on appveyor and get the windows CI to much faster.
> Try to install azurite on Windows + GitHub Actions.

- docs/release.rst
Got one or two more PRs in. Propose to release as 2.7.0. Anything else anyone wants to add? Objections?
> Update 2.7.0 release notes

- setup.py
Update the "beta" development status to "mature". (Also add Python 3.9)
> Update Python classifiers (close #731)

- zarr/storage.py
> docs: Clarify how to manually convert a DirectoryStore to a ZipStore

- zarr/storage.py
- zarr/tests/test_dim_separator.py
Work on 2.9.0 let coverage drop. This tries to restore it.
> Shoot for 100% coverage

- .github/workflows/minimal.yml
- environment.yml
Rather than adding fsspec as a dependency to conda-forge,
this tests a conda-forge style minimal build for each PR.
> Actions: add minimal.yml (close #820)

- setup.cfg
Add [codespell](https://github.com/codespell-project/codespell) configuration to a newly created  `setup.cfg` file.
See also https://github.com/zarr-developers/zarr-python/pull/880#issuecomment-979234537.
TODO:
> Codespell configuration

- docs/contributing.rst
Closes https://github.com/zarr-developers/zarr-python/issues/919
> DOC: update create dev env

- zarr/creation.py
Minor doc fix, the `.. versionadded::` directive needs surrounding newlines.
cc. @jakirkham 
TODO:
> Minor doc fix

- docs/contributing.rst
Closes https://github.com/zarr-developers/zarr-python/issues/922
> DOC: update pytest line

- .github/workflows/Pre-commit-hooks.yml
- .pre-commit-config.yaml
Flake8 is already added.
and the following will be added soon.
With few changes
https://github.com/pre-commit/mirrors-mypy
https://github.com/adrienverge/yamllint.git
https://github.com/asottile/pyupgrade
With moderate changes
https://github.com/pre-commit/pre-commit-hooks
https://github.com/asottile/seed-isort-config
https://github.com/PyCQA/isort
With lots of changes
https://github.com/psf/black
> Pre-commit configuration

- .pre-commit-config.yaml
Yaml check for pre-commit.
Related to #1015 and #1012
> Added Yaml Check in Pre-commit

- .github/dependabot.yml
- .github/workflows/minimal.yml
- .github/workflows/python-package.yml
- .github/workflows/releases.yml
- .github/workflows/windows-testing.yml
Will have to address compatibility issues.
TODO:
> Update GitHub Actions

- LICENSE
- docs/conf.py
> adjustment of year in Docs

- docs/conf.py
fixes #1172
ref: https://github.com/sphinx-doc/sphinx/issues/10474
TODO:
> set docs confy.py language = 'en'

- docs/installation.rst
- docs/release.rst
> Fixed typo error

- README.md
> updated installation documentation link in readme

- docs/index.rst
- docs/license.rst
- docs/spec/v3.rst
> added license to docs and updated spec_v3

- docs/release.rst
- zarr/convenience.py
> Simpler if/else statement

- .github/workflows/minimal.yml
- .github/workflows/python-package.yml
- .github/workflows/windows-testing.yml
- docs/release.rst
Update to the recent `conda-incubator/setup-miniconda` and pin that release.
xref: https://github.com/zarr-developers/numcodecs/pull/398
<hr>
TODO:
> Use `conda-incubator/setup-miniconda@v2.2.0`

- docs/release.rst
- zarr/hierarchy.py
> Get coverage up to 100%

- docs/release.rst
- zarr/hierarchy.py
- zarr/tests/test_hierarchy.py
Fixes #1228
TODO:
* ~Add docstrings and API docs for any new/modified user-facing classes and functions~
* ~New/modified features documented in docs/tutorial.rst~
> Fix double counting V3 groups bug

- .github/workflows/needs_release_notes.yml
See https://github.com/zarr-developers/zarr-python/pull/1270#issuecomment-1319618071
This also narrows down the PRs that we are labeling, in line with #1226.
TODO:
> Skip labeler for bot PRs

- docs/release.rst
- notebooks/dask_copy.ipynb
- notebooks/dask_count_alleles.ipynb
> http:// → https://

- docs/release.rst
Kicking off the release process. Comments on which scope ("maintenance", "major", etc) each PR should belong to welcome. Thanks to @MSanKeys963 for drafting this over the holidays! :tada:
> 2.13.4/2.14.0 draft release notes

- docs/release.rst
Also tidy release notes
xref: https://github.com/zarr-developers/zarr-python/pull/1285#issuecomment-1397468044
cc @joshmoore @madsbk
<hr>
TODO:
> Add FSStore contiguous bug fix note

- docs/_static/custom.js
- docs/release.rst
Check for hash in anchormap. Fix issues in the links of, e.g., api.html
TODO:
> Fix 2.14.0 redirects

- .github/workflows/python-package.yml
Fixes https://github.com/zarr-developers/zarr-python/issues/1390
TODO:
> Remove `codecov`

- docs/release.rst
Added release note for #1391. Feel free to merge this, @jakirkham.
> Update release.rst for 2.15.0

- docs/release.rst
> Mark for 2.15.0a1 pre-release

- docs/release.rst
> Fix typo introduced by dcce26e

- docs/release.rst
This PR prepares our release notes for the 2.16.0 release. I'll do the release as soon as this is merged.
TODO:
> Updated release notes for 2.16.0

- docs/tutorial.rst
> Fix typo newly found by codespell

- pyproject.toml
> Remove  dependency

- README-v3.md
- pyproject.toml
A minor addition to the readme Ryan created for today's Zarr V3 sprint.
> Add env variables to sprint setup instructions

- .readthedocs.yaml
- README-v3.md
- pyproject.toml
Part of https://github.com/zarr-developers/zarr-python/issues/1648
> Specify docs hatch env for v3 branch

- zarr/_storage/store.py
- zarr/tests/test_core.py
> Couple fixes

- .pre-commit-config.yaml
- src/zarr/convenience.py
- src/zarr/n5.py
- src/zarr/storage.py
- src/zarr/util.py
- src/zarr/v3/common.py
- tests/v3/test_common.py
- tests/v3/test_metadata.py
Nothing exciting here. Just a bit of house cleaning on the v3 for the v3 branch.
TODO:
> V3 update pre commit

- .pre-commit-config.yaml
> chore(pre-commit): update pre-commit versions and remove attrs dep mypy section

- docs/release.rst
Includes the fix to #1874 and #1883. Thanks @dcherian!
TODO:
> release notes for 2.18.1

- pyproject.toml
- src/zarr/group.py
> fix(types): Group.info -> NotImplementedError

- src/zarr/codecs/transpose.py
- tests/v3/test_codecs.py
@zoj613 [reported a bug](https://github.com/scalableminds/zarrita/issues/14) with the transpose codec in zarrita. This PR ports the fix over to zarr-python-
> Fixes bug in transpose

- pyproject.toml
All issues seem to have been fixed.
TODO:
> Stop ignoring these ruff rules

- src/zarr/indexing.py
> Redundant list comprehension

- src/zarr/group.py
> Apply ruff/flake8-bandit rule B006

- .pre-commit-config.yaml
- pyproject.toml
updates:
- [github.com/astral-sh/ruff-pre-commit: v0.5.7 → v0.6.3](https://github.com/astral-sh/ruff-pre-commit/compare/v0.5.7...v0.6.3)
I hope this can help with a few issues in #2110.
TODO:
> Bump ruff version

- TEAM.md
Welcoming @dcherian and @TomAugspurger to the @zarr-developers/python-core-devs team!
> Adding Deepak and Tom to the core team

- docs/_static/custom.css
Backports the low contrast fix to the `main` branch.
> Backport #2287 to main

- src/zarr/abc/codec.py
- src/zarr/codecs/__init__.py
- tests/v3/test_indexing.py
> Apply ruff rules (RUF)

- pyproject.toml
- src/zarr/testing/strategies.py
> Enforce ruff/flake8-annotations rule ANN003

- pyproject.toml
Syncing with https://github.com/zarr-developers/zarr-python/blob/main/TEAM.md
> chore: update package maintainers

- .github/workflows/test.yml
- pyproject.toml
We should have the necessary support in our dependencies now.
TODO:
> chore: add python 3.13 to ci / pyproject.toml

- .pep8speaks.yml
See also https://github.com/zarr-developers/numcodecs/pull/612.
TODO:
> Get rid of pep8speaks - replaced by ruff

- src/zarr/core/array.py
Introduced by #2400 / e5135f9.
TODO:
> Unreachable code

- pyproject.toml
> Bump numcodecs

- tests/test_indexing.py
> Multiple imports for an import name

- .pre-commit-config.yaml
- pyproject.toml
- src/zarr/core/group.py
See [Removal of six deprecated rules](https://astral.sh/blog/ruff-v0.8.0#removal-of-six-deprecated-rules).
TODO:
> Update ruff and associated changes

- src/zarr/storage/memory.py
Fixes https://github.com/zarr-developers/zarr-python/issues/2598
> Un-mark memory store as "for testing"

- docs/user-guide/consolidated_metadata.rst
See https://github.com/zarr-developers/zarr-python/pull/2589#discussion_r1901835508
> show pprint import

- docs/user-guide/v3_migration.rst
Two more "known issues" for the v3 migration guide.
> add known bugs to work in progress section of the v3 migration guide

- docs/release-notes.rst
- pyproject.toml
Fixes https://github.com/zarr-developers/zarr-python/issues/2678
> Remove un-needed files from source distribution

- docs/release-notes.rst
Following up after #2726 
TODO:
> doc: seed unreleased release notes

- src/zarr/core/metadata/v2.py
> Redundant list comprehension can be replaced using generator

- src/zarr/testing/strategies.py
> Unnecessary lambda expression

- changes/2908.bugfix.rst
- docs/release-notes.rst
> release: update release notes for 3.0.6

- docs/release.rst
Assuming all the tests pass, I'll merge this and do a release.
> Update release notes for 2.18.5

- docs/release.rst
Assuming this passes, I will self merge and do a release in order to un-break 2.18.* installations.
> Add a changelog for 2.18.6

- tests/test_group.py
Suggested by [DeepSource](https://app.deepsource.com/gh/DimitriPapadopoulos/zarr-python/issue/PYL-R1717/.occurrences). This micro-optimisation might be faster, but I'm not convinced it improves readability/maintainability.
TODO:
> Use a dictionary comprehension instead

- pyproject.toml
- tests/package_with_entrypoint/__init__.py
- tests/test_codecs/test_transpose.py
- tests/test_config.py
I had a long train journey yesterday, so here's some misc mypy fixes.
> Fix some mypy errors

- pyproject.toml
> Clean up after getting rid of notebooks

- changes/3068.bugfix.rst
- changes/3156.bugfix.rst
- src/zarr/core/common.py
- src/zarr/storage/_common.py
- tests/test_api.py
- tests/test_common.py
- tests/test_store/test_core.py
> Backport PR #3156 on branch 3.0.9 (Create read only copy if needed when opening a store path)

- .github/workflows/hypothesis.yaml
We have upstreamed the action during the scipy sprint...
> CI: update actions location

- docs/about.rst
MRC Centre for Genomics and Global Health (CGGH)
Correct link: 
https://github.com/cggh/
The original link does not work:
http://www.cggh.org/
TODO:
> Update the link to CGGH non-profit organization

- pyproject.toml
> pin setuptools-scm to !=9.0.0

- changes/3425.bugfix.rst
- src/zarr/core/common.py
> fix: `ChunkCoords` definition

- changes/1798.feature.rst
- changes/2582.bugfix.rst
- changes/2859.removal.rst
- changes/2992.bugfix.rst
- changes/3310.feature.rst
- changes/3376.misc.rst
- changes/3390.misc.rst
- changes/3403.misc.rst
- changes/3411.bugfix.rst
- changes/3422.bugfix.rst
- changes/3425.bugfix.rst
- changes/3428.bugfix.rst
- changes/3431.bugfix.rst
- changes/3436.feature.rst
- changes/3444.feature.rst
- changes/3448.bugfix.rst
- changes/3449.misc.rst
- docs/release-notes.rst
> 3.1.3 release notes

- changes/3118.doc.md
Small follow-up to #3118 to add a changelog entry
> Changelog entry for docs change
